documentation/src/main/docbook/en-US/reference-guide/10-performance-tuning.xml
documentation/src/main/docbook/en-US/reference-guide/3-command-handling.xml
documentation/src/main/docbook/en-US/reference-guide/4-domain-modeling.xml
documentation/src/main/docbook/en-US/reference-guide/5-repositories-and-event-stores.xml
documentation/src/main/docbook/en-US/reference-guide/6-event-listeners.xml
documentation/src/main/docbook/en-US/reference-guide/7-sagas.xml
documentation/src/main/docbook/en-US/reference-guide/8-testing.xml
documentation/src/main/docbook/en-US/reference-guide/9-using-spring.xml

Hey,
I went through the Axon reference guide to brush up my Axon 2.0 knowledge, and fixed some typo's that I encountered.

Fixed typo's in the Axon 2.0 reference guide

---

core/src/main/java/org/axonframework/eventstore/jdbc/DefaultEventEntryStore.java

The loadLastSnapshotEvent in the JDBC DefaultEventEntryStore did not close the PreparedStatement after usage which leads to the leakage of open cursor on a DB level.

Fix for Statement leak in the loadLastSnapshotEvent method

---

mongo/src/test/java/org/axonframework/mongoutils/MongoLauncher.java

Uses a client socket to the default mongo port. I found that this detection was failing locally using a listening socket but the client socket approach worked.

Updated MongoDB detection

---

core/src/main/java/org/axonframework/saga/repository/jpa/JpaSagaRepository.java
core/src/main/java/org/axonframework/unitofwork/UnitOfWorkListenerCollection.java
core/src/test/java/org/axonframework/unitofwork/UnitOfWorkListenerCollectionTest.java

Allard,
These are team submissions for changes/fixes for problems we have encountered during performance testing our Axon services. The named queries provides a minor uplift the second is a cleanup approach for Units of work.

Axon 2.4.x

---

amqp/src/main/java/org/axonframework/eventhandling/amqp/spring/ExtendedMessageListenerContainer.java
core/src/main/java/org/axonframework/contextsupport/spring/AutowiredDependencyFactoryBean.java
core/src/main/java/org/axonframework/contextsupport/spring/SpringParameterResolverFactoryBean.java
core/src/main/java/org/axonframework/eventhandling/AbstractCluster.java
core/src/main/java/org/axonframework/eventsourcing/HybridJpaRepository.java

While initially reading the source I fixed some minor warning and comment wording. 
Turns out that I have no real feature to code, so I am offering these two commits rather than throwing them away.

Remove some warnings and comment errors

---

core/src/main/java/org/axonframework/serializer/json/JacksonSerializer.java

for approximately 10% faster event playback. YMMV

Added a class-lookup cache to the Jackson Serializer

---

readme.md

self explanatory but it really bugs me :)

fix wrong redirects in readme

---

.travis.yml

Starting experimentation with publicly available build

Added travis config file

---

core/src/main/java/org/axonframework/messaging/interceptors/BeanValidationInterceptor.java
core/src/main/java/org/axonframework/messaging/interceptors/JSR303ViolationException.java

@abuijze as promised :-) 
ps sorry about the import reordering, my git-fu is too weak to try and redo the pull request without it :-|

improve exception message in case of jsr303 validation

---

core/src/main/java/org/axonframework/common/jdbc/ConnectionWrapperFactory.java
core/src/test/java/org/axonframework/common/jdbc/ConnectionWrapperFactoryTest.java

This pull request contains a cosmetic change. The wrappers created by the ConnectionWrapperFactory class may throw InvocationTargetException exceptions that wrap the original exception.
In some cases it is not required for exceptions to be wrapped by InvocationTargetException. This pull request makes sure that in those cases the nested exceptions will be unwrapped.

AXON-12271

---

core/src/main/java/org/axonframework/serialization/json/MetaDataDeserializer.java

This is a PR as requested  in http://issues.axonframework.org/youtrack/issue/AXON-368 for the master branch

AXON-368 fix in master (3.x) branch

---

core/src/main/java/org/axonframework/serializer/json/MetaDataDeserializer.java

This is a PR for the 2.4.x branch as requested in http://issues.axonframework.org/youtrack/issue/AXON-368

AXON-368 fix in 2.4.x branch

---

core/src/main/java/org/axonframework/config/Configuration.java
core/src/main/java/org/axonframework/config/Configurer.java
core/src/main/java/org/axonframework/config/SagaConfiguration.java
core/src/main/java/org/axonframework/eventhandling/scheduling/EventScheduler.java
core/src/main/java/org/axonframework/eventsourcing/EventSourcedAggregate.java
core/src/main/java/org/axonframework/serialization/json/JacksonSerializer.java
quickstart/src/main/java/org/axonframework/quickstart/AxonSpringConfiguration.java
quickstart/src/main/java/org/axonframework/quickstart/annotated/ToDoItem.java
spring/src/main/java/org/axonframework/spring/config/AnnotationDriven.java
spring/src/main/java/org/axonframework/spring/config/AxonConfiguration.java
spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java

Hi, I am hacking a bit with the codebase, looking to put together some sort of spring boot starter project to quickstart an opinionated setup.
I think these are useful commits on the way to 3.0 stable, please check them out.
PS: The new autoconfig looks good, but I would like to see an example of a non trivial modular setup.
Cheers

Miscellaneous improvements

---

core/src/main/java/org/axonframework/eventhandling/saga/repository/inmemory/InMemorySagaStore.java

* fixed an IllegalArgumentException in InMemorySagaStore thrown when multiple sagas are set up to handle the same event.
full stacktrace can be found at  https://groups.google.com/d/topic/axonframework/tsmdwxQZoWw/discussion

fix a bug in the InMemorySagaStore

---

spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java

If you use @EnableAxon and create a FactoryBean then a NullPointerException will be thrown. BeanFactory.getType returns null if the bean name passed to it is the name of a factory bean, consequently null will be passed to ReflectionUtils.methodsOf. See SpringAxonAutoConfigurer.registerDefaultEventHandlerConfiguration for more details.
For now I have edited the code, so factory beans will be disregarded when looking for message handlers. I am not sure if this is the best solution, so I am open to suggestions.
The following code triggers the bug:
```java
@Configuration
@EnableAxon
public class Config {
@Bean
public FactoryBean<Foobar> foobarFactoryBean() {
return new FoobarFactoryBean();
}
public static class Foobar {
}
public static class FoobarFactoryBean implements FactoryBean<Foobar> { …
```

Fix NullPointerException

---

metrics/src/main/java/org/axonframework/metrics/PayloadTypeMessageMonitorWrapper.java
metrics/src/test/java/org/axonframework/metrics/PayloadTypeMessageMonitorWrapperTest.java

A Message Monitor implementation which gets or creates a specific MessageMonitor for every payload type encountered during message ingestion and call onMessageIngested on it.

Payload type message monitor wrapper

---

core/src/main/java/org/axonframework/eventsourcing/eventstore/DomainEventStream.java
core/src/test/java/org/axonframework/eventsourcing/eventstore/EventUtilsTest.java
spring-boot-autoconfigure/src/main/java/org/axonframework/boot/AxonAutoConfiguration.java

Avoid NullPointerException on empty DomainEventStream and Backward compatibility with spring 4.2.3

---

test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
test/src/main/java/org/axonframework/test/aggregate/TestExecutor.java
test/src/test/java/org/axonframework/test/aggregate/FixtureTest_Annotated.java

FixtureConfiguration: Allow a mix of given events and commands

---

spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java

Unable to configure ListenerInvocationErrorHandler using Spring

---

core/src/main/java/org/axonframework/eventhandling/saga/repository/jpa/SagaEntry.java
core/src/main/java/org/axonframework/eventhandling/tokenstore/AbstractTokenEntry.java
core/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventEntry.java

Hibernate AutoDDL generates columns with a maxsize of 255 for @Lob annotations

---

spring/src/main/java/org/axonframework/spring/messaging/DefaultEventMessageConverter.java
spring/src/main/java/org/axonframework/spring/messaging/EventMessageConverter.java
spring/src/main/java/org/axonframework/spring/messaging/InboundEventMessageChannelAdapter.java
spring/src/main/java/org/axonframework/spring/messaging/OutboundEventMessageChannelAdapter.java
spring/src/test/java/org/axonframework/spring/messaging/DefaultEventMessageConverterTest.java

OutboundEventMessageChannelAdapter: wrong conversion of GenericDomainEventMessage

---

core/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java

Limit the amount of rows returned by adding a WHERE clause instead of using `PreparedStatement.setMaxRows(int)`.
Note that the latter discards rows from the `ResultSet` only and does not improve database performance, as mentioned in the JavaDoc:
```
void setMaxRows(int max) throws SQLException:
Sets the limit for the maximum number of rows that any ResultSet object generated by this Statement object can contain to the given number. If the limit is exceeded, the excess rows are silently dropped.
```
In our case we have a tracking event processor that is started after there are already 150 million events in the event store. On startup it attempts to execute the following query, causing the database to become unresponsive: 
`SELECT globalIndex, eventIdentifier, timeStamp, payloadType, …

Limit the amount of rows returned by adding a WHERE clause in JdbcEventStorageEngine

---

core/src/main/java/org/axonframework/commandhandling/distributed/ConsistentHash.java
core/src/main/java/org/axonframework/commandhandling/distributed/Member.java
core/src/main/java/org/axonframework/commandhandling/distributed/SimpleMember.java
distributed-commandbus-jgroups/src/main/java/org/axonframework/jgroups/commandhandling/JGroupsConnector.java
distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringCloudCommandRouter.java
distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringHttpCommandBusConnector.java
distributed-commandbus-springcloud/src/test/java/org/axonframework/springcloud/commandhandling/SpringCloudCommandRouterTest.java
distributed-commandbus-springcloud/src/test/java/org/axonframework/springcloud/commandhandling/SpringHttpCommandBusConnectorTest.java

DistributedCommandBus: Ability to identify local member

---

spring-boot-autoconfigure/src/main/java/org/axonframework/boot/AxonAutoConfiguration.java
spring-boot-autoconfigure/src/test/java/org/axonframework/boot/AxonAutoConfigurationWithHibernateTest.java

The JpaEventStorageEngine now uses the Seriallizer bean .

Use Serializer in autoconfigured JpaEventStorageEngine.

---

core/src/main/java/org/axonframework/eventhandling/scheduling/quartz/FireEventJob.java
core/src/main/java/org/axonframework/serialization/upcasting/event/SingleEventUpcaster.java

Pr for #317 #319

---

spring-boot-autoconfigure/pom.xml
spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/AxonAutoConfiguration.java
spring-boot-autoconfigure/src/test/java/org/axonframework/boot/AxonAutoConfigurationWithDisruptorTest.java

Currently it is impossible to use the disruptor commandbus together with the autoconfiguration, 
This is a small fix for the issue

fixes for using disruptor commandbus ea.

---

amqp/src/main/java/org/axonframework/amqp/eventhandling/legacy/EventMessageReader.java
amqp/src/main/java/org/axonframework/amqp/eventhandling/legacy/EventMessageWriter.java
amqp/src/test/java/org/axonframework/amqp/eventhandling/legacy/JavaSerializationAMQPMessageConverterTest.java

Make JavaSerializationAMQPMessageConverter compatible with Axon 2

---

core/src/main/java/org/axonframework/saga/annotation/AsyncSagaEventProcessor.java

Followup to 3c260e57.
When running with multiple application instances and with row-level
locking of saga entries, if there were multiple processor threads for an
AsyncSagaEventProcessor, it was possible to get into a deadlock between
the wait for the row lock and the wait for the saga creation vote:
Instance A
Saga thread 1
Previously processed an event for saga S and still holds the lock
Processing an event for new saga N and waiting for the creation vote
Saga thread 2
Waiting for the row lock on saga X
Instance B
Saga thread 1
Previously processed an event for saga X and still holds the lock
Processing an event for new saga Q and waiting for the creation vote
Saga thread 2
Waiting for the row lock on saga S
This fix takes a similar approach to 3c260e57 and flushes any pending
saga …

Deadlock in AsyncSagaEventProcessor with row locks

---

core/src/main/java/org/axonframework/eventhandling/saga/repository/jdbc/GenericSagaSqlSchema.java

AUTO_GENERATED is not supported in MySQL

Set AUTO_INCREMENT on id field in Saga association table

---

core/src/main/java/org/axonframework/config/DefaultConfigurer.java

Fix #378: Added support for Transaction for DefaultConfigurer.jpaConfiguration()

Added support for custom TransactionManager in DefaultConfigurer

---

core/src/main/java/org/axonframework/commandhandling/AsynchronousCommandBus.java
core/src/main/java/org/axonframework/commandhandling/SimpleCommandBus.java
core/src/main/java/org/axonframework/commandhandling/disruptor/DisruptorCommandBus.java
core/src/main/java/org/axonframework/commandhandling/distributed/DistributedCommandBus.java
core/src/test/java/org/axonframework/commandhandling/SimpleCommandBusTest.java
core/src/test/java/org/axonframework/commandhandling/disruptor/DisruptorCommandBusTest.java
core/src/test/java/org/axonframework/commandhandling/distributed/DistributedCommandBusTest.java

command bus does not call MonitorCallback#reportFailure when no handler can be found for command

---

core/src/main/java/org/axonframework/eventhandling/saga/repository/jpa/AssociationValueEntry.java

Issue #524: Define indices for AssociationValueEntry

---

core/src/main/java/org/axonframework/eventhandling/saga/repository/jdbc/GenericSagaSqlSchema.java
core/src/main/java/org/axonframework/eventhandling/saga/repository/jpa/JpaSagaStore.java

[#527] SQL based SagaStore's should use saga identifier as primary key

---

core/src/main/java/org/axonframework/config/EventHandlingConfiguration.java

#532 Wrap invocation of both default and fallback selectors in a lambda

---

amqp/pom.xml
amqp/src/test/java/org/axonframework/amqp/eventhandling/spring/SpringAMQPMessageSourceTest.java
core/src/test/java/org/axonframework/commandhandling/AggregateAnnotationCommandHandlerTest.java
core/src/test/java/org/axonframework/commandhandling/disruptor/CommandHandlerInvokerTest.java
core/src/test/java/org/axonframework/commandhandling/gateway/CommandGatewayFactoryTest.java
core/src/test/java/org/axonframework/commandhandling/gateway/DefaultCommandGatewayTest.java
core/src/test/java/org/axonframework/commandhandling/model/AnnotatedAggregateTest.java
core/src/test/java/org/axonframework/commandhandling/model/EventSourcingRepositoryTest.java
core/src/test/java/org/axonframework/eventhandling/TrackingEventProcessorTest.java
core/src/test/java/org/axonframework/eventhandling/scheduling/java/SimpleEventSchedulerTest.java
core/src/test/java/org/axonframework/eventsourcing/AbstractSnapshotterTest.java
core/src/test/java/org/axonframework/messaging/DefaultInterceptorChainTest.java
core/src/test/java/org/axonframework/messaging/annotation/MultiParameterResolverFactoryTest.java
core/src/test/java/org/axonframework/messaging/interceptors/LoggingInterceptorTest.java
core/src/test/java/org/axonframework/queryhandling/DefaultQueryGatewayTest.java
distributed-commandbus-jgroups/pom.xml
distributed-commandbus-jgroups/src/test/java/org/axonframework/jgroups/commandhandling/JGroupsConnectorTest.java
distributed-commandbus-jgroups/src/test/java/org/axonframework/jgroups/commandhandling/JgroupsConnectorTest_Gossip.java
distributed-commandbus-springcloud/src/test/java/org/axonframework/springcloud/commandhandling/SpringCloudCommandRouterTest.java
distributed-commandbus-springcloud/src/test/java/org/axonframework/springcloud/commandhandling/SpringCloudHttpBackupCommandRouterTest.java
distributed-commandbus-springcloud/src/test/java/org/axonframework/springcloud/commandhandling/SpringHttpCommandBusConnectorTest.java
integrationtests/pom.xml
integrationtests/src/test/java/org/axonframework/integrationtests/commandhandling/EventPublicationOrderTest.java
pom.xml
spring/pom.xml
spring/src/test/java/org/axonframework/spring/config/EventHandlerRegistrarTest.java
spring/src/test/java/org/axonframework/spring/eventsourcing/SpringAggregateSnapshotterFactoryBeanTest.java
spring/src/test/java/org/axonframework/spring/messaging/OutboundEventMessageChannelAdapterTest.java

Upgraded Mockito to 2.0 as per #541

Mockito 2.0 

---

test/src/main/java/org/axonframework/test/aggregate/Reporter.java
test/src/main/java/org/axonframework/test/aggregate/ResultValidator.java
test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java
test/src/test/java/org/axonframework/test/aggregate/FixtureTest_ExceptionHandling.java

I add assertions for exception message.

Add exception message assertions

---

core/src/main/java/org/axonframework/eventhandling/ReplayToken.java
core/src/main/java/org/axonframework/eventsourcing/eventstore/TrackingToken.java
core/src/test/java/org/axonframework/eventhandling/ReplayTokenTest.java
core/src/test/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStoreTest.java

Fixed jackson serialization/deserialization of ReplayToken.

---

spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
spring/src/main/java/org/axonframework/spring/stereotype/Aggregate.java
spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java

Extended @Aggregate annotation with possibility to specify custom CommandTargetResolver.
Resolves #544

Extended @Aggregate with commandTargetResolver

---

core/src/main/java/org/axonframework/eventhandling/ReplayToken.java
mongo/pom.xml
mongo/src/main/java/org/axonframework/mongo/eventsourcing/eventstore/MongoTrackingToken.java
mongo/src/test/java/org/axonframework/mongo/eventsourcing/eventstore/MongoTrackingTokenTest.java

MongoTrackingToken and ReplayToken are now serializable.

---

spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
spring/src/main/java/org/axonframework/spring/stereotype/Aggregate.java
spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java

Command Target Resolver bean is picked up from application context and assigned as default command target resolver.
Resolves #601

Command Target Resolver bean in application context

---

core/src/main/java/org/axonframework/queryhandling/responsetypes/AbstractResponseType.java
core/src/main/java/org/axonframework/queryhandling/responsetypes/InstanceResponseType.java
core/src/main/java/org/axonframework/queryhandling/responsetypes/MultipleInstancesResponseType.java
core/src/test/java/org/axonframework/queryhandling/responsetypes/ResponseTypesJacksonSerializationTest.java

Added Jackson annotations for serialization/deserialization of response types.

Jackson serialization/deserialization of response types

---

distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringCloudCommandRouter.java
distributed-commandbus-springcloud/src/test/java/org/axonframework/springcloud/commandhandling/SpringCloudCommandRouterTest.java

If blacklisted service instance is not present on heartbeat, remove it from the blacklist.
Resolves #546

Blacklist cleaning

---

core/src/main/java/org/axonframework/common/jdbc/JdbcUtils.java
core/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java
core/src/test/java/org/axonframework/common/jdbc/JdbcUtilsTest.java
core/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/MysqlJdbcEventStorageEngineTest.java

Fixed issue #636

---

core/src/main/java/org/axonframework/config/EventHandlingConfiguration.java
spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/AxonAutoConfiguration.java
spring-boot-autoconfigure/src/test/java/org/axonframework/boot/EventProcessorConfigurationTest.java
spring-boot-autoconfigure/src/test/resources/test-processors.application.properties

[#660] Added support to define SequencingPolicy in EventHandlingConfiguration

---

core/src/main/java/org/axonframework/eventhandling/MultiEventHandlerInvoker.java
core/src/test/java/org/axonframework/eventhandling/MultiEventHandlerInvokerTest.java

MultiHandlerInvoker reset awareness.

---

core/src/main/java/org/axonframework/queryhandling/QueryBus.java
core/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java

[ #656] Interceptors on query bus

---

core/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
core/src/main/java/org/axonframework/eventhandling/TrackingEventProcessorConfiguration.java
core/src/test/java/org/axonframework/eventhandling/TrackingEventProcessorTest.java
core/src/test/java/org/axonframework/eventhandling/TrackingEventProcessorTest_MultiThreaded.java

[#634] TrackingEventProcessor release segment

---

core/src/main/java/org/axonframework/config/DefaultConfigurer.java
core/src/test/java/org/axonframework/config/ConfigurationScopeAwareProviderTest.java
core/src/test/java/org/axonframework/config/DefaultConfigurerTest.java

[Bugfix #788] Shutdown handler not registered properly 

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/AxonDBClient.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
core/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java
pom.xml

Added support for snapshot filter in AxonServer event store. 

---

core/src/main/java/org/axonframework/eventhandling/saga/repository/jdbc/JdbcSagaStore.java

PR for 3.4.x branch instead of 3.2.x (#853)

[#853] Fix connection leak when loading saga

---

eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/Oracle11EventTableFactory.java
messaging/src/main/java/org/axonframework/common/jdbc/Oracle11Utils.java
modelling/src/main/java/org/axonframework/modelling/saga/repository/jdbc/Oracle11SagaSqlSchema.java

All hail to SonarQube.
This PR resolves #854.

Added some try-with-resources to fix resource leaks

---

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java

This is #835 but branched from `axon-4.0.x`

Fix: Spring boot autoconfiguration query gateway

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ErrorCode.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/ErrorCodeTest.java

Do not try to convert a null source, provide an empty string instead.

---

core/src/test/java/org/axonframework/eventhandling/TrackingEventProcessorTest.java

Remove duplicate test method

---

test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
test/src/main/java/org/axonframework/test/aggregate/FixtureConfiguration.java
test/src/test/java/org/axonframework/test/aggregate/FixtureTest_Annotated.java

[#628] Allow registering custom CommandTargetResolver within test fixture

---

config/src/main/java/org/axonframework/config/Configurer.java

Added a convenience method to register an EventHandler builder.

---

integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
messaging/src/main/java/org/axonframework/eventhandling/GlobalSequenceTrackingToken.java
messaging/src/test/java/org/axonframework/eventhandling/GlobalSequenceTrackingTokenTest.java

Hi,
Creating a pull request for a bug that I had already mentioned on the forum and discussed with @abuijze. See https://groups.google.com/forum/#!topic/axonframework/n0RXgGwD7e4 for details.
Regards,
Jens

Fixed GlobalSequenceTrackingToken.covers and added unit tests

---

metrics/src/main/java/org/axonframework/metrics/GlobalMetricRegistry.java

fix(metrics): CapacityMonitor for EventProcessor

---

core/src/main/java/org/axonframework/eventsourcing/eventstore/GlobalSequenceTrackingToken.java
core/src/test/java/org/axonframework/eventhandling/TrackingEventProcessorTest.java

https://github.com/AxonFramework/AxonFramework/issues/970

Fix covers method off-by-one error on GlobalSequenceTrackingToken

---

core/src/main/java/org/axonframework/commandhandling/AggregateAnnotationCommandHandler.java
core/src/main/java/org/axonframework/commandhandling/disruptor/DisruptorCommandBus.java
core/src/main/java/org/axonframework/commandhandling/distributed/ConsistentHash.java
core/src/main/java/org/axonframework/commandhandling/gateway/CommandGatewayFactory.java
core/src/main/java/org/axonframework/commandhandling/model/inspection/AnnotatedAggregateMetaModelFactory.java
core/src/test/java/org/axonframework/commandhandling/distributed/ConsistentHashTest.java

Hi.
My first PR on Github. Please be kind :-)
I'd like to help on Reactor integration.
I thought making some minor improvements on the project could help me better understand how it is organized.
Are you interested in that kind of "upgrade". I've only looked at core>commandhandling package so far but i can go on if you like.
Cheers,

Java 8 friendly

---

messaging/src/main/java/org/axonframework/commandhandling/gateway/AbstractCommandGateway.java
messaging/src/main/java/org/axonframework/eventhandling/gateway/AbstractEventGateway.java
messaging/src/main/java/org/axonframework/eventhandling/gateway/DefaultEventGateway.java
messaging/src/main/java/org/axonframework/eventhandling/gateway/EventGateway.java
messaging/src/test/java/org/axonframework/eventhandling/gateway/DefaultEventGatewayTest.java

[#954] Introduce an EventGateway to simplify Event Message publication 

---

.travis.yml
eventsourcing/pom.xml
messaging/src/test/java/org/axonframework/deadline/quartz/DeadlineJobDataBinderTest.java
messaging/src/test/java/org/axonframework/eventhandling/scheduling/quartz/DirectEventJobDataBinderTest.java
spring/pom.xml

fix compilation of module "eventsourcing" on JDK 11

Fix compilation of "eventsourcing" module on JDK 11

---

core/src/main/java/org/axonframework/deadline/quartz/DeadlineJob.java

QuartzDeadlineManager doesn't retry job execution in case of failure

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java

Changed compare function for BlockingQueue to use negative value of prio, as current interpretation is higher value means higher priority.

Priority setting for commands and queries

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java

Check if connected to Axon Server before sending instruction.

---

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java

The `@ConditionalOnMissingBean` annotation on the `CommandBus` Bean creation function shouldn't use the `AxonServerCommandBus.class` in the `ignored` parameter. Instead, it should leverage the fully qualified class name as a `String`.
Without this change, one cannot exclude the `axon-server-connector` *and* use `axon-spring-boot-starter` in the same time, as the Auto Configuration misses the `AxonServerCommandBus` class.
This issue resolves #1034

[#1034] Change ConditionalOnMissingBean annotation

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/ResubscribableStreamObserver.java
pom.xml

Defined a unified way of dealing with gRPC Error Handling.

Grpc error handling improvement

---

spring/src/main/java/org/axonframework/spring/config/CommandHandlerSubscriber.java
spring/src/main/java/org/axonframework/spring/config/QueryHandlerSubscriber.java
spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java

I adjusted a couple of classes in order to support hierarchical application contexts as explained in #1055.
Honestly, I'm not sure I got all the places which are needed as this implementation is driven by our project's needs. Anyway, using this implementation one could the components declared by a parent context in a child context.

[#1055] Support for hierarchical application contexts added

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/grpc/TrackingEventProcessorInfoMessage.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/grpc/FakeEventTrackerStatus.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/grpc/TrackingEventProcessorInfoMessageTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
messaging/src/main/java/org/axonframework/eventhandling/EventTrackerStatus.java
messaging/src/main/java/org/axonframework/eventhandling/MergedTrackingToken.java
messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
messaging/src/test/java/org/axonframework/eventhandling/MergedTrackingTokenTest.java
pom.xml

This pull request resolves #1063

[#1063] Tracking processor error status

---

config/src/main/java/org/axonframework/config/EventProcessingModule.java
integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/SubscribingEventProcessorTest.java
messaging/src/main/java/org/axonframework/eventhandling/SubscribingEventProcessor.java

Not sure if there's more to it.. Could have another test maybe to make sure the configuration uses the configured `TransactionManger`.
This PR resolves #1074

Issue #1074: TransactionManager for SubscribingEventProcessor

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/GrpcBufferingInterceptor.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/util/GrpcBufferingInterceptorTest.java

This PR adds the ability to request more messages from the server, increasing the flow of messages that may be sent simultaneously from server to client.

Improvement grpc message flow

---

eventsourcing/src/test/java/org/axonframework/eventsourcing/MultiStreamableMessageSourceTest.java
messaging/src/test/java/org/axonframework/eventhandling/MultiSourceTrackingTokenTest.java

This is a work in progress.  I'll add to it as I have time.
This PR aims to provide resolution on #1101.

Attempting to complete feature/multiSourceEventProcessing

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java

This is a hotfix for a possible deadlock between the `AxonServerConnectionManager` and `AxonServerQueryBus`/`AxonServerCommandBus`.
There are not unit test included because I was not able to reproduce it locally.

Resolution for Potential Deadlock

---

messaging/src/main/java/org/axonframework/commandhandling/gateway/AbstractRetryScheduler.java
messaging/src/main/java/org/axonframework/commandhandling/gateway/ExponentialBackOffIntervalRetryScheduler.java
messaging/src/main/java/org/axonframework/commandhandling/gateway/IntervalRetryScheduler.java
messaging/src/main/java/org/axonframework/common/BuilderUtils.java
messaging/src/test/java/org/axonframework/commandhandling/gateway/ExponentialBackOffIntervalRetrySchedulerTest.java
messaging/src/test/java/org/axonframework/commandhandling/gateway/IntervalRetrySchedulerTest.java
messaging/src/test/java/org/axonframework/common/BuilderUtilsTest.java

- Extracted a common base class, which only needs the specifics for
the strategy to follow when deciding how long to wait.
- Added an assertPositive() for longs to the BuilderUtils
- Used Generics on the Builder to make fluent interfacing work

Added an exponential backoff retry scheduler

---

messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStore.java

Stop using updatable result sets to write to the token store. This results in a huge performance increase under PostgreSQL.
It may be possible to get rid of most or all of the `SELECT FOR UPDATE`s as well (by adding more conditions to the `UPDATE` statements such that they fail to update if the token can't be claimed) which would further improve performance. But that'd be a more significant structural change; this PR keeps the same basic structure, just changes how the actual writes are done.
All the existing JUnit tests pass, which should mean this doesn't change any behavior.
This PR resolve #1165.

[#1165] Use explicit UPDATEs in JdbcTokenStore

---

disruptor/src/main/java/org/axonframework/disruptor/commandhandling/EventPublisher.java
disruptor/src/test/java/org/axonframework/disruptor/commandhandling/DisruptorCommandBusTest.java

fixed so DisruptorCommandBus returns the command value

---

modelling/src/main/java/org/axonframework/modelling/saga/AbstractSagaManager.java
modelling/src/test/java/org/axonframework/modelling/saga/SagaManagerTest.java

Fix duplicate saga creation after segment split

---

config/pom.xml
eventsourcing/pom.xml
messaging/pom.xml
metrics-micrometer/pom.xml
metrics/pom.xml
modelling/pom.xml
pom.xml
spring-boot-starter/pom.xml
test/pom.xml

Fix warning during `mvn install`: Unused Import-Package instructions: [org.slf4j.*]
Also updated some dependencies.

Fix warning: Unused Import-Package instructions: [org.slf4j.*]

---

config/src/main/java/org/axonframework/config/EventProcessingModule.java
config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java

[#940] Fixes NullPointerException for tracking group package name fallback 

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/EventBuffer.java
messaging/src/main/java/org/axonframework/eventhandling/SimpleEventHandlerInvoker.java
messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
modelling/src/main/java/org/axonframework/modelling/saga/AbstractSagaManager.java

Added logging of event path through the Axon Framework.

Increased logging of event processing

---

messaging/src/main/java/org/axonframework/common/lock/PessimisticLockFactory.java
messaging/src/test/java/org/axonframework/common/lock/PessimisticLockFactoryTest.java

This pull request resolve #1224.
@smcvb the pull request to axon-4.2.x branch
Thanks

Assert that identifier is not null in PessimisticLockFactory

---

pom.xml
spring-boot-starter/pom.xml

Update Dependencies + Plugins.

Update Dependencies + Plugins

---

config/src/main/java/org/axonframework/config/AggregateConfigurer.java
disruptor/src/test/java/org/axonframework/disruptor/commandhandling/CommandHandlerInvokerTest.java
disruptor/src/test/java/org/axonframework/disruptor/commandhandling/DisruptorCommandBusTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/deadline/AbstractDeadlineManagerTestSuite.java
messaging/src/main/java/org/axonframework/deadline/GenericDeadlineMessage.java
messaging/src/main/java/org/axonframework/deadline/SimpleDeadlineManager.java
messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java
messaging/src/test/java/org/axonframework/deadline/quartz/DeadlineJobDataBinderTest.java
modelling/src/test/java/org/axonframework/modelling/command/AbstractRepositoryTest.java
test/src/main/java/org/axonframework/test/deadline/StubDeadlineManager.java
test/src/test/java/org/axonframework/test/aggregate/AggregateDeadlineSchedulingTest.java
test/src/test/java/org/axonframework/test/saga/SagaDeadlineSchedulingTest.java

A couple of improvements to the deadline manager.

Deadline manager improvements

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/DefaultHandlers.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/DefaultInstructionAckSource.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ErrorCode.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/Handlers.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/InstructionAckSource.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConnectionManagerTest.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/TestStreamObserver.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
pom.xml

This PR introduces changes that support reporting whether certain instruction in bidi streams was handled successfully or not. It also adds the possibility to report unsupported instructions.

Confirmation in bidi streams

---

metrics-micrometer/src/test/java/org/axonframework/micrometer/CapacityMonitorTest.java
metrics-micrometer/src/test/java/org/axonframework/micrometer/EventProcessorLatencyMonitorTest.java
metrics-micrometer/src/test/java/org/axonframework/micrometer/GlobalMetricRegistryTest.java
metrics-micrometer/src/test/java/org/axonframework/micrometer/MessageCountingMonitorTest.java
metrics-micrometer/src/test/java/org/axonframework/micrometer/MessageTimerMonitorTest.java
metrics-micrometer/src/test/java/org/axonframework/micrometer/MetricsConfigurerModuleTest.java
metrics-micrometer/src/test/java/org/axonframework/micrometer/PayloadTypeMessageMonitorWrapperTest.java
metrics-micrometer/src/test/java/org/axonframework/micrometer/reservoir/SlidingTimeWindowReservoirTest.java
metrics/src/test/java/org/axonframework/metrics/CapacityMonitorTest.java
metrics/src/test/java/org/axonframework/metrics/EventProcessorLatencyMonitorTest.java
metrics/src/test/java/org/axonframework/metrics/GlobalMetricRegistryTest.java
metrics/src/test/java/org/axonframework/metrics/MessageCountingMonitorTest.java
metrics/src/test/java/org/axonframework/metrics/MessageTimerMonitorTest.java
metrics/src/test/java/org/axonframework/metrics/MetricsConfigurerModuleTest.java
metrics/src/test/java/org/axonframework/metrics/PayloadTypeMessageMonitorWrapperTest.java
pom.xml

Adding dependencies + migration of modules axon-micrometer, axon-metrics to JUnit5.

Update axon-micrometer and axon-metrics modules to use JUnit5

---

integrationtests/src/test/java/org/axonframework/integrationtests/deadline/AbstractDeadlineManagerTestSuite.java
messaging/src/main/java/org/axonframework/deadline/DeadlineManager.java
messaging/src/main/java/org/axonframework/deadline/SimpleDeadlineManager.java
messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java
test/src/main/java/org/axonframework/test/deadline/StubDeadlineManager.java

Resolves #1235 
_Note to the reviewers_: pay special attention to quartz implementation since it has a performance impact.

Added possibility to cancel all deadlines within a scope.

---

messaging/src/main/java/org/axonframework/common/caching/WeakReferenceCache.java
messaging/src/test/java/org/axonframework/common/caching/WeakReferenceCacheTest.java

This pull request resolve https://github.com/AxonFramework/AxonFramework/issues/1289
Thanks

Assert that key is not null in WeakReferenceCache

---

integrationtests/pom.xml
integrationtests/src/test/java/org/axonframework/integrationtests/commandhandling/CommandRetryAndDispatchInterceptorIntegrationTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/commandhandling/EventPublicationOrderTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/deadline/AbstractDeadlineManagerTestSuite.java
integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/SubscribingEventProcessorTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest_MultiThreaded.java
integrationtests/src/test/java/org/axonframework/integrationtests/eventsourcing/NestedUnitOfWorkTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/eventsourcing/conflictresolution/ConflictResolutionIntegrationTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/eventsourcing/eventstore/benchmark/JpaStorageEngineInsertionReadOrderTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/eventsourcing/eventstore/jdbc/Oracle11EventTableFactoryTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/loopbacktest/NestedUowRollbackTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/loopbacktest/synchronous/LoopBackWithInterweavedCommandsAndEventsTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/loopbacktest/synchronous/SynchronousLoopbackTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/modelling/command/CommandHandlerInterceptorTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/modelling/command/CommandHandlingTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/modelling/command/ComplexAggregateStructureTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/modelling/command/GenericJpaRepositoryIntegrationTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/modelling/saga/repository/jdbc/Oracle11SagaSqlSchemaTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/queryhandling/QueryEventHandlingTest.java

Migrate module "integrationtests" to JUnit5

Migrate module "integrationtests" to JUnit5

---

messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
messaging/src/test/java/org/axonframework/queryhandling/FutureAsResponseTypeToQueryHandlersTest.java

Convert a query result of Future to a QueryResponse (if necessary).

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/EventBuffer.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/EventBufferTest.java
eventsourcing/src/main/java/org/axonframework/eventsourcing/MultiStreamableMessageSource.java
eventsourcing/src/test/java/org/axonframework/eventsourcing/MultiStreamableMessageSourceTest.java

Improvements to deal with exceptions in underlying event streams.
@smcvb , added it to master for inclusion in 4.3. If you prefer it to be included in a 4.2.2, let me know.

Improved exception handling in MultiStreamableMessageSource

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/QueryResultBuffer.java
disruptor/src/main/java/org/axonframework/disruptor/commandhandling/EventPublisher.java
eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java
messaging/src/main/java/org/axonframework/common/property/AbstractMethodPropertyAccessStrategy.java
spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/util/AbstractQualifiedBeanCondition.java

There were a couple of wrong class names in use on our loggers.
I've adjusted those values.
This PR resolves #1359 .

[1359] Adjusted logger values to use the correct class name

---

.travis.yml
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/EventStoreImpl.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/StubServer.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java
pom.xml

Related to: https://github.com/AxonIQ/axon-server-api/pull/20

Added possibility to use event store of node currently connected to.

---

eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStoreTest.java
messaging/src/main/java/org/axonframework/eventhandling/AbstractEventBus.java

Events are staged in a Unit of Work when they are published. However, when a Unit of Work is nested, committing a UoW, will stage the events in a parent UoW. When reading staged events during a commit, it is possible that staged events have already been promoted to the parent UoW and are then being read, causing duplicates.
This commit prevents the occurrence of duplicates when reading staged events from a Unit of Work.
Resolved issue #1408

Ensure no duplicate events are visible when reading staged events

---

messaging/src/main/java/org/axonframework/commandhandling/CommandHandler.java

I was browsing through the source code and came across this minor typo and wanted to bring it to your attention. :)

Fix minor typo

---

integrationtests/pom.xml
integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
pom.xml

Fix issue https://github.com/AxonFramework/AxonFramework/issues/1451, that happens when we try to merge two segments in the inverted order.

[#1451] Fix for merge segments in inverted order

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java

This prevents situations where calls fail after a connection was closed by AxonServer because the JVM was unresponsive for a certain period of time. This could be caused by a stop-the-world GC and has also been observed in the case of JVM based Function (e.g. Lambdas) where a JVM is paused to prevent it from consuming resources when inactive.
These changes will attempt to recover a connection before abandoning it as lost.

Prevent connections from being shut down if they can be recovered

---

eventsourcing/src/main/java/org/axonframework/eventsourcing/AbstractSnapshotter.java
eventsourcing/src/test/java/org/axonframework/eventsourcing/AbstractSnapshotterTest.java

This prevents creation of snapshots before all events included in the snapshot have been committed to the underlying store.

Postpone snapshot creation to the afterCommit phase

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java

Missing properties:
max-message-size
gRPC keepalive settings
processorNotificationRate

Forward properties from AxonServerConfiguration to AxonServerConnectionFactory

---

config/src/main/java/org/axonframework/config/EventProcessingModule.java
config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java

Event Handler instances would not be assigned to the correct processing group when using type-level rules.

Fix for assignment rules by type that were ignored

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/GrpcBackedResponseMessage.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/GrpcBackedQueryUpdateMessage.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/GrpcBackedResponseMessageTest.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/subscription/GrpcBackedQueryUpdateMessageTest.java
messaging/src/main/java/org/axonframework/messaging/responsetypes/ConvertingResponseMessage.java
messaging/src/main/java/org/axonframework/queryhandling/GenericSubscriptionQueryUpdateMessage.java
messaging/src/test/java/org/axonframework/messaging/responsetypes/ConvertingResponseMessageTest.java

[#1477] ResultMessage illegal payload access alignment 

---

messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/GenericTokenTableFactory.java
messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/Oracle11TokenTableFactory.java
messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/PostgresTokenTableFactory.java
messaging/src/test/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStoreTest.java

[#1460] Added INSTANCE field to TokenTableFactory implementations

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
config/src/main/java/org/axonframework/config/DefaultConfigurer.java
messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedMessageHandlingMember.java
messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedMessageHandlingMemberDefinition.java
test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java

Changed some log messages to provide better information about the context of the log statement and removed unnecessary exception unwrapping.
The log level for logging about snapshot creation has been changed to debug and now includes the type and identifier of the aggregate for which a snapshot was created.

Improved logging and minor code style fixes

---

eventsourcing/src/main/java/org/axonframework/eventsourcing/EventSourcingRepository.java

#1439 When loading the aggregrate prepare the Snapshot trigger first

---

messaging/src/main/java/org/axonframework/serialization/AbstractXStreamSerializer.java
messaging/src/main/java/org/axonframework/serialization/json/JacksonSerializer.java
messaging/src/main/java/org/axonframework/serialization/xml/XStreamSerializer.java
spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java

#1613 Added ability to set ClassLoader on XStreamSerializer builder

---

disruptor/src/main/java/org/axonframework/disruptor/commandhandling/CommandHandlerInvoker.java
modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java
modelling/src/test/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandlerTest.java

Adds aggregate to the cache after commit (Distruptor Command Bus)
Fixes https://github.com/AxonFramework/AxonFramework/issues/1778

[#1778] Fixes issue that event is not applied when using create if missing

---

disruptor/src/main/java/org/axonframework/disruptor/commandhandling/CommandHandlerInvoker.java

Remove onCommit hook as an additional fix on top of pull request #1792 for issue #1778.

[#1778] Remove onCommit hook

---

messaging/src/main/java/org/axonframework/eventhandling/async/PropertySequencingPolicy.java
messaging/src/test/java/org/axonframework/eventhandling/async/PropertySequencingPolicyTest.java

This is a pull request for issue #1827.
Signed-off-by: Nils Christian Ehmke <nils@rhocas.de>

[#1827] New SequencingPolicy: PropertySequencingPolicy

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java

When shutting down the Axon components through the configuration, the AxonServerQueryBus caused a timeout in one of the shutdown stages. While this didn't prevent the shutdown sequence from continuing, it did add unnecessary delay.
This PR addresses that, be ensuring that the termination of queries is properly registered, both for point-to-point and scatter-gather queries. Long running queries, such as subscription queries don't prevent a shutdown. They are simply cancelled ones the shutdown sequence is initiated.

Fix timeout when shutting down AxonServerQueryBus

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerRemoteCommandHandlingException.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerRemoteQueryHandlingException.java
messaging/src/main/java/org/axonframework/commandhandling/CommandExecutionException.java
messaging/src/main/java/org/axonframework/common/AxonException.java
messaging/src/main/java/org/axonframework/messaging/HandlerExecutionException.java
messaging/src/main/java/org/axonframework/messaging/RemoteHandlingException.java
messaging/src/main/java/org/axonframework/queryhandling/QueryExecutionException.java
messaging/src/test/java/org/axonframework/messaging/HandlerExecutionExceptionTest.java

PR proposal for https://github.com/AxonFramework/AxonFramework/issues/1901

Prevent stack trace generation for HandlerExecutionException

---

messaging/src/main/java/org/axonframework/eventhandling/async/MetaDataSequencingPolicy.java
messaging/src/test/java/org/axonframework/eventhandling/async/MetaDataSequencingPolicyTest.java

Added the MetaDataSequencingPolicy

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConnectionManagerTest.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/PlatformService.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/StubServer.java

This PR ensures that setting for heartbeat is used to validate all connections to Axon Server, not only the connection used by the main context.

Ensure heartbeat is enabled on all connections

---

.github/workflows/maven.yml

Added java 17 to the build and some extra improvements to the build file.
It might be hard to merge it to master later on since our master build files are different from this branch but we can work out on master when needed.
---
from logs:
> Java configuration:
Distribution: zulu
Version: 17.0.0+35
Path: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.0-35/x64

Added java 17 to the main build

---

eventsourcing/src/main/java/org/axonframework/eventsourcing/CachingEventSourcingRepository.java
eventsourcing/src/test/java/org/axonframework/eventsourcing/CachingEventSourcingRepositoryTest.java

The cache was not invalidated in all cases, which made it possible that subsequent commands would hit a wrong instance of an aggregate. Typically, the failure of these commands would in turn invalidate the entry.
This commit ensures that all points where cached entries could be in use properly register an onRollback handler to invalidate the cached entry.

Ensure cached aggregates are invalidated on failures

---

messaging/src/main/java/org/axonframework/commandhandling/gateway/AbstractRetryScheduler.java
messaging/src/main/java/org/axonframework/commandhandling/gateway/AxonNonTransientExceptionClassesPredicate.java
messaging/src/main/java/org/axonframework/commandhandling/gateway/ExponentialBackOffIntervalRetryScheduler.java
messaging/src/main/java/org/axonframework/commandhandling/gateway/IntervalRetryScheduler.java
messaging/src/main/java/org/axonframework/commandhandling/gateway/NonTransientExceptionClassesPredicate.java
messaging/src/test/java/org/axonframework/commandhandling/gateway/AbstractRetrySchedulerTest.java

For reference this commit is missing from master branch:
https://github.com/AxonFramework/AxonFramework/commit/6e531a6cf173243adf9519905f42cbec0a334238

Restore missing commit 6e531a6cf173243adf9519905f42cbec0a334238

---

test/src/main/java/org/axonframework/test/aggregate/Reporter.java
test/src/main/java/org/axonframework/test/aggregate/ResultValidator.java
test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java
test/src/test/java/org/axonframework/test/aggregate/FixtureTest_ExceptionHandling.java

`AggregateTestFixture` improvement - Validate Exception Details

---

messaging/src/main/java/org/axonframework/messaging/responsetypes/InstanceResponseType.java
messaging/src/main/java/org/axonframework/messaging/responsetypes/MultipleInstancesResponseType.java
messaging/src/main/java/org/axonframework/messaging/responsetypes/OptionalResponseType.java
messaging/src/main/java/org/axonframework/messaging/responsetypes/ResponseType.java
messaging/src/main/java/org/axonframework/messaging/responsetypes/ResponseTypes.java
messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
messaging/src/test/java/org/axonframework/messaging/responsetypes/AbstractResponseTypeTest.java
messaging/src/test/java/org/axonframework/messaging/responsetypes/InstanceResponseTypeTest.java
messaging/src/test/java/org/axonframework/messaging/responsetypes/MultipleInstancesResponseTypeTest.java
messaging/src/test/java/org/axonframework/messaging/responsetypes/OptionalResponseTypeTest.java
messaging/src/test/java/org/axonframework/queryhandling/SimpleQueryBusTest.java

This pull request resolves #602.

MultipleInstancesResponseType should match (lower) on single item

---

messaging/src/main/java/org/axonframework/commandhandling/CommandCallback.java
messaging/src/main/java/org/axonframework/commandhandling/WrappedCommandCallback.java
messaging/src/main/java/org/axonframework/commandhandling/callbacks/FailureLoggingCallback.java
messaging/src/main/java/org/axonframework/commandhandling/gateway/DefaultCommandGateway.java
messaging/src/test/java/org/axonframework/commandhandling/WrappedCommandCallbackTest.java
messaging/src/test/java/org/axonframework/commandhandling/gateway/DefaultCommandGatewayTest.java

This pull request resolves #1889

Add method on DefaultCommandGateway to be able to customize callbacks

---

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java

fix typo in local variable name

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java

Snapshots are not read with snapshot filter and same serializer for events and snapshots

---

config/src/main/java/org/axonframework/config/DefaultConfigurer.java

Signed-off-by: Nils Christian Ehmke <nils-christian.ehmke@bmiag.de>
This pull request resolves #2289.

[#2289] Incorrect warning message in case of shutdown timeout

---

pom.xml

Since there were some incompatible updates, I ran `mvn versions:display-dependency-updates` locally, and updated some things, to have it run again + get quick feedback on the incompatible ones, due to not being Java 8 compatible.

Updated some dependencies

---

modelling/src/main/java/org/axonframework/modelling/command/AbstractRepository.java

Take all types into account when resolving the deadline handler

---

messaging/src/main/java/org/axonframework/eventhandling/deadletter/DeadLetteredEventProcessingTask.java
messaging/src/main/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventHandlerInvoker.java
messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/JpaSequencedDeadLetterQueue.java
messaging/src/main/java/org/axonframework/messaging/deadletter/InMemorySequencedDeadLetterQueue.java

[#2396] Deadletter logging changes

---

test/src/main/java/org/axonframework/test/matchers/ExactClassMatcher.java
test/src/main/java/org/axonframework/test/matchers/Matchers.java
test/src/test/java/org/axonframework/test/matchers/ExactClassMatcherTest.java

Fixes https://github.com/AxonFramework/AxonFramework/issues/2444

[#2444] Exact class type matcher

---

messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java

Resolves https://github.com/AxonFramework/AxonFramework/issues/2451.
I validated the fix with a test project, as the only way to test this is with unclean (kill -9) shutdown, I didn't include any tests.
I don't see any downsides, besides under very special circumstances, like a problem with the database the deadlines are stored in, the deadline might trigger twice. Since typically a command is fired in such a case, I think that's better than doing nothing, where multiple sagas easily got stuck forever in case of a hard shutdown.

Fixes recovering quartz jobs in case of sudden shutdown

---

README.md

This pull request aims to update the `README.md` to better help users of Axon Framework and other Axon products.
It does so by expanding on the introduction, getting started, receiving help, and feature-request/bug sections. 
Next to this, links are included when applicable.
Lastly, typos are resolved to my best-effort.

Update the `README.md` to guide users better

---

pom.xml

Upgrade axonserver-connector-java version to 4.6.3.

Upgrade axonserver-connector-java version to 4.6.3

---

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JdbcAutoConfiguration.java
spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JdbcAutoConfigurationTest.java

2nd PR which is related to #2581
@smcvb

#2581 Do not duplicate bean definition of TokenStore

---

integrationtests/pom.xml
spring-boot-3-integrationtests/pom.xml
spring/src/test/java/org/axonframework/integrationtests/deadline/AbstractDeadlineManagerTestSuite.java

Move `AbstractDeadlineManagerTestSuite` to spring module so it's deployed.

Move AbstractDeadlineManagerTestSuite to spring module so it's deployed.

---

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java
spring/src/main/java/org/axonframework/spring/config/ApplicationContextLookupParameterResolverFactory.java
spring/src/main/java/org/axonframework/spring/config/CommandHandlerSubscriber.java
spring/src/main/java/org/axonframework/spring/config/annotation/SpringHandlerDefinitionBean.java
spring/src/main/java/org/axonframework/spring/config/annotation/SpringHandlerEnhancerDefinitionBean.java
spring/src/main/java/org/axonframework/spring/eventsourcing/SpringAggregateSnapshotter.java
spring/src/main/java/org/axonframework/spring/eventsourcing/SpringAggregateSnapshotterFactoryBean.java

[#2628] Extended support for Spring application context hierarchy

---

spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationTest.java
spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/SagaCustomizeIntegrationTest.java
spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest_CustomEventHandlerConfiguration.java

Removes unnecessary annotations from tests. #2594

refactor: Spring Boot 2.x best practices

---

config/src/main/java/org/axonframework/config/EventProcessingModule.java

Preventing already initializing the processors.

Make `registerHandlerInterceptor` lazy

---

integrationtests/src/test/java/org/axonframework/integrationtests/cache/JCacheIntegrationTest.java
integrationtests/src/test/resources/log4j2.properties
messaging/src/test/java/org/axonframework/common/caching/AbstractCacheAdapterTest.java
messaging/src/test/java/org/axonframework/common/caching/EhCache3AdapterTest.java
messaging/src/test/java/org/axonframework/common/caching/JCacheAdapterTest.java

Fixes https://github.com/AxonFramework/AxonFramework/issues/2421, builds onto the pr https://github.com/AxonFramework/AxonFramework/pull/2709, so ideally that one is merged first. This is only about the last commit, https://github.com/AxonFramework/AxonFramework/commit/ef598b3e30fa39acef0e921519c9c47f056afb98.

Add JCacheAdapter test scenarios

---

eventsourcing/pom.xml
eventsourcing/src/test/java/org/axonframework/eventsourcing/CachingEventSourcingRepositoryTest.java
eventsourcing/src/test/java/org/axonframework/eventsourcing/CachingRepositoryWithNestedUnitOfWorkTest.java
integrationtests/pom.xml
integrationtests/src/test/java/org/axonframework/integrationtests/cache/EhCache3IntegrationTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/cache/EhCacheIntegrationTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/cache/JCacheIntegrationTest.java
integrationtests/src/test/resources/log4j2.properties
messaging/pom.xml
messaging/src/main/java/org/axonframework/common/caching/EhCache3Adapter.java
messaging/src/main/java/org/axonframework/common/caching/EhCacheAdapter.java
messaging/src/test/java/org/axonframework/common/caching/AbstractCacheAdapterTest.java
messaging/src/test/java/org/axonframework/common/caching/EhCache3AdapterTest.java
messaging/src/test/java/org/axonframework/common/caching/EhCacheAdapterTest.java
messaging/src/test/java/org/axonframework/common/caching/JCacheAdapterTest.java
modelling/pom.xml
modelling/src/test/java/org/axonframework/modelling/saga/repository/EhCache3SagaStoreTest.java
modelling/src/test/java/org/axonframework/modelling/saga/repository/EhCachingSagaStoreTest.java
modelling/src/test/resources/log4j2.properties
pom.xml

Fixes https://github.com/AxonFramework/AxonFramework/issues/2420. It's more or less a complete rewrite. It even lives in another repository. Since it will become unmaintained from this September ([source](https://github.com/ehcache/ehcache2)). it will be nice to switch.
I was a bit unsure about the `CacheEventListenerAdapter`. Tests were added and the implementation changed using the documentation, to remove the doubts.

Add cache using EhCache 3

---

messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/JpaSequencedDeadLetterQueue.java
messaging/src/main/java/org/axonframework/eventhandling/deadletter/legacyjpa/JpaSequencedDeadLetterQueue.java
messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/GenericTokenTableFactory.java
messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStore.java
messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/Oracle11TokenTableFactory.java

I found some small typos. These have been resolved in this PR.

Fix some typos

---

pom.xml

Upgrade `axonserver-connector-java` to version 2023.1.0.

Upgrade axonserver-connector-java to 2023.1.0

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventScheduler.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventSchedulerTest.java

Add ability to set context to a event scheduler. 
Required for Multi Tenant version of Event Scheduler.

Improve Event Scheduler context configuration

---

config/src/main/java/org/axonframework/config/DefaultConfigurer.java
integrationtests/src/test/java/org/axonframework/integrationtests/deadline/SimpleDeadlineManagerTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/deadline/dbscheduler/BinaryDbSchedulerDeadlineManagerTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/deadline/dbscheduler/HumanReadableDbSchedulerDeadlineManagerTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/deadline/jobrunr/JobrunrDeadlineManagerTest.java
integrationtests/src/test/java/org/axonframework/integrationtests/deadline/quartz/QuartzDeadlineManagerTest.java
messaging/src/main/java/org/axonframework/deadline/DeadlineManagerSpanFactory.java
messaging/src/main/java/org/axonframework/deadline/DefaultDeadlineManagerSpanFactory.java
messaging/src/main/java/org/axonframework/deadline/SimpleDeadlineManager.java
messaging/src/main/java/org/axonframework/deadline/dbscheduler/DbSchedulerDeadlineManager.java
messaging/src/main/java/org/axonframework/deadline/jobrunr/JobRunrDeadlineManager.java
messaging/src/main/java/org/axonframework/deadline/quartz/DeadlineJob.java
messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java
messaging/src/main/java/org/axonframework/tracing/HandlerSpanFactory.java
messaging/src/main/java/org/axonframework/tracing/NoOpSpanFactory.java
messaging/src/test/java/org/axonframework/commandhandling/DefaultCommandBusSpanFactoryTest.java
messaging/src/test/java/org/axonframework/deadline/DefaultDeadlineManagerSpanFactoryTest.java
messaging/src/test/java/org/axonframework/eventhandling/DefaultEventBusSpanFactoryTest.java
messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryBusSpanFactoryTest.java
messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryUpdateEmitterSpanFactoryTest.java
messaging/src/test/java/org/axonframework/tracing/TestSpanFactory.java
spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/TracingProperties.java
spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonDbSchedulerAutoConfiguration.java
spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonJobRunrAutoConfiguration.java
spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonTracingAutoConfiguration.java
spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithTracingTest.java
spring/src/test/java/org/axonframework/integrationtests/deadline/AbstractDeadlineManagerTestSuite.java

Updates the following interfaces and adds intermediate span factories for all their implementations:
- DeadlineManager
This PR currently targets the #2826 branch until it is merged to better reflect the individual changes. Once merged, this PR will target main.

Add intermediate span factories for DeadlineManager

---

messaging/src/main/java/org/axonframework/deadline/dbscheduler/DbSchedulerDeadlineManager.java
spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonDbSchedulerAutoConfiguration.java

Fixes https://github.com/AxonFramework/AxonFramework/issues/2844

[#2844] Improve shutdown behavior for `DbSchedulerDeadlineManager`

---

config/src/main/java/org/axonframework/config/AxonIQConsoleModule.java
config/src/main/java/org/axonframework/config/DefaultConfigurer.java
config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
config/src/test/resources/log4j2.properties
hibernate-6-integrationtests/src/test/resources/log4j2.properties
integrationtests/src/test/resources/log4j2.properties
spring-boot-3-integrationtests/src/test/resources/log4j2.properties
spring-boot-autoconfigure/src/test/resources/log4j2.properties

Fixes https://github.com/AxonFramework/AxonFramework/issues/2819.
There are no tests, as it's just logging. I don't think it's worth the hassle.

Add suppressible log message when console client is not on the classpath.

---

messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java
messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java

This pull request adjusts the logging in the `PooledStreamingEventProcessor` and its `Coordinator`, specifically around claiming segments. 
Doing so enables easier investigation when segment claims/steals occur.

Enhance segment logging for `PooledStreamingEventProcessor`

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerBusAutoConfiguration.java

[#3149] Allow queries with a local handler to shortcut to the local segment

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamConnection.java
axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamConnectionTest.java

Retry events with exponential backoff when event handling fails.

Add retry on error behavior to persistent streams

---

eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SimpleEventStoreTest.java

Tests added according to https://github.com/AxonFramework/AxonFramework/pull/3216#discussion_r1898541153

Add `SimpleEventStoreTest`

---

.github/workflows/add-to-project.yml
.github/workflows/main.yml
.github/workflows/pullrequest.yml

Corresponding PR as those below for Axon Framework 4:
- https://github.com/AxonFramework/AxonFramework/pull/3236
- https://github.com/AxonFramework/AxonFramework/pull/3237

ci: GitHub Actions (AF4) - rerun flaky tests

---

eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransaction.java
eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/AsyncInMemoryEventStorageEngine.java
eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransactionTest.java
eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/StorageEngineTestSuite.java

Tests added according to https://github.com/AxonFramework/AxonFramework/pull/3216#discussion_r1898541153

Add `DefaultEventStoreTransactionTest`

---

pom.xml

[#3181] deps: upgrade XStream to 1.4.21 to resolve CVE-2024-47072

---

eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransaction.java
eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/SimpleEventStore.java
eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransactionTest.java
eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SimpleEventStoreTest.java

Described by @smcvb here:
https://axoniq.slack.com/archives/C9KREBXK6/p1736956514395869

`TagResolver` - use in `DefaultEventStoreTransaction`

---

docs/old-reference-guide/modules/axon-framework-commands/pages/modeling/aggregate.adoc

Add explanation about aggregate identifiers and uniqueness

---

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
config/src/main/java/org/axonframework/config/EventProcessingConfigurer.java
config/src/main/java/org/axonframework/config/EventProcessingModule.java
config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java
docs/old-reference-guide/modules/events/pages/event-processors/subscribing.adoc
docs/old-reference-guide/modules/messaging-concepts/pages/index.adoc
docs/old-reference-guide/modules/queries/pages/implementations.adoc
spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfigurationTest.java

[#3170] Persistent streams - auto configuration

---

docs/old-reference-guide/modules/monitoring/pages/message-tracking.adoc

This quickly fixes the Correlation data table in the documentation.

fix Correlation data table

---

README.md

This pull request adds an "Update Checker and Anonymous Usage Data Collection" section to the `README.md` for added transparency.

Add Update Checker mention to the `README.md`

---

eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/HsqldbTestContainer.java
eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngineTest.java

[#3623] Add HSQLDB container and use it in JDBCEventStorageEngineTest

---

eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventStorageEngine.java

Mark `EventStorageEngine` as internal

---

docs/af5-getting-started/modules/ROOT/nav.adoc
docs/af5-getting-started/modules/ROOT/pages/implement-read-model.adoc

[#3659] docs: Axon Framework 5.0.0-M3 - Expand Getting Started with Read Model example
