core/src/main/java/org/axonframework/commandhandling/annotation/AggregateCommandHandlerInspector.java, core/src/main/java/org/axonframework/commandhandling/annotation/CommandHandlingMemberMap.java, core/src/test/java/org/axonframework/commandhandling/annotation/AggregateAnnotationCommandHandlerTest.java
Added an annotation to mark fields with a map of entities capable of
handling commands. The annotation specifies which field in the command
to use as a key to look up the appropriate entity in the map.
=> Added support for @CommandHandler on map of entities

core/src/main/java/org/axonframework/domain/MetaData.java
Enhance exception message in case of unsupported metadata mutation.
Really the metadata can be used in any message, however the unsupported exception message (confusingly) reported event metadata.
=> Enhance exception message in case of unsupported metadata mutation.

distributed-commandbus/src/main/java/org/axonframework/commandhandling/distributed/jgroups/HashChangeListener.java, distributed-commandbus/src/main/java/org/axonframework/commandhandling/distributed/jgroups/JChannelFactory.java, distributed-commandbus/src/main/java/org/axonframework/commandhandling/distributed/jgroups/JGroupsConnector.java, distributed-commandbus/src/main/java/org/axonframework/commandhandling/distributed/jgroups/JGroupsConnectorFactoryBean.java, distributed-commandbus/src/main/java/org/axonframework/commandhandling/distributed/jgroups/JGroupsXmlConfigurationChannelFactory.java, distributed-commandbus/src/test/java/org/axonframework/commandhandling/distributed/jgroups/JGroupsConnectorFactoryBeanTest.java, distributed-commandbus/src/test/java/org/axonframework/commandhandling/distributed/jgroups/JGroupsConnectorTest.java, documentation/src/main/docbook/en-US/reference-guide/3-command-handling.xml
- Optionally register JChannel MBean after connecting
- Delegate creation of JChannel to Factory to allow alternative (programmatic) instantiation of the JChannel, e.g. to apply configuration settings from spring placeholder properties.
=> Jgroups configuration enhancements

core/src/main/java/org/axonframework/eventstore/jdbc/JdbcEventStore.java, pom.xml
I made a correction to the javadoc for JdbcEventStore, removing the reference to JPA in the class javadoc. I had removed something from the pom.xml as well (for my own purposes) but forgot and left that in for my previous pull request.
=> Simple Javadoc correction to JdbcEventStore

core/src/main/java/org/axonframework/common/annotation/MethodMessageHandlerInspector.java
If test-cases wishes to run multiple axon instances (Sequentially, within the same JVM) but with different spring context configurations, the cache inside axon will hold on to earlier definitions. 
This patch adds a clear method to the cache so we can stop using reflection and setVisible
=> Added clear method to facilitate clearing of cache for tests

test/src/main/java/org/axonframework/test/GivenWhenThenTestFixture.java, test/src/test/java/org/axonframework/test/FixtureTest_ExceptionHandling.java
The test case is overly verbose considering the small fix. I wrote the test before fully investigating the cause. Please feel free to abbreviate the test case.
Please also merge into 'master'.
=> AXON-345: Fixed GivenWhenThenTestFixture "givenCommands" exception handling

core/src/main/java/org/axonframework/saga/AbstractSagaManager.java, core/src/test/java/org/axonframework/saga/SagaManagerTest.java
AXON-349: SagaManager reliability improvements
- Always fail replay when SagaManager is in cluster.
- SagaManager will always used the first tracked Saga for cluster selection purposes.
=> AXON-349: SagaManager reliability improvements

core/src/main/java/org/axonframework/eventsourcing/AbstractEventSourcedEntity.java, core/src/main/java/org/axonframework/eventsourcing/EventSourcedEntity.java
Changed getAggregateRoot in AbstractEventSourcedEntity to a generic return type. This way there's no need to explicitly cast to your aggregate root.
=> Generic return type getAggregateRoot in AbstractEventSourcedEntity

test/src/main/java/org/axonframework/test/saga/AnnotatedSagaTestFixture.java, test/src/test/java/org/axonframework/test/saga/AnnotatedSagaTest.java, test/src/test/java/org/axonframework/test/saga/StubSaga.java, test/src/test/java/org/axonframework/test/saga/TriggerExistingSagaEvent.java
This allows Sagas that use EventTemplate rather than EventBus to be tested using the test fixture's fluent API rather than by mocking an EventTemplate instance in the test code.
=> Add EventTemplate to the built-in resources in AnnotateSagaTestFixture

quickstart/src/main/java/org/axonframework/quickstart/annotated/ToDoEventHandler.java, spring/src/test/java/org/axonframework/spring/config/annotation/AnnotationEventListenerBeanPostProcessorTest.java, spring/src/test/java/org/axonframework/spring/config/annotation/AnnotationEventListenerBeanPostProcessorTest_DoubleAnnotated.java, spring/src/test/java/org/axonframework/spring/config/annotation/SpringBeanParameterResolverFactoryTest.java, spring/src/test/java/org/axonframework/spring/config/xml/AnnotationConfigurationBeanDefinitionParserTest.java, test/src/main/java/org/axonframework/test/eventscheduler/EventConsumer.java, test/src/main/java/org/axonframework/test/eventscheduler/StubEventScheduler.java, test/src/main/java/org/axonframework/test/saga/AnnotatedSagaTestFixture.java, test/src/main/java/org/axonframework/test/saga/ContinuedGivenState.java, test/src/main/java/org/axonframework/test/saga/FixtureConfiguration.java, test/src/main/java/org/axonframework/test/saga/GivenAggregateEventPublisher.java, test/src/main/java/org/axonframework/test/saga/WhenAggregateEventPublisher.java, test/src/main/java/org/axonframework/test/saga/WhenState.java, test/src/test/java/org/axonframework/test/MyCommandHandler.java, test/src/test/java/org/axonframework/test/saga/AnnotatedSagaTest.java, test/src/test/java/org/axonframework/test/saga/FixtureExecutionResultImplTest.java
A commit that added a throws clause to MessageHandler broke some of the testing fixures. throws clauses have been added where needed.
Date formatting was failing because the pattern wasn't specifying a timezone.
=> Updates to get quickstart working

mongo/src/main/java/org/axonframework/serialization/bson/DBObjectHierarchicalStreamReader.java, mongo/src/main/java/org/axonframework/serialization/bson/DBObjectHierarchicalStreamWriter.java
This pull request is focused on resolving occurrences of Sonar rule
squid:S1149 - Synchronized classes Vector, Hashtable, Stack and StringBuffer should not be used.
This pull request removes 60 minutes of technical debt.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1149
Please let me know if you have any questions.
George Kankava
=> squid:S1149 - Synchronized classes Vector, Hashtable, Stack and StringBuffer should not be used

core/src/main/java/org/axonframework/common/annotation/ClasspathParameterResolverFactory.java, core/src/main/java/org/axonframework/common/jdbc/JdbcUtils.java
This pull request is focused on resolving occurrences of Sonar rule
squid:S1118 - Utility classes should not have public constructors.
This pull request removes 60 minutes of technical debt.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Please let me know if you have any questions.
George Kankava
=> squid:S1118 - Utility classes should not have public constructors

core/src/main/java/org/axonframework/saga/AbstractSagaManager.java, core/src/test/java/org/axonframework/saga/SagaManagerTest.java
Hi,
I found a bug in AbstractSagaManager. It doesn't clear its internal map "sagasInCreation" when Unit of Work is rollbacked.
When saga threw an exception while being created, it was still handled events in another units of work, but it shouldn't.
I think this bug doesn't appear in Axon 3.0, but let me know if I'm wrong.
Maciek
=> Saga should not survive it's creation if it threw exception while being created

core/src/main/java/org/axonframework/commandhandling/gateway/CommandGateway.java, core/src/main/java/org/axonframework/commandhandling/gateway/DefaultCommandGateway.java, core/src/test/java/org/axonframework/commandhandling/gateway/DefaultCommandGatewayTest.java
Convert CommandGateway#send from a void return to a CompletableFuture, in order to allow resolving callbacks in a different location than CommandGateway#send is called
=> Return CompletableFuture from CommandGateway#send

core/src/main/java/org/axonframework/messaging/annotation/SimpleResourceParameterResolverFactory.java, core/src/test/java/org/axonframework/messaging/annotation/SimpleResourceParameterResolverFactoryTest.java
The SimpleResourceParameterResolverFactory is used to inject a resource of any type into message handling methods.
This is done by creating a SimpleResourceParameterResolverFactory with the resource you want it to inject.
By adding SimpleResourceParameterResolverFactory to the ParameterResolverFactories used by the Axon application,
any message handling method with a parameter similar to the type of resource will get the resource injected.
=> Added a SimpleResourceParameterResolverFactory

core/src/main/java/org/axonframework/common/property/DirectPropertyAccessStrategy.java, core/src/main/java/org/axonframework/common/property/DirectlyAccessedProperty.java, core/src/main/resources/META-INF/services/org.axonframework.common.property.PropertyAccessStrategy, core/src/test/java/org/axonframework/common/property/DirectPropertyAccessStrategyTest.java
Since I have Event message like
public class EventMsg{
public String data;
public EventMsg(String data){
this.data = data;
}
}
and current @SagaEventHandler(associationProperty = "data") is not supporting this, edited a property accessor methods. Don't know if there is some other way to access the fields directly.
=> Support public fields without get methods on Message

distributed-commandbus-jgroups/src/main/java/org/axonframework/jgroups/commandhandling/JGroupsConnector.java
When Jgroups thread pool queue is enabled [thread_pool.queue_enabled=true], under heavy command load JoinMessages get queued up after regular command/reply messages and take long time to process and some time even rejected if the queue is maxed out. This results in a members having different member views of each other and inconsistent hash-rings. This then leads into routing strategy not working as desired.
We should send JGroups JoinMessage out-of-band [OOB] in order for them to take precedence over regular command/reply messages, and get processed by jgroups oob_thread_pool which is separate from the regular JGroups thread pool.
=> Send JGroups JoinMessage out-of-band [OOB] to take precedence

core/src/main/java/org/axonframework/common/AxonThreadFactory.java
Give a name to threads generated by axon in order to be able to identify them easily in thread dumps.
=> Name axon threads

spring/src/main/java/org/axonframework/spring/messaging/DefaultEventMessageConverter.java, spring/src/main/java/org/axonframework/spring/messaging/EventMessageConverter.java, spring/src/main/java/org/axonframework/spring/messaging/InboundEventMessageChannelAdapter.java, spring/src/main/java/org/axonframework/spring/messaging/OutboundEventMessageChannelAdapter.java, spring/src/test/java/org/axonframework/spring/messaging/DefaultEventMessageConverterTest.java
Same as #267 but targeting 3.0.x.
Also contains fix of #273
=> OutboundEventMessageChannelAdapter: wrong conversion of GenericDomainEventMessage

spring/src/main/java/org/axonframework/spring/messaging/DefaultEventMessageConverter.java
Spring Cloud Stream deserialize message headers with Jackson using `objectMapper.fromJson(headerValue, Object.class)` in `org.springframework.cloud.stream.binder.EmbeddedHeadersMessageConverter`.
When the `headerValue` contains a number which fits into an Integer, Jackson returns an Integer value.
Therefore we cannot cast directly to long, but we must perform a toLong conversion to be certain that no exception will be thrown.
=> SpringMessage: Use a converter to parse aggregate sequence long value

core/src/main/resources/org/axonframework/eventsourcing/eventstore/jpa/SQLErrorCode.properties, core/src/test/java/org/axonframework/eventsourcing/eventstore/jpa/SQLErrorCodesResolverTest.java
DB2 for iSeries (former AS400) uses the same SQL error code as DB2 for LUW but with a different JDBC driver and database product name. 
With this change, DataSources with this driver will be auto detected.
=> auto detect DB2 UDB using DataSource

distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringHttpCommandBusConnector.java, distributed-commandbus-springcloud/src/test/java/org/axonframework/springcloud/commandhandling/SpringHttpCommandBusConnectorTest.java
Currently the member URI path is not used by the SpringCloud CommandBus connector.
This makes it impossible to use this distributed command bus with applications running inside a webapp container.
=> SpringCloud Distributed CommandBus: Member URI path should be incorporated to the request URI

core/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java
When loading events by only `aggregateIdentifier` and `sequenceNumber` a `GlobalSequenceTrackingToken` should be used instead of a `GapAwareTrackingToken`.
Using a `GapAwareTrackingToken` causes an `OutOfMemoryError` when the `globalIndex` of the loaded event is very high, because the resulting gap is always 1 ... `globalIndex`.
=> Bugfix for an OutOfMemoryError

distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringCloudCommandRouter.java, distributed-commandbus-springcloud/src/test/java/org/axonframework/springcloud/commandhandling/SpringCloudCommandRouterTest.java
=> SpringCloudCommandRouter: Member name should not be only composed by the serviceId

distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringCloudCommandRouter.java, distributed-commandbus-springcloud/src/test/java/org/axonframework/springcloud/commandhandling/SpringCloudCommandRouterTest.java
=> SpringCloudCommandRouter: Membership update should remove service members absent from discoveryClient

core/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java, core/src/test/java/org/axonframework/eventhandling/TrackingEventProcessorTest.java
In a clustered Axon deployment we need the Saga's to run on a dedicated cluster member. We intend to use a leader election solution like Spring Integration Zookeeper. To make this work we need a TrackingEventProcessor that can be started / stopped repeatedly as leadership is granted / revoked. Any Saga should then use a TrackingEventProcessor to process events from the event store. Leader election will start / stop the TrackingProcessor on each member as expected.
(I moved my commit to a dedicated branch which deleted the original pull request)
=> reentrant TrackingEventProcessor

core/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/TokenSchema.java
There's a small bug in `TokenSchema.Builder`, calling `setProcessorNameColumn` does not have any effect because the parameter isn't used.
=> Use columnName parameter in setProcessorNameColumn

core/src/main/java/org/axonframework/eventhandling/SubscribingEventProcessor.java, core/src/test/java/org/axonframework/eventhandling/SubscribingEventProcessorTest.java
Without setting eventBusRegistration to null, there is no chance to restart SubscribingEventProcessor.
=> Allow SubscribingEventProcessor restart

core/src/main/java/org/axonframework/eventhandling/saga/AssociationResolver.java, core/src/main/java/org/axonframework/eventhandling/saga/MetaDataAssociationResolver.java, core/src/main/java/org/axonframework/eventhandling/saga/PayloadAssociationResolver.java, core/src/main/java/org/axonframework/eventhandling/saga/SagaEventHandler.java, core/src/main/java/org/axonframework/eventhandling/saga/SagaMethodMessageHandlerDefinition.java, core/src/main/java/org/axonframework/eventhandling/saga/SagaMethodMessageHandlingMember.java, core/src/test/java/org/axonframework/eventhandling/saga/AnnotatedSagaTest.java
This follows @abuijze's proposed specification described in #293.
=> Resolve #293 Allow saga event handler to resolve property name against metadata

core/src/main/java/org/axonframework/serialization/json/JacksonSerializer.java
Simply replaced JSR310Module with JavaTimeModule (recommended in the Jackson module). No tests added. Existing tests continue to pass.
=> Replaced use of deprecated JSR310Module with recommended JavaTimeModule

core/src/main/java/org/axonframework/common/io/IOUtils.java
Tiny correction to align the Javadoc with the implementation of the method.
=> Correction in Javadoc of IOUtils#closeQuietlyIfCloseable

core/src/main/resources/org/axonframework/eventsourcing/eventstore/jpa/SQLErrorCode.properties
We're using Axon with the HANA database from SAP. We're currently overriding the SQLErrorCode.properties to make it work properly.
=> Add duplicate key code for SAP HANA DB.

core/src/main/java/org/axonframework/saga/annotation/AsyncSagaEventProcessor.java, core/src/main/java/org/axonframework/saga/repository/jdbc/PostgresSagaSqlSchema.java
This is a series of two commits based on some work I've been doing recently to make my application scale to multiple hosts. The first adds an option to the PostgreSQL saga schema to allow it to acquire row locks when loading sagas from the database.
The second changes `AsyncSagaEventProcessor` to avoid database deadlocks when multiple nodes in a cluster publish events that need to be handled by the same sagas.
With these two changes and a distributed command bus, I'm able to successfully run my saga-heavy application on multiple nodes.
This may or may not be a useful approach in the 3.x world, but it may be of interest to other people with 2.x applications.
The first change could also live in `GenericSagaSqlSchema` but I don't know if people are using Axon with databases that don't …
=> Data loss prevention for sagas in clustered environments on PostgreSQL

test/src/main/java/org/axonframework/test/eventscheduler/StubEventScheduler.java, test/src/main/java/org/axonframework/test/saga/FixtureConfiguration.java, test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java, test/src/test/java/org/axonframework/test/eventscheduler/StubEventSchedulerTest.java, test/src/test/java/org/axonframework/test/saga/AnnotatedSagaTest.java
This revision adds a new method to the `FixtureConfiguration` interface: `givenCurrentTime`. This method is implemented in the `SagaTestFixture` class. I think it is important to note that by adding a new method to a public interface, this breaks backwards compatibility for users who have written their own implementations of `FixtureConfiguration`. If this is undesirable, we could either move the method to a new interface (to be implemented by `SagaTestFixture`), or we could just make it a public method in `SagaTestFixture`, without adding it to any interface. I chose to add it to `FixtureConfiguration` for now, to remain consistent with the other public methods in `SagaTestFixture`.
In order to make the date-time initialization work, I had to add a new method to `StubEventScheduler`: ` …
=> [#435] Allow initializing Saga fixture to specific date and time

core/src/main/java/org/axonframework/eventhandling/AbstractEventProcessor.java, core/src/test/java/org/axonframework/eventhandling/AbstractEventProcessorTest.java
Fixes the bug that the AbstractEventProcessor does not call each MonitorCallback once. Created a test for this scenario that also contains a test of a previous bug in this area, where the MonitorCallback would not be called when the message was modified during processing.
[#432]
=> Call correct MonitorCallback

core/src/main/java/org/axonframework/saga/annotation/AsyncSagaEventProcessor.java
I had briefly renamed this method during development and somehow the rename ended up in the original PR. Switch to the correct name.
=> Fix compile error in AsyncSagaEventProcessor

core/src/main/java/org/axonframework/commandhandling/distributed/AnnotationRoutingStrategy.java, spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/JGroupsAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/RoutingStrategyAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/SpringCloudAutoConfiguration.java, spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories, spring-boot-autoconfigure/src/test/java/org/axonframework/boot/AxonAutoConfigurationWithJGroupsTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/boot/AxonAutoConfigurationWithSpringCloudTest.java
Strategy). Also, if there is no @TargetIdentifier set on command payload
no error will be triggered, instead, random key policy will be used.
Resolves #450.
=> Added auto configuration for Routing Strategy (set to Annotation Routing

core/src/main/java/org/axonframework/commandhandling/model/inspection/AnnotatedAggregateMetaModelFactory.java, core/src/test/java/org/axonframework/commandhandling/StubAggregate.java, core/src/test/java/org/axonframework/commandhandling/model/inspection/AnnotatedAggregateMetaModelFactoryTest.java, core/src/test/java/org/axonframework/common/IdentifierValidatorTest.java, core/src/test/java/org/axonframework/eventsourcing/AggregateSnapshotterTest.java, integrationtests/src/test/java/org/axonframework/integrationtests/commandhandling/StubAggregate.java, spring/src/test/java/org/axonframework/spring/config/annotation/StubAggregate.java, test/src/test/java/org/axonframework/test/aggregate/AnnotatedAggregate.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CommandInterceptors.java, test/src/test/java/org/axonframework/test/aggregate/StandardAggregate.java
Aggregate field annotated with @EntityId or @AggregateIdentifier should override Object.toString()
- StubAggregate classes now use UUID or String as identifier type
- java.lang.Object is no longer supported as identifier type
=> issue #495: require toString() for types used as aggregate identifier

core/src/main/java/org/axonframework/config/EventHandlingConfiguration.java, core/src/test/java/org/axonframework/config/EventHandlingConfigurationTest.java, spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
This PR adds the option to configure an `ErrorHandler` in the `EventHandlingConfiguration`.
It allows to either adjust the default `ErrorHandler` or adjust an `ErrorHandler` per `EventProcessor`.
This PR resolves #500
=> [#500] Allow setting of ErrorHandler through Configuration API

spring/src/main/java/org/axonframework/spring/config/annotation/SpringBeanParameterResolverFactory.java, spring/src/test/java/org/axonframework/spring/config/annotation/SpringBeanParameterResolverFactoryTest.java
support for @Qualifier annotation in SpringBeanParameterResolverFactory
- @Qualifier annotation on event handlers' parameter take precedence over @Primary annotated bean candidates
- no support for custom @Qualifier annotations
=> issue 499: support @Qualifier annotation in SpringBeanParameterResolverFactory

core/src/main/java/org/axonframework/commandhandling/distributed/ConsistentHashChangeListener.java, core/src/main/java/org/axonframework/commandhandling/distributed/SimpleMember.java, distributed-commandbus-springcloud/pom.xml, distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringCloudCommandRouter.java, distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringCloudHttpBackupCommandRouter.java, distributed-commandbus-springcloud/src/test/java/org/axonframework/springcloud/commandhandling/SpringCloudCommandRouterTest.java, distributed-commandbus-springcloud/src/test/java/org/axonframework/springcloud/commandhandling/SpringCloudHttpBackupCommandRouterTest.java, spring-boot-autoconfigure/pom.xml, spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/SpringCloudAutoConfiguration.java, spring-boot-autoconfigure/src/test/java/org/axonframework/boot/AxonAutoConfigurationWithSpringCloudTest.java
This PR adjusts the `spring-cloud-commons` version from `1.1.5.RELEASE` to `1.3.1.RELEASE` and replaces any deprecated calls to that package.
Main point of interested is the removal of the `DiscoveryClient#getLocalServiceInstance()` call for the `Registration` class. All usages of that call in the `SpringCloudCommandRouter` have been replaced  by introducing a global private `Registration localServiceInstance` variable which is set on construction of the router.
Additionally I did:
- Updated the javadoc accordingly.
- Remove the deprecated constructor from the `SpringCloudCommandRouter`.
- Added a NoOp constant for the `ConsistentHashChangeListener` for added clarity when no change listener is required.
- Adjust the auto configuration to require a `Registration` bean.
This PR will resolve …
=> [#488] Update spring-cloud-commons to 1.3.1 and replace deprecated calls

core/src/main/java/org/axonframework/commandhandling/model/AggregateLifecycle.java, core/src/main/java/org/axonframework/commandhandling/model/inspection/AnnotatedAggregate.java, core/src/test/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStoreTest.java, test/src/main/java/org/axonframework/test/aggregate/StubAggregateLifecycle.java
=> Exposed aggregate version through static method in aggregate lifecycle.

core/pom.xml
Upgrading xstream dependency to 1.4.10
Fix #579
=> Upgrading xstream dependency to 1.4.10

spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java, spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
If event upcasters are declared as beans, they are now picked up and registered within configuration.
Resolves #560.
=> Auto registration of event upcasters

core/src/main/java/org/axonframework/eventhandling/scheduling/ScheduleToken.java, core/src/main/java/org/axonframework/eventhandling/scheduling/java/SimpleScheduleToken.java, core/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzScheduleToken.java, core/src/test/java/org/axonframework/eventhandling/scheduling/ScheduleTokenJacksonSerializationTest.java
This PR adds `JsonTypeInfo` to the `ScheduleToken` interface to be able to let a `ScheduleToken` be de-/serialized by Jackson correctly.
This PR resolves #589
=> [ #589]  SerializationException when storing ScheduleToken in a Saga using JacksonSerializer

distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringCloudCommandRouter.java, distributed-commandbus-springcloud/src/test/java/org/axonframework/springcloud/commandhandling/SpringCloudCommandRouterTest.java, spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/SpringCloudAutoConfiguration.java
This PR introduces a solution to ensure the `SpringCloudCommandRouter` selects a consistent spot for the local-member in it's `ConsistentHash`. 
In a previous release we adjusted the local member's name to `{service-id}[LOCAL]`, instead of setting the name to `{service-id}{service-uri}`. 
We did this because Spring Cloud 1.3.1 and up threw a `NullPointerException` if the `URI` was requested from a local instance in the start-up phase. 
The name of a member is however used to create the hash were the member will live on the `ConsistenHash` ring. As such, each node would deem itself the best spot to have the 'local-spot' on the ring.
This fix introduces a solution which listens to the `InstanceRegisteredEvent` from Spring Cloud, which serves as a notifier that the local instance has been …
=> [#600] Inconsistent routing to local instance in SpringCloudCommandRouter

spring/src/main/java/org/axonframework/spring/config/AbstractAnnotationHandlerBeanPostProcessor.java
Fixed IllegalArgumentException in AbstractAnnotationHandlerBeanPostProcessor when beanName parameter is null.
postProcessAfterInitialization was calling beanFactory.containsBean() and beanFactory.isSingleton() without checking beanName for null.
Closes #585
=> Fixed IllegalArgumentException in AbstractAnnotationHandlerBeanPostProcessor when beanName is null

core/src/main/java/org/axonframework/common/ObjectUtils.java, core/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java, core/src/main/java/org/axonframework/queryhandling/responsetypes/AbstractResponseType.java, core/src/main/java/org/axonframework/queryhandling/responsetypes/InstanceResponseType.java, core/src/main/java/org/axonframework/queryhandling/responsetypes/MultipleInstancesResponseType.java, core/src/test/java/org/axonframework/queryhandling/FutureAsResponseTypeToQueryHandlersTest.java, core/src/test/java/org/axonframework/queryhandling/responsetypes/AbstractResponseTypeTest.java, core/src/test/java/org/axonframework/queryhandling/responsetypes/InstanceResponseTypeTest.java, core/src/test/java/org/axonframework/queryhandling/responsetypes/MultipleInstancesResponseTypeTest.java
Added support for future as response type for query handlers: If return type of query handler is of type future, query bus will block until computation is done and inform query side about result.
Resolves #554
=> Future as response type to query handlers.

core/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java, core/src/main/java/org/axonframework/eventsourcing/eventstore/BatchingEventStorageEngine.java, core/src/main/java/org/axonframework/eventsourcing/eventstore/NoOpSnapshotJury.java, core/src/main/java/org/axonframework/eventsourcing/eventstore/RevisionBasedSnapshotJury.java, core/src/main/java/org/axonframework/eventsourcing/eventstore/SnapshotJury.java, core/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java, core/src/test/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngineTest.java, core/src/test/java/org/axonframework/eventsourcing/eventstore/RevisionBasedSnapshotJuryTest.java, core/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngineTest.java
This is a fix related to issue #566 
Added a hook in AbstractEventStorageEngine to filter snapshot based on a criteria which can be customized by implementing SnapshotJury.
Provided a reference implementation which ignores snapshots by comparing the snapshot payload version with the aggregate revision using RevisionResolver (suggested by @abuijze ). Clients can have their own implementations, if they want.
Defaults to Noop filtering which behaves as per the existing code, by always loading snapshot, if present.
** Only implemented for JDBCEventStorageEngine. Its a similar procedure for other storage engines. If you are okay with this implementation, I can do it for the rest **
=> Add feature to ignore snapshot by applying some criteria on it. Reference issue #566

core/src/main/java/org/axonframework/queryhandling/QueryUpdateEmitter.java, core/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java, core/src/test/java/org/axonframework/queryhandling/SubscriptionQueryTest.java
=> [#647] QueryUpdateEmitter doesn't respect UnitOfWork lifecycle

core/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngine.java
After changing JPA implementation from Hibernate to EclipseLink, TrackingEventProcessor fails due to incorrect JPQL query with exception:
```
2018-07-19 11:16:35.036 ERROR 566 --- [dedEventStore-0] o.a.e.eventstore.EmbeddedEventStore      : Failed to read events from the underlying event storage
java.lang.IllegalArgumentException: You have attempted to set a value of type class java.util.Collections$UnmodifiableSortedSet for parameter gaps with expected type of long from query string SELECT e.globalIndex, e.type, e.aggregateIdentifier, e.sequenceNumber, e.eventIdentifier, e.timeStamp, e.payloadType, e.payloadRevision, e.payload, e.metaData FROM DomainEventEntry e WHERE e.globalIndex > :token OR e.globalIndex IN (:gaps) ORDER BY e.globalIndex ASC.
at …
```
=> JPQL "IN" expression corrected to work with EclipseLink

core/src/test/java/org/axonframework/queryhandling/SubscriptionQueryTest.java
Fixed synchronization of multithreaded tests in `SubscriptionQueryTest`.
=> Subscription Query Test sync fix.

core/src/main/java/org/axonframework/eventhandling/MultiEventHandlerInvoker.java, core/src/test/java/org/axonframework/eventhandling/MultiEventHandlerInvokerTest.java
This PR adjusts the `MultiEventHandlerInvoker` to not catch a thrown exception from it's delegates on the `handle(EventMessage<?>, Segment)` function, but leave it as is.
This PR resolves #689
=> [#689] Don't catch event handling exception in MultiEventHandlerInvoker

core/src/main/java/org/axonframework/eventsourcing/EventSourcingRepository.java
Adding additional constructor as to allow one to use the EventSourcingRepository with a custom lockfactory in combination with an (preconstructed) AggregateModel.
=> EventSourcingRepository with custom Lockfactory combined with AggregateModel

core/src/main/java/org/axonframework/config/EventHandlingConfiguration.java, core/src/main/java/org/axonframework/config/EventProcessingConfiguration.java, spring/src/test/java/org/axonframework/spring/config/EventProcessingConfigurationConfigTest.java
#687 This issue introduces the registerHandlerInterceptor(BiFunction) in the EventProcessingConfiguration.
The same method exists in the EventHandlerConfiguration, but is deprecated since v3.3. Not alternative method was introduced yet in the EventProcessingConfiguration.
- Added the method in the EventProcessingConfiguration
- Adjusted the interceptorsFor method to also pass the default handler interceptors
- Adjusted the EventProcessingConfigurationTest
- Added comments
This is the PR for the 3.3.x branch
PR for the master branch is here #709
=> #687 EventProcessingConfiguration registerHandlerInterceptor(BiFunction) - 3.3.5

core/src/main/java/org/axonframework/config/EventProcessingConfiguration.java, spring/src/test/java/org/axonframework/spring/config/EventHandlingConfigurationWithInterceptorsTest.java, spring/src/test/java/org/axonframework/spring/config/EventProcessingConfigurationConfigTest.java
Add handler interceptors to builders within EventProcessingConfiguration. Reason for this is if we reinitialize the configuration, interceptor gets registered with the EventProcessor.
This PR resolve #714.
=> Fix for #714

spring/src/main/java/org/axonframework/spring/config/AnnotationDriven.java
Fixing the documentation on AnnotationDriven, as the AnnotationDrivenRegistrar doesn't register eventhandlers with the eventbus but rather registers queryhandlers with the querybus.
=> Fixing the documentation on AnnotationDriven

test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java, test/src/test/java/org/axonframework/test/aggregate/ResultValidatorImplTest.java
This PR resolves #725 
Introduces Test and Fix for the bug where calling expectEvents() with EventMessage... on ResultValidatorImpl would always result in a failed test, whether they are valid or not.
=> Issue725 expect events always fails for event messages

core/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java
(meant was "tail token" not "head token")
=> Bugfix of Exception Text in JdbcEventStorageEngine

core/src/main/java/org/axonframework/eventhandling/scheduling/quartz/FireEventJob.java, core/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java, core/src/test/java/org/axonframework/eventhandling/scheduling/quartz/DirectEventJobDataBinderTest.java, core/src/test/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventSchedulerTest.java
This PR introduces an adjustment to the `QuartzEventScheduler`, which makes it so that scheduled events will use a configurable `Serializer` to store a serialized version of the `EventMessage` in the Quartz `JobDataMap` instead of the `EventMessage` directly.
The old format made it so that Java serialization was performed, which is not inline with how the framework de-/serializes messages overall.
This PR resolves #749
=> [#749] QuartzEventScheduler must use serializer to serialize events

core/src/main/java/org/axonframework/config/EventProcessingConfiguration.java, spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java, spring/src/test/java/org/axonframework/spring/config/EventProcessingConfigurationConfigTest.java
If there is `@ProcessingGroup` annotation on a Saga, pick up the group name and register it within Saga config (this is related to the Spring config).
EventProcessingConfiguration - combine all handler builder functions first and then assign them to processors, old implementation was overriding handler builders that were assigned to the same processor.
=> Saga spring config

distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringCloudHttpBackupCommandRouter.java
for instances that are not available, unless debug level is enabled in which case include stacktrace.
This occurs whenever any service is registered with eureka registry but does not have distributed command bus enabled. All other services will log ugly exceptions (which in my opinion is warnings seeing that they're logged under INFO), prompting sysadmins to investigate "error" unnecessarily.
PR addresses concern by suppressing exception stack trace and only showing it if logger's level is set to DEBUG.
=> SpringCloudHttpBackupCommandRouter: Suppress exception stack traces when logging info messages

core/src/main/java/org/axonframework/config/ConfigurationScopeAwareProvider.java, core/src/test/java/org/axonframework/config/ConfigurationScopeAwareProviderTest.java
This PR addresses a bug we encountered when using the with `ConfigurationScopeAwareProvider` with Axon's Spring autoconfiguration.
This bug occurred because `ConfigurationScopeAwareProvider` did not detect `LazyRetrievedModuleConfiguration` to be a `ModuleConfiguration` which wraps the actual `SagaManagerConfiguration`. As a consequence, deadline messages are not being sent to relevant Saga instances as a result of failing to lookup `SagaManager`s configured by the `SpringAutoConfigurer`.
Similar behavior was expected (and addresses by this PR) with Aggregates (also a `ScopeAwareComponent`), for similar reasons.
In addition to aforementioned bugfix, this PR addresses a non-observed but possible bug where concurrent initialization of the `ConfigurationScopeAwareProvider` could yield in …
=> Fix resolving of ScopeAwareProvider components in Spring autoconfigured context

kafka/src/main/java/org/axonframework/kafka/eventhandling/consumer/DefaultConsumerFactory.java, kafka/src/main/java/org/axonframework/kafka/eventhandling/producer/DefaultProducerFactory.java, spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/KafkaAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/KafkaProperties.java, spring-boot-autoconfigure/src/test/java/org/axonframework/boot/KafkaAutoConfigurationTests.java, spring-boot-autoconfigure/src/test/resources/ksLoc, spring-boot-autoconfigure/src/test/resources/ksLocP, spring-boot-autoconfigure/src/test/resources/tsLoc, spring-boot-autoconfigure/src/test/resources/tsLocP
- Fixes #710 
- Fixes #717
- Added support for consumer and producer specific properties.
=> Tests for KafkaAutoConfiguration

test/src/main/java/org/axonframework/test/matchers/Matchers.java
Noticed this issue when migrating from Axon 2.x to 3.x.
Cfr: issue #269 and https://groups.google.com/forum/?nomobile=true#!searchin/axonframework/exactSequenceOf%7Csort:date/axonframework/kr8AMCqh3io/d3ESeFMqBwAJ
=> Fix generics on Matchers.exactSequenceOf()

core/src/main/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStore.java, core/src/test/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStoreTest.java
Implemented an overloaded version of the `EmbeddedEventStore` constructor, to allow the usage of a custom `ThreadFactory`.
This PR resolves #735.
=> [#735] Constructor overloading for threadfactory in EmbeddedEventStore

pom.xml
This adds a Maven profile for the jacoco plugin, to generate unit test coverage information.
=> Added jacoco-maven plugin to generate coverage information.

distributed-commandbus-jgroups/src/main/java/org/axonframework/jgroups/commandhandling/JGroupsConnector.java, distributed-commandbus-jgroups/src/test/java/org/axonframework/jgroups/commandhandling/JGroupsConnectorTest.java
An issues arose if a thread would perform a 'send and wait' to dispatch a command, which would end up another node which would ping back a 'send and wait' to the original dispatcher. By introducing an `ExecutorService` which instantiates a thread to receive a message, we unblock this problem. Added a test to verify and solve the pointed out issue. This is a solution for the `JGroupsConnector`, but something similar should be introduced in the `SpringHttpCommandBusConnector`, as described in #756.
This issue resolves bug #777.
=> [#777] Introduce ExecutorService to unblock upon receiving a message in JGroupsConnector

core/src/main/java/org/axonframework/commandhandling/AsynchronousCommandBus.java, spring/src/main/java/org/axonframework/spring/eventhandling/scheduling/java/SimpleEventSchedulerFactoryBean.java
Use AxonThreadFactory instead of default so thread pools and thread created by axon have non-default names (e.g.: useful for troubleshooting stuck threads).
This is based on another PR, #790.
=> Use AxonThreadFactory instead of default

core/src/main/java/org/axonframework/common/lock/PessimisticLockFactory.java, core/src/test/java/org/axonframework/common/lock/PessimisticLockFactoryTest.java
Adding back off support to PessimisticLockFactory to avoid unresponsiveness under load.
Backing off from trying to obtain a lock allows the system to signal, to client firing commands, that it failed to do so in a reasonable amount of time, allowing the client to respond / degrade gracefully. (perhaps by throttling, rescheduling or dropping commands)
Also should an specific aggregate(or saga) (type or instance) contain bad logic, then backing off allows the system to still process commands targeting other aggregates(or sagas). If one waits indefinitely then eventually all worker threads will be waiting to obtain the lock causing the pool to dry up. At that point the system no longer processes commands, making it unavailable.
=> Adding back off support to PessimisticLockFactory

distributed-commandbus-jgroups/src/test/java/org/axonframework/jgroups/commandhandling/JgroupsConnectorTest_Gossip.java, distributed-commandbus-springcloud/src/main/java/org/axonframework/springcloud/commandhandling/SpringHttpCommandBusConnector.java, distributed-commandbus-springcloud/src/test/java/org/axonframework/springcloud/commandhandling/SpringHttpCommandBusConnectorTest.java
Made the sending of commands through the `RestOperations` in the  `SpringHttpCommandBusConnector` use an `Executor` to make those calls async.
Additionally, added missing javadoc to the `SpringHttpCommandBusConnector`.
=> [#756] SpringHttpCommandBusConnector should support async execution

axon-server-connector/pom.xml, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerException.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModule.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/AxonServerEventStoreClient.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/EventProcessorInfoConfiguration.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/grpc/GrpcEventProcessorInfoSource.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java, axon-server-connector/src/main/resources/META-INF/services/org.axonframework.config.ConfigurerModule, axon-server-connector/src/main/resources/axonserver_download.txt, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModuleTest.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/ServerConnectorRunner.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java, core/src/main/java/org/axonframework/config/ConfigurerModule.java, core/src/main/java/org/axonframework/config/DefaultConfigurer.java, core/src/main/java/org/axonframework/config/EventProcessingConfigurer.java, core/src/main/java/org/axonframework/config/EventProcessingModule.java, pom.xml, spring-boot-autoconfigure/src/main/java/org/axonframework/boot/autoconfig/AxonServerAutoConfiguration.java, spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
When using the Configuration API, and the AxonServer Connector is on the
classpath, it will be used by default, using sensible (dev) settings.
When starting with default settings, the AxonServer Connector will
output a message stating where AxonServer can be downloaded.
This commit also includes a few minor naming changes on the AxonServer
configuration.
=> Added connectivity to AxonServer as default behavior of Config API

core/src/main/java/org/axonframework/eventsourcing/eventstore/EventUtils.java, core/src/main/java/org/axonframework/serialization/AbstractXStreamSerializer.java, core/src/main/java/org/axonframework/serialization/JavaSerializer.java, core/src/main/java/org/axonframework/serialization/SerializedType.java, core/src/main/java/org/axonframework/serialization/json/JacksonSerializer.java, core/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngineTest.java, core/src/test/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngineTest.java, core/src/test/java/org/axonframework/serialization/JavaSerializerTest.java, core/src/test/java/org/axonframework/serialization/json/JacksonSerializerTest.java, core/src/test/java/org/axonframework/serialization/xml/XStreamSerializerTest.java
Backport of a fix done in the 4.0 release to 3.4.x.
The main difference is that a `null` payload is returned for unknown events, instead of an UnknownSerializedType. This only happens in cases where unknown types are explicitly skipped.
=> Bugfix 807 backport

core/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java, core/src/test/java/org/axonframework/eventhandling/TrackingEventProcessorTest.java
when no tokens in batch could be handled. Resolves #872
=> Token in TrackingEventProcessor status API should be updated

test/src/main/java/org/axonframework/test/saga/FixtureConfiguration.java, test/src/main/java/org/axonframework/test/saga/FixtureExecutionResultImpl.java, test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java, test/src/test/java/org/axonframework/test/saga/FixtureExecutionResultImplTest.java, test/src/test/java/org/axonframework/test/saga/SagaTestFixtureTest.java
Note:
This PR is similar to #898, but made against (at time of writing) most recent master of 4.x+.
This change enables SagaFixture to register callbacks to be notified when the
recording of fixture execution results starts.
This is particularly helpful to testing scenarios where a Saga collaborator
resource(s) is injected which is not a well known Axon collaborator (such as
e.g. CommandGateway), but is interested in having its interactions verified,
local to a specific Saga message handling.
=> Allow registration of sagafixture start recording callbacks

spring-boot-autoconfigure/pom.xml
This dependency generate metadata needed to help Spring Boot with the
startup time.
=> Add spring boot configuration processor dependency

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/ExceptionSerializer.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/util/ExceptionSerializerTest.java
When an exception occurs in a Command or Query Handler, this exception is not properly serialized into a protobuf message. As a result, senders aren't notified of the exception and receive a timeout.
=> Exception results are not properly sent to AxonServer

core/src/main/java/org/axonframework/eventsourcing/eventstore/BatchingEventStorageEngine.java, core/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java, core/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngineTest.java
This PR introduces a fix so that the `JdbcEventStorageEngine` will enforce further retrieval of events from the database, even if the retrieved batch contained gaps.
It does so by overriding the `BatchingEventStorageEngine.readEventData(String, long)` function and using the `EventStreamSpliterator` (which was made protected) with `fetchUntilEmpty` set to false.
Doing so will ensure that the `EventStreamSpliterator` notices it should fetch another batch of events, which enables this functionality to retrieve all the events for a given Aggregate regardless of any gaps in the Aggregate's event stream.
This PR resolves #911.
=> [#911]  JdbcEventStorageEngine should cope with potential Aggregate Event Stream gaps

core/src/main/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStore.java, core/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemoryEventStorageEngine.java, core/src/test/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStoreTest.java, core/src/test/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemoryEventStorageEngineTest.java
This PR introduces a `boolean` field which enables or disable 'event consumption optimization' in the `EmbeddedEventStore`. The `EmbeddedEventStore` has logic in place to let several Event Consumer read events from the same event-stream-tailing consumer. There might however be scenario that this optimization is not desirable, hence opening it up to be switched off is desirable. 
The default approach to this is `true` as that's what the `EmbeddedEventStore` used to do initial.
To adjust the `optimizeEventConsumption` field, one could either create the `EmbeddedEventStore` themselves and provide this field through the constructor. If something like Spring (Boot) is used to instantiate the Axon application, this might not be desirable. To that end, we've opened up the option to provide a …
=> [#915] Make Event Consumption optimization adjustable

messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStore.java, messaging/src/test/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStoreTest.java
To tune performance, it may be desired to override the default lock
mode when reading tokens from the token store. This commit adds an
option to the builder of the JpaTokenStore that allows this to be
overridden.
=> Allow customization of lock mode when reading tokens

messaging/src/main/java/org/axonframework/messaging/RemoteHandlingException.java
Added the causes reported by the remote message handler to the exception message, to improve ability to debug.
=> Add cause description to exception message

integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java, messaging/src/main/java/org/axonframework/eventhandling/GlobalSequenceTrackingToken.java, messaging/src/test/java/org/axonframework/eventhandling/GlobalSequenceTrackingTokenTest.java
Hi,
As requested by @smcvb, this is a pull request of my earlier fix (see https://github.com/AxonFramework/AxonFramework/pull/930) but for 4.0.x instead of master.
Regards,
Jens De Wit
=> Fix GlobalSequenceTrackingToken.covers for Axon 4.0.x

messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
Hi,
In our application we want to have monitoring in order to see where a tracking event processor is comparing to the head of the stream.  
In order to accomplish this in a 'generic' way we need access to the messageSource.  Currently we have worked around this using reflection but this is far from ideal.  A getter would be mush more useful.
`StreamableMessageSource messageSource = (StreamableMessageSource) FieldUtils.readField(trackingEventProcessor, "messageSource", true);
TrackingToken headToken = messageSource.createHeadToken();`
=> Add getter for the messageSource

messaging/src/main/java/org/axonframework/eventhandling/AbstractEventProcessor.java
In our application we have built a system to handle errors more gracefully.
It is some kind of deadletter queue for events from a tracking event processor.
In order to replay those events I need access to the eventHandlerInvoker. Unfortunately the getter is protected. This pull request is to make it public.
=> make org.axonframework.eventhandling.AbstractEventProcessor#eventHandlerInvoker public

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfigurationTest.java
Conditionally load `AxonServerCommandBus` if there is no **unqualified `CommandBus`** in the Spring context already
**The idea:**
If there is a bean of type `CommandBus` **qualified with `localSegmet`**, it will be used by `AxonServerCommandBus`.
If there is a bean of type `CommandBus` **NOT qualified with any name**, `AxonServerCommandBus` will not be loaded to context at all (in favor of specific `CommandBus` that user defined).
=> Configure `AxonServerCommandBus` Spring (boot) bean to use `localSegment`

messaging/src/main/java/org/axonframework/commandhandling/gateway/IntervalRetryScheduler.java, messaging/src/main/java/org/axonframework/common/BuilderUtils.java
=> [#968] The IntervalRetryScheduler builder should provide sensible defaults

integrationtests/src/test/java/org/axonframework/integrationtests/eventstore/benchmark/mongo/MongoEventStoreBenchMark.java, mongo/src/main/java/org/axonframework/mongo/eventsourcing/eventstore/MongoEventStorageEngine.java, mongo/src/main/java/org/axonframework/mongo/eventsourcing/tokenstore/MongoTokenStore.java, mongo/src/test/java/org/axonframework/mongo/eventsourcing/eventstore/MongoEventStorageEngineTest.java, mongo/src/test/java/org/axonframework/mongo/eventsourcing/eventstore/MongoEventStorageEngineTest_DBObjectSerialization.java, mongo/src/test/java/org/axonframework/mongo/eventsourcing/eventstore/MongoEventStorageEngineTest_DocPerCommit.java, mongo/src/test/java/org/axonframework/mongo/eventsourcing/tokenstore/MongoTokenStoreTest.java
This allows the use of MongoTokenStore in a non-dependency-injected
environment without shifting the burden of initialization onto the
programmer. This is particularly important because of the unintended
event replays which can occur if the @PostConstruct call is not called
manually.
This PR resolves #973
=> Call ensureIndexes from constructors instead of @PostConstruct

pom.xml
this change reduces the number of failing tests while running on JDK 11
=> up mockito version

axon-server-connector/pom.xml, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorController.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/grpc/EventProcessors.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/grpc/GrpcEventProcessorInfoSource.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/grpc/GrpcEventProcessorMapping.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/grpc/PlatformInboundMessage.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/grpc/SubscribingEventProcessorInfoMessage.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/grpc/TrackingEventProcessorInfoMessage.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/EventProcessorControlServiceTest.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/EventProcessorControllerTest.java, pom.xml
This PR introduces the functionality to receive a split or merge `PlatformOutboundInstruction` from, for example, Axon Server.
To support this, the `EventProcessorControlService` has now included the `SPLIT_EVENT_PROCESSOR_SEGMENT` and `MERGE_EVENT_PROCESSOR_SEGMENT` operations to the `AxonServerConnectionManager`, which will add a `Consumer` which issues a split/merge against the `EventProcessorController`.
The `EventProcessorController` in turn will try to retrieve the right `EventProcessor` and hit the `mergeSegment(int)`/`splitSegment(int)` methods.
Additionally, I've performed some clean up operations, leading to re-indents of the file, added javadoc,  modifier adjustments and some new test cases.
This PR relies on the Axon Server API addition of split and merge, which will be …
=> [#995] Implement split-and-merge in Axon Server Client

.travis.yml, config/src/main/java/org/axonframework/config/EventProcessingConfigurer.java, config/src/main/java/org/axonframework/config/EventProcessingModule.java
This PR adds the `registerTrackingEventProcessorConfiguration(Function<Configuration, TrackingEventProcessorConfiguration>)` function to set the default `TrackingEventProcessorConfiguration` to use for any `TrackingEventProcessor` of no specific one is provided through the regular `registerTrackingEventProcessor()` functions.
This PR resolves issue #881
=> [#881]  Add possibility to register default TrackingEventProcessorConfiguration

pom.xml
fix javassist's WARNING: An illegal reflective access operation has occurred
=> Fix javassist's WARNING: An illegal reflective access operation has occurred

config/pom.xml, disruptor/pom.xml, eventsourcing/pom.xml, integrationtests/pom.xml, legacy/pom.xml, messaging/pom.xml, modelling/pom.xml, pom.xml, spring-boot-autoconfigure/pom.xml, spring/pom.xml, test/pom.xml
* Fix version discrepancy for `hibernate-entitymanager` and `hsqldb` dependencies. The former has had the version `5.1.0.Final` in `config`, `eventsourcing` modules and `4.3.8.Final` in the `integrationtests` module. The latter has had the version `2.3.4` in `config`,  `eventsourcing` modules and  `2.3.4` in the `spring-boot-autoconfigure` module. Fixed by moving the dependencies with max version to `<dependencyManagement>`
* Divorce versions for spring and spring-security
* Move some frequently used dependencies to `<dependencyManagement>`
* Replace some dependencies in `<dependencyManagement>` with BOM (Bill Of Materials)
=> Fix version discrepancy + move some deps to dependencyManagement

integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java, messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
The `TrackingEventProcessor#mergeSegment(int)` operation shouldn't be allowed to occur if there's just a single segment present for the given `TrackingEventProcessor`.
To that end, this pull request checks whether the 'segment to merge with' it's `segmentId` is identical to the `segmentId` used to call the `mergeSegment` function, by leveraging the `Segment#mergeableSegmentId()` function.
If this returns `true`, a `CompletableFuture.completedFuture(false)` will be returned.
=> Ignore merge segment request if there is only a single segment present

messaging/src/test/java/org/axonframework/common/lock/PessimisticLockFactoryTest.java, test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java, test/src/main/java/org/axonframework/test/aggregate/TestExecutor.java
Introduce a `whenThenTimeElapses()` and `whenThenTimeAdvancesTo()` function, to replace the misleadingly named `andThenTimeElapses()` and `andThenTimeAdvancesTo()` functions. 
All four return the result, thus ending the possibility to chain further. A method starting with `and...()` however suggest you can do more afterwards, which isn't the case with these methods.
Next to adding these new functions, the old ones are deprecated and the javadoc has been updated accordingly.
This PR resolves #1014
=> [#1014]  Misleading method names in AggregateTestFixture

pom.xml
Running `mvn -Pcoverage clean test` on JDK 11 results in 
`Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?`
The version update fixes the problem.
=> Fix running tests with jacoco on JDK 11

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/EventProcessorProperties.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/EventProcessorConfigurationTest.java, spring-boot-autoconfigure/src/test/resources/test-processors.application.properties
=> [#1008] Provide functionality to set the 'Token Claim Interval' for TrackingEventProcessors through a Spring Configuration file

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/AppendEventTransaction.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/AxonServerEventStoreClient.java
This PR makes it possible to configure the `commitTimeout` when events should be appended to the Event Store present in Axon Server from an Axon Server Client instance.
=> Make Commit Timeout configurable

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/AxonServerEventStoreClient.java
This is triggered when the AxonServerEventStoreClient receives an error
indicating that the connected node is not the leader, or is otherwise
unable to respond to the request.
Resolves #1029
=> Added logic to force a disconnection to AxonServer

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/DispatchInterceptors.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/DummyMessagePlatformServer.java
The `AxonServerQueryBus` in the `axon-server-connector` module wasn't utilizing the registered `MessageDispatchInterceptor` to intercept a `subscriptionQuery` call.
This PR adjust that issue and as such resolves #1013
=> [#1013] Use MessageDispatchInterceptor on Subscription Query in Axon Server Query Bus

config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngine.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngineTest.java
This pull request ensure that the `JpaEventStorageEngine` uses the `TransactionManager` to perform the `appendEvents(List<EventMessage>, Serializer)` call in a Transaction, always.
Typically, this transaction is started by the `CommandGateway` is that's the starting point of entering an Aggregate/External Command Handler, and applying events as a result of that.
However, if somebody would want to publish events directly when utilizing the `JpaEventStorageEngine`, then that would form an issue from a Transaction perspective.
This pull request resolve #1035
=> [#1035] Utilize TransactionManager on append events operation

messaging/src/main/java/org/axonframework/eventhandling/GapAwareTrackingToken.java, messaging/src/main/java/org/axonframework/eventhandling/GlobalSequenceTrackingToken.java, messaging/src/main/java/org/axonframework/eventhandling/ReplayToken.java, messaging/src/main/java/org/axonframework/eventhandling/TrackingToken.java, messaging/src/test/java/org/axonframework/eventhandling/GapAwareTrackingTokenTest.java, messaging/src/test/java/org/axonframework/eventhandling/GlobalSequenceTrackingTokenTest.java, messaging/src/test/java/org/axonframework/eventhandling/MergedTrackingTokenTest.java, messaging/src/test/java/org/axonframework/eventhandling/ReplayTokenTest.java
Hi,
I have written following construct a few times now:
```
if (token instanceof GlobalSequenceTrackingToken) {
return ((GlobalSequenceTrackingToken) token).getGlobalIndex();  
} else if (token instanceof GapAwareTrackingToken) { 
return ((GapAwareTrackingToken) token).getIndex();  
} else { 
return -1L; 
}
```
We use this index for monitoring purposes to see where our trackingEventProcessors are and for debugging and general troubleshooting.
While writing this it felt like this should actually be a feature of the TrackingToken interface because it represents a position.
It might be useful for other people as well.
However, I did not find a meaningful implementation for the `MergedTrackingToken` which uses the default implementation of `-1L`.
Regards,
Tom
=> Add position to trackingToken

config/src/main/java/org/axonframework/config/Configuration.java, config/src/main/java/org/axonframework/config/DefaultConfigurer.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithDisruptorTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerPropertiesTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithHibernateTest.java, spring/src/main/java/org/axonframework/spring/config/AxonConfiguration.java
The PR resolves [#1047](https://github.com/AxonFramework/AxonFramework/issues/1047)
Streamline EventGateway with CommandGateway/QueryGateway:
Adding it to spring boot autoconfiguration as well as to axon configuration and configurer,
exactly like in case of CommandGateway/QueryGateway.
=> Add EventGateway to configuration

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java, messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java, messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java, modelling/src/main/java/org/axonframework/modelling/saga/repository/jdbc/JdbcSagaStore.java, modelling/src/main/java/org/axonframework/modelling/saga/repository/jpa/JpaSagaStore.java
The default XStream based serializer is only initialized when no explicit
serializers have been configured. This ensures that the warning message
about XStream's security subsystem not being initialized isn't logged
unless an unsafe instance is really used.
Furthermore, this allows XStream to be excluded from the dependencies
when it isn't used at runtime.
Resolves #1054
=> Lazy initialization of Serializers to prevent erroneous warning messages

messaging/src/main/java/org/axonframework/common/ReflectionUtils.java, messaging/src/main/java/org/axonframework/messaging/responsetypes/AbstractResponseType.java, messaging/src/main/java/org/axonframework/messaging/responsetypes/MultipleInstancesResponseType.java, messaging/src/main/java/org/axonframework/messaging/responsetypes/OptionalResponseType.java, messaging/src/main/java/org/axonframework/messaging/responsetypes/ResponseTypes.java, messaging/src/main/java/org/axonframework/queryhandling/annotation/MethodQueryMessageHandlerDefinition.java, messaging/src/test/java/org/axonframework/messaging/responsetypes/AbstractResponseTypeTest.java, messaging/src/test/java/org/axonframework/messaging/responsetypes/MultipleInstancesResponseTypeTest.java, messaging/src/test/java/org/axonframework/messaging/responsetypes/OptionalResponseTypeTest.java, messaging/src/test/java/org/axonframework/messaging/responsetypes/ResponseTypesJacksonSerializationTest.java, messaging/src/test/java/org/axonframework/queryhandling/annotation/AnnotationQueryHandlerAdapterTest.java, messaging/src/test/java/org/axonframework/queryhandling/annotation/MethodQueryMessageHandlerDefinitionTest.java
On the handling side, Optional is considered a wrapper of the actual
return type. Hence, a handler declaring Optional<T> as return type is
considered a handler returning T.
On the dispatching side, Optional is merely used to wrap (potentially
null) return values. It doesn't change the expectations of the query
handler at all.
This PR resolves #552
=> [#552] Added explicit support for Optional in Queries

test/src/main/java/org/axonframework/test/aggregate/Reporter.java, test/src/main/java/org/axonframework/test/aggregate/ResultValidator.java, test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_MarkDeleted.java
The ResultValidator is extended to support two methods which express an expectation of
whether the Aggregate should have been marked as deleted or not. The test-suite for
TestFixture has been extended to cover these situations using the AnnotatedAggregate.
=> Adds the ability to validate the isDeleted state of an Aggregate in the TestFixture

messaging/src/main/java/org/axonframework/eventhandling/DisallowReplay.java, messaging/src/test/java/org/axonframework/eventhandling/replay/ReplayAwareMessageHandlerWrapperWithDisallowReplayTest.java
Hi, 
As I understand the logic for the AllowReplay annotation, it is as follows:
- No annotation: replay is allowed
- Annotation without boolean: replay is allowed
- Annotation with boolean: boolean value is use to decide the replay
Given this logic, the only time we seem to add the AllowReplay annotation is to not allow a replay.  To make this more explicit I thougt it would be usefull to have the 'inverted' annotation: "DisallowReplay".
Regards,
Tom.
=> Introduction of DisallowReplay annotation

legacy/pom.xml, legacy/src/main/java/org/axonframework/commandhandling/model/AggregateScopeDescriptor.java, legacy/src/main/java/org/axonframework/eventhandling/saga/SagaScopeDescriptor.java, legacy/src/test/java/org/axonframework/commandhandling/model/AggregateScopeDescriptorTest.java, legacy/src/test/java/org/axonframework/eventhandling/saga/SagaScopeDescriptorTest.java
This PR introduces legacy versions of the `AggregateScopeDescriptor` and `SagaScopeDescriptor` in the `axon-legacy` package. This will for example ensure that people migrating from Axon 3.x to 4.2 will be able to reuse their scheduled messages.
=> [#1097] Problem with ScopeDescriptor after migration from axon 3.4 to 4.1

messaging/pom.xml
Our OWASP-tooling identified XStream 1.4.10 to have a vulnerability. Version 1.4.11.1 fixes this vulnerability.
=> Updates version of XStream (fixes CVE-2013-7285 vulnerability)

messaging/src/main/java/org/axonframework/common/lock/PessimisticLockFactory.java, messaging/src/test/java/org/axonframework/common/lock/PessimisticLockFactoryTest.java
Fixed the variable in the log - we want to log acquireAttempts instead of maximum queued threads.
=> PessimisticLockFactory log fix

messaging/src/main/java/org/axonframework/messaging/annotation/HandlerComparator.java, messaging/src/test/java/org/axonframework/messaging/annotation/HandlerHierarchyTest.java
Changed the way we compare handlers - classes take precedence over interfaces. Depth of interface hierarchy is calculated based on interface inheritance level.
Co-Authored Sara Pellegrini
=> Handler Comparator Hierarchy Fix

messaging/src/main/java/org/axonframework/messaging/interceptors/LoggingInterceptor.java, messaging/src/test/java/org/axonframework/messaging/interceptors/LoggingInterceptorTest.java
Let the `LoggingInterceptor` implement both the `MessageHandlerInterceptor` and the `MessageDispatchInterceptor`. Doing so will allow a `LoggingInterceptor` to be used to log on dispatching a message and upon handling an incoming message.
This PR resolves #698
=> [#698] Make LoggingInterceptor implement Message Dispatch Interceptor

metrics-micrometer/src/main/java/org/axonframework/micrometer/reservoir/SlidingTimeWindowReservoir.java, metrics-micrometer/src/test/java/org/axonframework/micrometer/reservoir/SlidingTimeWindowReservoirTest.java
The time window given to the constructor of SlidingTimeWindowReservoir is converted to nanoseconds. However, the keys used in the field measurements are in milliseconds. This results in incorrect behavior when invoking the trim method. Less measurements are removed than required.
=> Fix time window in SlidingTimeWindowReservoir

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/GrpcMetaDataConverter.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/util/GrpcMetaDataConverterTest.java, messaging/src/main/java/org/axonframework/serialization/SerializedType.java
The `GrpcMetaDataConverter` currently we create a `MetaDataValue` containing the type `empty` if the `GrpcMetaDataConverter#convertToMetaDataValue(Object)` method receives a `null`.
This occurs because the `Serializer` will change the type to 'empty' as a fallback. 
However, when such a `MetaDataValue` is pulled through the `GrpcMetaDataConverter#convertFromMetaDataValue(MetaDataValue)`, the used `Serializer` will fail, stating it does not know the serialized type `empty` (and rightfully so).
Thus, it would be beneficial if the 'convertTo' method does not set a `null` serialized object, but instead returns an empty `MetaDataValue` instance.
This is exactly what this PR does, including several test cases to verify the validity of the `convertToMetaDataValue` and `convertFromMetaDataValue` …
=> Deal with null MetaData values in the GrpcMetaDataConverter

messaging/src/main/java/org/axonframework/common/jdbc/UnitOfWorkAwareConnectionProviderWrapper.java, messaging/src/test/java/org/axonframework/common/jdbc/UnitOfWorkAwareConnectionProviderWrapperTest.java
Currently, when connection rollback failed, the original exception is lost.
This makes it harder to investigate the problem why the `UnitOfWork` was rolled-back.
=> Keep UnitOfWork root exception when rollback failed

config/src/main/java/org/axonframework/config/AggregateConfigurer.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/EventSourcingRepository.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/EventSourcingRepositoryTest.java, integrationtests/src/test/java/org/axonframework/integrationtests/commandhandling/StubAggregate.java, integrationtests/src/test/java/org/axonframework/integrationtests/loopbacktest/synchronous/SynchronousLoopbackTest.java, spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java, spring/src/main/java/org/axonframework/spring/stereotype/Aggregate.java, spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
This acts as a sanity check and also eases migration from Axon 2, per discussion in https://groups.google.com/forum/#!msg/axonframework/fVKTSZrfYqY/n2IFnXzmCgAJ
=> Configurable event filtering for EventSourcingRepository

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModule.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConnectionManagerTest.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/AxonServerEventStoreClientTest.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
This pull request makes it possible to configure the `ScheduledExecutorService` used to schedule the reconnect tasks in the `AxonServerConnectionManager` to your hearts content. Currently, this is hard coded for you, whilst (as explained in #907) there are scenarios where it is beneficial if this could be adjusted or the control pulled in to the users own hands.
Making this configurable has been done by setting up the Builder pattern in the `AxonServerConnectionManager` in a similar fashion as the other framework components. Due to this, the constructors have been deprecated and all usages replaced with this Builder.
=> [#907] Allow customizing the ScheduledExecutorService for AxonServerConnectionManager

eventsourcing/src/main/java/org/axonframework/eventsourcing/MultiStreamableMessageSource.java
The poll time calculation in `MultiStreamableMessageSource.MultiSourceBlockingStream.hasNextAvailable()` assumed that it was being called with a timeout in milliseconds. Unfortunately, `TrackingEventProcessor.processBatch()` is hardwired to use a timeout of 1 second, denominated in seconds. So the timeout value of 1 was being divided by 10, resulting in a poll time of zero, which caused each event processor thread to sit in a tight CPU-bound loop checking for new messages with no sleeping at all.
=> Fix poll interval calculation in MultiStreamableMessageSource

test/src/main/java/org/axonframework/test/saga/EventValidator.java, test/src/test/java/org/axonframework/test/saga/AnnotatedSagaTest.java
This pull request resolves #1157
=> [#1157] Don't double-record published events if SagaTestFixture is invoked twice

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/grpc/TrackingEventProcessorInfoMessage.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/grpc/TrackingEventProcessorInfoMessageTest.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/subscription/AxonServerSubscriptionQueryResultTest.java
EventTrackerInfo has been renamed to SegmentStatus
Renamed to EventProcessorReference:
- PauseEventProcessor
- RequestEventProcessorInfo
- StartEventProcessor
Renamed to EventProcessorSegmentReference:
- MergeEventProcessorSegment
- ReleaseEventProcessorSegment
- SplitEventProcessorSegment
=> Code changes to reflect the new message names in the AxonServer gRPC API

spring/src/main/java/org/axonframework/spring/config/ConfigurerFactoryBean.java, spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
As this was done by an BeanDefinitionRegistrar, Spring configurations
were initialized too early. This could cause problems for configurations
depending on Post Processors to process beans.
The SpringAxonAutoConfigurer now creates a FactoryBean which wires all
the ModuleConfigurations before making the Configurer available to the
application context.
=> Improved timing of wiring of ConfigurerModules

config/src/main/java/org/axonframework/config/EventProcessingModule.java, messaging/src/main/java/org/axonframework/eventhandling/EventProcessor.java, messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
My application shutdown time is dominated by the sequential shutdown of all the `TrackingEventProcessor`s, each of which sleeps for a brief period. Shut them down in parallel instead.
=> Parallelize TrackingEventProcessor shutdown

integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java, integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest_MultiThreaded.java, messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java, messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessorConfiguration.java, messaging/src/main/java/org/axonframework/messaging/unitofwork/BatchingUnitOfWork.java
The Tracking Event Processor will now update the Token before it starts
processing the first Event from a Batch. This will force the necessary
lock on the Token row (when supported) and extends the claim. Only when
event processing took longer than the tokenClaimInterval, the Processor
will explicitly extend the Token's claim. Otherwise, it is assumed the
next batch will be sufficiently quick to start that the token is
extended well before the claim expires.
This behavior can be overridden in the
TrackingEventProcessorConfiguration.
Addresses issue #1168
=> Reduce load on TokenStore from Tracking Event Processor

eventsourcing/src/main/java/org/axonframework/eventsourcing/MultiStreamableMessageSource.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/MultiStreamableMessageSourceTest.java
If you called `peek()` on a `MultiStreamableMessageSource`, then called `nextAvailable()` twice, the first `nextAvailable()` would give you the peeked event, and the second call would give you the next available event. But if the two events were from different underlying message sources, the tracking token update from the first event would be discarded. If you then released the segment and let another node claim it, the other node would have no way of knowing that the peeked event had already been consumed, and would deliver it again.
=> Fix peek-then-consume in MultiStreamableMessageSource

config/src/main/java/org/axonframework/config/EventProcessingConfigurer.java, config/src/main/java/org/axonframework/config/EventProcessingModule.java, config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java, messaging/src/main/java/org/axonframework/eventhandling/SubscribingEventProcessor.java
Instead of having a hard-coded default (the Event Bus), one can now
configure the default message source for Tracking or Subscribing
processors.
=> Allow the default message source to be configured

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/CommandSerializer.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/QuerySerializer.java, messaging/src/main/java/org/axonframework/commandhandling/callbacks/FutureCallback.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/ReplyMessage.java, messaging/src/main/java/org/axonframework/commandhandling/gateway/CommandGatewayFactory.java, messaging/src/main/java/org/axonframework/commandhandling/gateway/DefaultCommandGateway.java, messaging/src/main/java/org/axonframework/messaging/GenericResultMessage.java, messaging/src/main/java/org/axonframework/messaging/HandlerExecutionException.java, messaging/src/main/java/org/axonframework/messaging/ResultMessage.java, messaging/src/test/java/org/axonframework/commandhandling/callbacks/FutureCallbackTest.java, messaging/src/test/java/org/axonframework/commandhandling/gateway/CommandGatewayFactoryTest.java, messaging/src/test/java/org/axonframework/commandhandling/gateway/DefaultCommandGatewayTest.java
Exceptions are reported as part of the ReplyMessage. This Message now
exposes ExceptionDetails explicitly.
FutureCallback now just completes successfully with a message, even if
that message contains an exception result.
Gateways now throw exceptions related to timeout and interrupts instead
of returning null.
=> Improved exception handling in (non-AxonServer) distributed scenarios

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java, disruptor/src/main/java/org/axonframework/disruptor/commandhandling/DisruptorCommandBus.java, disruptor/src/test/java/org/axonframework/disruptor/commandhandling/DisruptorCommandBusTest.java, messaging/src/main/java/org/axonframework/commandhandling/AsynchronousCommandBus.java, messaging/src/main/java/org/axonframework/commandhandling/CommandBus.java, messaging/src/main/java/org/axonframework/commandhandling/SimpleCommandBus.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/DistributedCommandBus.java, messaging/src/test/java/org/axonframework/commandhandling/SimpleCommandBusTest.java, messaging/src/test/java/org/axonframework/commandhandling/distributed/DistributedCommandBusTest.java
The default command callback is used when a fire-and-forget dispatch
method is used.
=> Added ability to configure default command callback

test/src/main/java/org/axonframework/test/utils/CallbackBehavior.java
Its Javadoc says callbacks can throw checked exceptions, but the method
declaration doesn't allow them.
=> Allow checked exceptions from CallbackBehavior

messaging/src/main/java/org/axonframework/eventhandling/MultiSourceTrackingToken.java, messaging/src/test/java/org/axonframework/eventhandling/MultiSourceTrackingTokenTest.java
On an empty event store, a constituent in `MultiSourceTrackingToken`
can be null. This causes NPE to be thrown if the `covers()` method is
called. Resetting the tokens on a tracking event processor can trigger
the exception.
=> Fix NPE in MultiSourceTrackingToken.covers()

legacy/src/main/java/org/axonframework/commandhandling/model/AggregateScopeDescriptor.java, legacy/src/main/java/org/axonframework/eventsourcing/eventstore/GapAwareTrackingToken.java, legacy/src/main/java/org/axonframework/eventsourcing/eventstore/GlobalSequenceTrackingToken.java, legacy/src/test/java/org/axonframework/eventsourcing/eventstore/GapAwareTrackingTokenTest.java, legacy/src/test/java/org/axonframework/eventsourcing/eventstore/GlobalSequenceTrackingTokenTest.java, messaging/src/main/java/org/axonframework/eventhandling/GapAwareTrackingToken.java
The legacy tracking tokens provided in the `axon-legacy` module provide the means to deserialize Axon 3.x tokens into Axon 4.x tokens. However, the current implementation only works for Java and XStream serialized tokens and not for Jackson variants.
This PR adjusts the legacy tokens such that the `JacksonSerializer` can also deserialize old version towards the new implementation.
More specifically, this PR provides adjustments for the legacy `GapAwareTrackingToken` and the `GlobalSequenceTrackingToken`.
This PR resolves #1230.
=> [#1230] Make Legacy TrackingTokens deserializable by Jackson

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/EventBuffer.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/EventBufferTest.java
This PR adds a polling time to the `EventBuffer`, used during the `EventBuffer#hasNextAvailable(int, TimeUnit)` method to ensure nobody accidentally performs said call that'll block for the given duration. 
This would indefinite blocking would occur if the timeout is long **and** the `EventBuffer#fail(RuntimeException)` is issued (typically because the connection to Axon Server is broken). 
The `EventBuffer#nextAvailable()` operation for example calls `EventBuffer#hasNextAvailable(int, TimeUnit)` with `Integer.MAX_VALUE`, thus potentially blocking  they entire `EventBuffer` in case of a failure. 
Specifically, the `EventBuffer` now has a `pollingTimeMillis` field, defaulted to 500ms, which will be used to periodically block the polling operation, which will make the buffer re-enter the …
=> Add a polling time to the EventBuffer

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/GrpcMetaDataAwareSerializer.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/QueryResult.java
This PR fixes AxonDB / AxonServer related typos in Javadoc.
A couple of places had AxonDB instead of AxonServer in the Javadoc, this change will update it to AxonServer.
=> Fix Javadoc typos

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/EventStoreImpl.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/ConcatenatingDomainEventStreamTest.java
When using the AxonServer Connector, and upcasting a single entry into
multiple entries, only the first of these entries was taken into account. This PR fixes that.
Resolves #1263
=> Fix issue where not all upcast results were taken into account

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JdbcAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaAutoConfiguration.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JdbcAutoConfigurationTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JpaAutoConfigurationTest.java
The `SQLErrorCodesResolver` bean creation method wrongfully resides in the `JdbcAutoConfiguration`, whilst it's a JPA specific implementation. 
This PR moves that method should towards the `JpaAutoConfiguration`. 
Additionally, the tests are updated accordingly, as well as some Javadoc and copyright notice updates
This PR resolves bug #1279
=> [#1279] JdbcAutoConfiguration depends on JPA persistence API

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java, config/src/main/java/org/axonframework/config/AggregateConfigurer.java, config/src/test/java/org/axonframework/config/AggregateConfigurerTest.java, messaging/src/main/java/org/axonframework/commandhandling/CommandBus.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/CommandBusConnector.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/DistributedCommandBus.java, messaging/src/main/java/org/axonframework/messaging/Distributed.java, messaging/src/test/java/org/axonframework/commandhandling/distributed/DistributedCommandBusTest.java
The `AggregateConfigurer` only checked whether the `Configuration#commandBus` instance was of type `DisruptorCommandBus`. In that case, the `DisruptorCommandBus` would be used to create the Aggregate's `Repository`. 
However, if the `DisruptorCommandBus` is the local segment when an `AxonServerCommandBus` or  `DistributedCommandBus` is used, then it would not be used by the `AggregateConfigurer` is it didn't check the local segment's instance type.
This is resolved in this PR, by adding a `CommandBus#localSegment` method which is called in the `AggregateConfigurer`.
This PR resolve bug #874
=> [#874] Use DisruptorCommandBus as Local Segment to create Repositories

messaging/src/main/java/org/axonframework/eventhandling/AbstractEventBus.java, messaging/src/test/java/org/axonframework/eventhandling/AbstractEventBusTest.java
The SimpleEventBus used a Stream to create a MessageMonitorCallback for each published message. Due to the lazy initialization of streams, this caused the messages to only be marked as "ingested" by the time they we actually dispatched. For monitors performing timing, it may seem that the publication of messages is done in near-0 time.
This commit fixes that, ensuring messages are marked as ingested as soon as they arrive on the Event Bus, and marked as completed (or failed) when the Unit of Work is committed.
=> Fixed timing of message monitor on the SimpleEventBus

messaging/src/main/java/org/axonframework/deadline/quartz/DeadlineJob.java, messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java, messaging/src/test/java/org/axonframework/deadline/quartz/DeadlineJobDataBinderTest.java, messaging/src/test/java/org/axonframework/eventhandling/scheduling/quartz/DirectEventJobDataBinderTest.java
Converting timestamp represented by `Instant` to `Long` using `.toEpochMillis()` loses timestamp precision. Injecting such timestamp using `@Timestamp` to `@DeadlineHandler` may cause unpredicted behavior.
This PR translates timestamp using `Instant.toString()`. When reading timestamp it attempts both old way `Long` and new way `String`. Thus change is non intrusive.
This pull request resolves issue #1302
=> Store message timestamp as string in JobData

spring-boot-autoconfigure/src/main/resources/application-disable-axon-server.properties
This should be enough to fulfill #1247 
By running the app with `-Dspring.profiles.active=disable-axon-server`(or using ENV, ...)
The application properties will be loaded and thus the autoconfiguration of axon server connector will be excluded from the context.
This allows to switch between axon-Server (prod) and local eventStore (test, dev) by adding a profile and do not require excluding the dependency from the starter.
=> Profile configuration to disable-axon-server

test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java, test/src/main/java/org/axonframework/test/aggregate/FixtureConfiguration.java, test/src/main/java/org/axonframework/test/saga/FixtureConfiguration.java, test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java, test/src/test/java/org/axonframework/test/aggregate/AnnotatedAggregate.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_RegisteringMethodEnhancements.java, test/src/test/java/org/axonframework/test/aggregate/ParameterResolvedEvent.java, test/src/test/java/org/axonframework/test/aggregate/ResolveParameterCommand.java, test/src/test/java/org/axonframework/test/saga/FixtureTest_RegisteringMethodEnhancements.java, test/src/test/java/org/axonframework/test/saga/ParameterResolvedEvent.java, test/src/test/java/org/axonframework/test/saga/ResolveParameterCommand.java, test/src/test/java/org/axonframework/test/saga/StubSaga.java
This pull request introduces the `registerParameterResolverFactory(ParameterResolverFactory)` method to the `AggregateTestFixture` and `SagaTestFixture` classes. Doing so allows an easy handle for users to register custom `ParameterResolverFactories` they might have added to their project.
Next to providing test cases for the added functionality, IDE warnings in the touched classes have been resolved.
This pull request resolves #1050
=> [#1050] Register Parameter Resolvers in Test Fixtures

test/src/main/java/org/axonframework/test/aggregate/ResultValidator.java, test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java, test/src/main/java/org/axonframework/test/saga/FixtureExecutionResult.java, test/src/main/java/org/axonframework/test/saga/FixtureExecutionResultImpl.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_Deadlines.java, test/src/test/java/org/axonframework/test/saga/FixtureTest_Deadlines.java
This pull request introduces two methods to both the `AggregateTestFixture` and `SagaTestFixture` validation phase:
1. `expectScheduledDeadlineWithName(Duration duration, String deadlineName)`
2. `expectScheduledDeadlineWithName(Instant scheduledTime, String deadlineName)`
This methods are beneficial to include, as users are able to schedule deadlines without any form of payload, but with a _deadline name_. In those scenarios, one would still want to verify through test cases if such a deadline was scheduled.
Alongside this addition, I've resolved warnings I encountered in the touched files.
This pull request resolves #680
=> [#680]  Expect Scheduled Deadline based on Deadline name

test/src/main/java/org/axonframework/test/saga/FixtureConfiguration.java, test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java, test/src/main/java/org/axonframework/test/utils/AutowiredResourceInjector.java, test/src/test/java/org/axonframework/test/saga/FixtureTest_RegisteringSagaEnhancements.java
This pull request introduces the `SagaTestFixture#registerResourceInjector(ResourceInjector)` method, which allows the registration of custom `ResourceInjector` instances a user might have defined in their application.
To keep supporting the fixtures `SagaTestFixture#registerResource(Object)` and `SagaTestFixture#withTransienceCheckDisabled` methods, we have decided that the `registerResourceInjector(ResourceInjector)` *does not* replace the fixtures default `ResourceInjector`. Instead, the registered custom injector is paired with the default provided in the fixture. Firstly, the default will be called for resource injection and secondly the custom one.
Through this approach we ensure that `registerResource` and `withTransienceCheckDisabled` work as intended, whilst the …
=> [#894] Add registerResourceInjector method to SagaTestFixture

messaging/src/main/java/org/axonframework/serialization/upcasting/event/EventTypeUpcaster.java, messaging/src/test/java/org/axonframework/serialization/upcasting/event/EventTypeUpcasterTest.java
On the user group a [request](https://groups.google.com/forum/#!topic/axonframework/jyg73R-2sXU) came in for insights into an upcaster which purely allowed for upcasting the event type. From the pseudo code I provided in, I went further and drafted an actual implementation.
Thus, this pull request introduced the `EventTypeUpcaster`. This is an implementation of the
`SingleEventUpcaster`, which in the constructor requires the expected and upcasted payload type / revision.
The `SingleEventUpcaster#canUpcast(IntermediateEventRepresentation)` and `SingleEventUpcaster#doUpcast(IntermediateEventRepresentation)` call `protected` methods, which allow for more fine grained control by the end user.
=> Introduce an EventTypeUpcaster

messaging/src/main/java/org/axonframework/common/BuilderUtils.java, messaging/src/main/java/org/axonframework/serialization/upcasting/event/EventTypeUpcaster.java, messaging/src/test/java/org/axonframework/common/BuilderUtilsTest.java, messaging/src/test/java/org/axonframework/serialization/upcasting/event/EventTypeUpcasterTest.java
This pull request introduces a static `EventTypeUpcaster#from(String, String)` and `EventTypeUpcaster.Builder#to(String, String)` method to allow creation of an `EventTypeUpcaster`.
This builder approach looks cleaner from a usage perspective then the constructor of the `EventTypeUpcaster`. I've also provided a `from(Class, String)` and `to(Class, String)` method, which will use the fully qualified class name of the given class as the expected/upcasted payload type of the `EventTypeUpcaster`.
Lastly, I've added the `assertNonEmpty(String, String)` method to the `BuilderUtils` class, as I wanted to assure the given payload type is non null and empty at all times.
=> EventTypeUpcaster Builder

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/AxonServerSubscriptionQueryResult.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/FlowControllingStreamObserver.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConfigurationTest.java
We would like to separate the flow control settings for each message type. This way we can use the flow control for back-pressure control of commands to a certain component, while letting it accepting the events with a greater (default settings) flow. The handing of commands in this component is far more time consuming than the event handling.
=> Flow control per message type

test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_StateStorage.java, test/src/test/java/org/axonframework/test/aggregate/HardToCreateResource.java
The `InMemoryRepository` used in the `AggregateTestFixture` for state-stored aggregate testing did not utilize any of the resources added through `AggregateTestFixture#registerInjectableResource(Object)`.
This followed from the fact that the `AggregateModel` created in the `InMemoryRepository` used the default `ParameterResolverFactory` instead of the one registered in the `AggregateTestFixture` which includes the registered resource.
Added, the registered `HandlerDefinition`/`HandlerEnhancerDefinition` was also not taken into account by the `InMemoryRepository`.
To thus resolve this bug, I've simply added the `ParameterResolverFactory` and `HandlerDefinition` to the `InMemoryRepository` which did the trick.
This issue resolves #1219
=> [#1219] Allow resource injection for State-Stored Aggregates

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaAutoConfiguration.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JpaAutoConfigurationLazySagaStoreTest.java
Currently the `JpaSagaStore` will eagerly create named queries for the `saga_entry` table. 
However, if the `saga_entry` entity is not required/desired, this approach will still enforce it being available. 
Changing this behavior to lazily initialize, by adding `@Lazy` to the `JpaSagaStore` bean creation method will allow ignoring the `saga_entry` entity altogether.
This pull request is a follow up from [this](https://groups.google.com/forum/#!topic/axonframework/VnCsbuMt0FU) user group issue.
=> Lazily initialize the JpaSagaStore

messaging/src/main/java/org/axonframework/common/caching/Cache.java, messaging/src/main/java/org/axonframework/common/caching/EhCacheAdapter.java, messaging/src/main/java/org/axonframework/common/caching/JCacheAdapter.java, messaging/src/main/java/org/axonframework/common/caching/WeakReferenceCache.java
The `Cache` interface utilizes unnecessary generics for the `put`, `putIfAbsent`, `remove` and `containsKey` methods. 
This pull request replaces those generics for `Object` instead, to simplify the `Cache` interface.
The implementation `EhCacheAdapter`, `JCacheAdapter` and `WeakReferenceCache` have been adjusted accordingly too.
This pull request resolves #1311
=> [#1311] Remove unnecessary use of generics in Cache

integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java, messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
This PR adds a rethrow of the exception caught in the `TrackingSegmentWorker` after the `TrackingEventProcessor` it's state has been set to `PAUSED_ERROR`.
As such this pull request resolves #1212
=> [#1212] TrackingProcessor should rethrow exceptions when shutting down in error state

messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
On our project, we are moving from MariaDB to CockroachDB. While migrating our code, we saw a lot of `Fetch Segments for Processor: ...` errors, with no further explanation. We were unable to figure out what the problem was without access to the underlying exception, which was not logged. With the modification proposed in this PR, the underlying issue was immediately clear: a silly casing issue in our SQL scripts. (CockroachDB is case sensitive, MariaDB is not.)
I'm opening this PR because I think it can be valuable for others as well to be able to see the underlying issue to this class of errors. I've set it to the "DEBUG" level because it's probably too chatty if it  were logged all of the time. This way users can opt-in to this message.
=> Adds debug logging for thrown exception

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java, spring-boot-autoconfigure/src/main/resources/application-disable-axon-server.properties, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfigurationTest.java
This PR introduces the ability to define a Spring property that disables AutoConfiguration for the AxonServer connector altogether. When set, none of the autoconfigured beans related to the AxonServer Connector is configured.
=> Allow disabling AxonServer AutoConfiguration through property

eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/ConcatenatingDomainEventStream.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/ConcatenatingDomainEventStreamTest.java
Apply changes to ConcatenatingDomainEventStream and delegate sequence number calculation to delegates.
=> [#1320] Do not miss sequence number if last event is filtered

modelling/src/main/java/org/axonframework/modelling/saga/repository/jdbc/JdbcSagaStore.java, modelling/src/test/java/org/axonframework/modelling/saga/repository/jdbc/JdbcSagaStoreTest.java
Updated `JdbcSagaStore` so it does not persist the saga when an update fails.
Inspired by this Axon google group question: https://groups.google.com/forum/#!topic/axonframework/xAiMAmsbgiE
Currently the `JdbcSagaStore` persists a saga if an update fails, but it seems like it should do nothing when this occurs which would be consistent with the `JpaSagaStore`.
=> JdbcSagaStore should not insert Saga after zero updates

axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/grpc/FakeEventTrackerStatus.java, integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java, messaging/src/main/java/org/axonframework/eventhandling/EventTrackerStatus.java, messaging/src/main/java/org/axonframework/eventhandling/ReplayToken.java, messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java, messaging/src/test/java/org/axonframework/eventhandling/ReplayTokenTest.java
This PR will solve issue #1252 
User can now have more information on an ongoing reply token status, knowing the estimated position of current replay token and the reset token position until the replay will be processed.
=> [#1252] Expose token replay info in EventTrackerStatus

integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java, messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
The previous default of storing tokens before processing (which is a performance improvement), is only valid when event handling is executed in a transaction. Therefore, when configuring the NoTransactionManager, the default behavior should be to claim tokens at the start, and update them after processing a batch. For other TransactionManager implementations, the default remains to store tokens before processing.
This pull request resolves #1220
=> Make default "storeTokenAfterProcessing" value depend on TransactionManager

messaging/src/main/java/org/axonframework/serialization/AbstractXStreamSerializer.java, messaging/src/main/java/org/axonframework/serialization/json/JacksonSerializer.java, messaging/src/main/java/org/axonframework/serialization/xml/XStreamSerializer.java, messaging/src/test/java/org/axonframework/serialization/json/JacksonSerializerTest.java, messaging/src/test/java/org/axonframework/serialization/xml/XStreamSerializerTest.java
This PR adds a method to the builders of the XStreamSerializer and JacksonSerializer that instructs them to be lenient towards missing properties when deserializing into Java Objects.
For distributed systems, lenience is considered good practice, as it allows producers to make slight changes to the serialized structure, without impacting consumers of these messages.
=> Easier configuration of lenient serialization

spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java, spring/src/test/java/org/axonframework/spring/AggregatePolymorphismTest.java
Without this change, it won't be possible to configure a spring component name for aggregate.
=> Consider top aggregate prototype when looking for aggregate spring bean.

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/DistributedCommandBusProperties.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/EventProcessorProperties.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/MetricsProperties.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/SerializerProperties.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaEventStoreAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/MetricsAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/TransactionAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/util/AbstractQualifiedBeanCondition.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/util/ConditionalOnMissingQualifiedBean.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/util/ConditionalOnQualifiedBean.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/util/jpa/ContainerManagedEntityManagerProvider.java
I found a few cases where the apache license had been duplicated in the file headers. I also found a case where a file didn't have the license in its header.
This PR cleans up the aforementioned cases. 
It does look like the years are inconsistent, however. For example, some say 2010-2017, 2010-2018 etc etc. I would more than happy to update them all to say 2020 if that would be beneficial. 
Cheers
=> Remove duplicate Apache license in headers and add a missing one

modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java, test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CreateOrUpdate.java
Adjusted the `AggregateTestFixture` `Repository` implementations, as well as adding some test cases to verify their correct behavior. 
Additionally, made a change to solves #1353: the assert performed on the `Aggregate#indentfier` wasn't performed on the `toString()` result, whilst that's what a `VersionedAggregateIdentifier` will **always** return. As such, this PR also resolves #1353.
=> [#1353] AggregateTestFixture load-or-create impl. and adjusted Aggregate Identifier assertion

eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/MysqlJdbcEventStorageEngineTest.java, pom.xml
This PR changes the `mysql-connector-java` version from 5.1.31 to 8.0.19 to resolve a "common vulnerabilities and exposures) somewhere down the call hierarchy, as mentioned in #1365.
As such, this pull request resolves #1365
=> [#1365] Adjust mysql-connector-java

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/DistributedCommandBus.java, messaging/src/main/java/org/axonframework/lifecycle/Phase.java
This pull request resolves a number of issues around the shutdown order process, being:
- Ensure the instruction streams are closed on the `AxonServerConnectionManager`.
- Switch around the "inbound" and "outbound" command-/query-connector phases, value wise. These were accidentally the wrong way around.
- Move the `Phase#OUTBOUND_EVENT_CONNECTORS` to -10
- Move the command/query Executor `disconnect()` call from the inbound to the outbound phase. The inbound shutdown handler should _only_ remove message handler registration from the outside world.
- Adjust the way handlers are removed/unregistered from the `AxonServerCommandBus` and `AxonServerQueryBus`, to ensure those operations aren't sent twice.
=> Several minor resolution around Shutdown Order

modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CreateOrUpdate.java
As @domaincomponents rightfully pointed out in #1356, using the `CreationPolicy` annotation with `AggregateCreationPolicy.ALWAYS` caused a `NullPointerException`. 
This occurred because we assumed the usage of a `AggregateConstructorCommandHandler` which (logically) doesn't use an existing aggregate instance. However, further down a check was made whether the executable (i.e. the command handling function) was a of type method. In the described scenario this was the case and hence an existing aggregate instance was expected.
This PR solves the problem by _only_ using the `AggregateConstructorCommandHandler` if the command handler annotation specifies it's a factory method. If this isn't the case, then an else block is in control of the switch case over the possible creation policies. …
=> [#1356] Support CreationPolicy Always on methods

messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspector.java, messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedMessageHandlingMember.java, messaging/src/main/java/org/axonframework/messaging/annotation/HandlerComparator.java, messaging/src/main/java/org/axonframework/messaging/annotation/MessageHandlingMember.java, messaging/src/test/java/org/axonframework/messaging/annotation/HandlerComparatorTest.java
Mainly the explicit priority of handlers must be taken into account before looking at payload types or parameter count. This allows handlers for specific Message types to be evaluated before handlers of more generic Message types.
=> Changes to ensure certain handlers take priority over others

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java
Set stream observer to `null` on error, which fixes resubscribe on `RESOURCE_EXHAUSTED` exception.
This pull request resolves #1384.
=> Fix resubscribe of Query Handlers on Resource Exhausted exception

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/UpstreamAwareStreamObserver.java
Keeping the request stream alive may lead to memory leak.
=> Complete request stream when response stream completes or errors

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JdbcAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaEventStoreAutoConfiguration.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JdbcAutoConfigurationTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JpaEventStoreAutoConfigurationWithoutAxonServerTest.java
When explicitly defining an EventBus in the configuration, that should be interpreted as an attempt to suppress Event Sourcing.
Resolves #1395
=> Removed autoconfiguration of EventStore when EventBus is present

spring/src/main/java/org/axonframework/spring/config/AbstractAnnotationHandlerBeanPostProcessor.java
Axon's spring BeanPostProcessor doesn't tolerate null BeanFactories.
In conjunction with spring-cloud-aws-autoconfigure it breaks entire application boot.
The culprit is null BeanFactory returned from @Bean method. Code is here: https://github.com/spring-cloud/spring-cloud-aws/blob/v2.2.1.RELEASE/spring-cloud-aws-autoconfigure/src/main/java/org/springframework/cloud/aws/autoconfigure/context/ContextStackAutoConfiguration.java#L80
As a result `org.axonframework.spring.config.AbstractAnnotationHandlerBeanPostProcessor#postProcessAfterInitialization` gets `org.springframework.beans.factory.support.NullBean` instance and on `beanFactory.isSingleton(beanName)` throws exception.
`org.axonframework.spring.config.AbstractAnnotationHandlerBeanPostProcessor#postProcessAfterInitialization` Produces …
=> Fixed exception occurring with BeanFactory that is null

messaging/src/main/java/org/axonframework/eventhandling/MultiSourceTrackingToken.java, messaging/src/test/java/org/axonframework/eventhandling/MultiSourceTrackingTokenTest.java
Handled null for empty streams as members of the MultiSourceTrackingToken.
Affected operations position/upperBound/lowerBound.
This PR resolves #1398.
=> Prevent null pointer exception in MultiSourceTrackingToken

messaging/src/main/java/org/axonframework/messaging/GenericMessage.java, messaging/src/main/java/org/axonframework/queryhandling/QueryGateway.java, messaging/src/main/java/org/axonframework/queryhandling/QueryMessage.java, messaging/src/test/java/org/axonframework/messaging/GenericMessageTest.java, messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryGatewayTest.java, messaging/src/test/java/org/axonframework/queryhandling/GenericQueryMessageTest.java
The `QueryGateway` recently received an adjustment which allowed the usage of `Message` instances for the `query` parameter. This was introduced to support addition of `MetaData` directly on the `QueryGateway`.
Due to this adjustment, some of the `default` `QueryGateway` methods now set the `queryName` parameter to the outcome of `Message.class.getName()`. As `Message` would (very likely) never be the desired `queryName`, this behaviour should be adjusted to verify whether the given `query` parameter is an instance of `Message`.
That's exactly what this pull request introduces. For this, a static method has been included in the `GenericMessage` class, which validates whether a given object is the payload or a message.
In case of the former, `payload.getClass().getName()` will be …
=> Adjust retrieval of Query Name in the QueryGateway

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java, config/src/main/java/org/axonframework/config/EventProcessingModule.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/HandlerEnhancerDefinitionConfigurationTest.java
When creating the `SimpleEventHandlerInvoker`, the `EventProcessingModule` did not include the `HandlerDefinition` from the given `Configuration`. As such, the `AnnotationEventHandlerAdapter` created through the `SimpleEventHandlerInvoker.Builder` defaulted to the `ClasspathHandlerDefinition#forClass` output.
Due to this, `Handler(Enhancer)Definition` beans in a Spring (Boot) context would never be taken into account if a component would only contain `@EventHandler` annotated methods.
This PR resolves that by providing the `HandlerDefinition` from the `Configuration` (potentially) based on the `ClassLoader` of the first event handling component.
This pull request resolves #1407
=> [#1407] Handler(Enhancer)Definition beans not taken into account

eventsourcing/src/main/java/org/axonframework/eventsourcing/MultiStreamableMessageSource.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/MultiStreamableMessageSourceTest.java
A situation was reported where a Tracking Processor did not catch up with the last event, until a new event was available after that event. Effectively causing it to read up to N-1. 
When using peek() to look at the next message, that message was taken into account when calling nextAvailable(), but not when using hasNextAvailable, with or without timeout. This causes tracking processors to only process a message when a new message was appended after that.
=> Fix in hasNextAvailable returning false when last message was peek()-ed.

messaging/src/main/java/org/axonframework/serialization/json/JacksonSerializer.java, messaging/src/test/java/org/axonframework/serialization/json/JacksonSerializerTest.java, pom.xml
As pointed out in issue #1418 (and several others), returning a `List` of complex objects as a result of a `@QueryHandler` annotated method will result in receiving a `ArrayList` containing `LinkedHashMap` instances instead of the expected Query Response.
This follows from the fact that the `ObjectMapper` can not deduce the type required within the collection, which can be resolved by adding type information upon serialization.
Although configurable on the `ObjectMapper` somebody would use for the `JacksonSerializer`, I think it's beneficial to allow configuration of default type information directly on the `JacksonSerializer` instead. This is inline with the already present `JacksonSerializer.Builder#lenientSerialization` method.
This pull request introduce just such a functionality, …
=> [#1418] Allow activation of default type information on the JacksonSerializer

spring/src/main/resources/META-INF/spring-devtools.properties
This pull request fine tunes the `spring-devtools.properties` file, by adjusting the included modules for restart. After local testing (at this stage uncertain how to provide test cases for this) it showed that [Spring Boot Devtools](https://docs.spring.io/spring-boot/docs/1.5.16.RELEASE/reference/html/using-boot-devtools.html) threw exceptions if any of the added jars was not included for restart.
With the adjustments in place, all worked as desired.
This pull request resolves #1382
=> [#1382] Support Spring Boot DevTools

test/src/main/java/org/axonframework/test/saga/EventValidator.java, test/src/test/java/org/axonframework/test/saga/FixtureExecutionResultImplTest.java
This makes the behavior of events consistent with the behavior of commands in the saga test fixture. The change here mirrors the implementation of `CommandValidator.startRecording()`.
Fixes #1436
=> Clear previous events when saga test fixture starts recording

eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java
When moving to Java 11, we noticed that XStream causes some warnings as it does some illegal reflection. [This is their issue on the topic](https://github.com/x-stream/xstream/issues/101), however it's unlikely to be fixed properly anytime soon. 
We would like to exclude XStream as a dependancy which is not possible at the moment as the `AbstractEventStorageEngine.Builder` uses the XStreamSerialiser as the default when it's constructed. Moving this to the `validate()` method means that we can use the Jackson serialiser without needing to keep XStream as a required dependency.
=> Move the assignment of the defaults for the AbstractEventStorageEngine.Builder to the validate method.

config/src/main/java/org/axonframework/config/AggregateConfiguration.java, config/src/main/java/org/axonframework/config/AggregateConfigurer.java, config/src/main/java/org/axonframework/config/Configuration.java, config/src/main/java/org/axonframework/config/DefaultConfigurer.java, config/src/test/java/org/axonframework/config/AggregateConfigurerTest.java
This pull request allows easier retrieval of the `AggregateFactory` by opening it up on the `AggregateConfiguration` class. This is for example use full if a user needs to create a `Snapshotter` instance, for which the `AggregateFactory` should be provided.
=> Allow easier retrieval of the AggregateFactory

config/src/main/java/org/axonframework/config/Configuration.java, config/src/main/java/org/axonframework/config/Configurer.java, config/src/main/java/org/axonframework/config/DefaultConfigurer.java, config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java
Currently, only the Spring auto configuration provides a `Snapshotter` instance (the `SpringAggregateSnapshotter`) out of the box. The main Configuration API doesn't provide anything of the sort.
This is resolved in this pull request, by expanding the `Configurer` with a `configureSnapshotter (Function<Configuration, Snapshotter>)` method. The `Configuration` in turn has received a `snapshotter` method, returning the `Component` containing a `Snapshotter` implementation.
The `DefautlConfigurer` will default to an `AggregateSnapshotter` instance.
=> Dedicated Snapshotter Configuration

eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/AbstractEventTableFactory.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/AppendEventsStatementBuilder.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/AppendSnapshotStatementBuilder.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/JdbcEventStorageEngineStatements.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/statements/TimestampWriter.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngineTest.java
Used when writing timestamps to both event- and snapshot-tables.
Fixes #1453 .
=> [#1453] Add TimestampWriter to facilitate writing timestamp as sql-timestamp

config/src/main/java/org/axonframework/config/DefaultConfigurer.java, metrics-micrometer/src/main/java/org/axonframework/micrometer/CapacityMonitor.java, metrics-micrometer/src/main/java/org/axonframework/micrometer/EventProcessorLatencyMonitor.java, metrics-micrometer/src/main/java/org/axonframework/micrometer/GlobalMetricRegistry.java, metrics-micrometer/src/main/java/org/axonframework/micrometer/MessageCountingMonitor.java, metrics-micrometer/src/main/java/org/axonframework/micrometer/MessageTimerMonitor.java, metrics-micrometer/src/main/java/org/axonframework/micrometer/MetricsConfigurerModule.java, metrics-micrometer/src/main/java/org/axonframework/micrometer/PayloadTypeMessageMonitorWrapper.java, metrics-micrometer/src/main/java/org/axonframework/micrometer/TagsUtil.java, metrics-micrometer/src/test/java/org/axonframework/micrometer/CapacityMonitorTest.java, metrics-micrometer/src/test/java/org/axonframework/micrometer/EventProcessorLatencyMonitorTest.java, metrics-micrometer/src/test/java/org/axonframework/micrometer/GlobalMetricRegistryTest.java, metrics-micrometer/src/test/java/org/axonframework/micrometer/MessageCountingMonitorTest.java, metrics-micrometer/src/test/java/org/axonframework/micrometer/MessageTimerMonitorTest.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/MetricsProperties.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/MicrometerMetricsAutoConfiguration.java
All Axon monitors have been changed to use tags that enable `dimensionality`.
By default, the message `palyoadType` is a tag for every metric. One can add/configure metrics with custom Tags/Dimensions (for example, from message metadata) as well.
Before this change, the axon-micrometer was `hierarchical`, which means it only supported a flat metric name.
=> Axon Micrometer with Tags/Dimensions

modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CreationPolicy.java
The `AggregateCreationPolicy#ALWAYS` on a command handler will currently ensure that the result of command handling will be the aggregate identifier. Thus similar to a command handling constructor. 
It however makes sense to place the annotation `@CreationPolicy(ALWAYS)` on a method with a specific return type, expecting the user specified returned result to be the command handling result.
This PR ensures that this is the behavior of a command handling function annotated with `@CreationPolicy(ALWAYS)`.
When a return value is given on such a method, it will be the result of command handling.
If none is provided, it will default to the aggregate identifier.
=> Allow specific return types on creation policy always

messaging/src/main/java/org/axonframework/common/ObjectUtils.java, messaging/src/main/java/org/axonframework/common/jdbc/JdbcUtils.java, messaging/src/main/java/org/axonframework/eventhandling/tokenstore/AbstractTokenEntry.java, messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStore.java, messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStore.java, messaging/src/test/java/org/axonframework/common/ObjectUtilsTest.java, messaging/src/test/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStoreTest.java
This pull request adjusts the `TokenStore#storeToken(TrackingToken, String, int)` method for both the `JpaTokenStore` and the `JdbcTokenStore`. The current implementation first does a fetch, trying to achieve a token claim if necessary, and only after that the token entry is updated. 
Although this works, we can optimize this process by doing an `UPDATE` query instead, which is exactly what this PR provides. If the `UPDATE` query yielded zero updates, we move back to the old process of load-then-save.
This pull request resolves #1442.
=> [#1442] Use UPDATE query on storing a token

axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/grpc/FakeEventTrackerStatus.java, integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java, messaging/src/main/java/org/axonframework/eventhandling/AddedTrackerStatus.java, messaging/src/main/java/org/axonframework/eventhandling/EventTrackerStatus.java, messaging/src/main/java/org/axonframework/eventhandling/EventTrackerStatusChangeListener.java, messaging/src/main/java/org/axonframework/eventhandling/RemovedTrackerStatus.java, messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java, messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessorConfiguration.java, messaging/src/main/java/org/axonframework/eventhandling/WrappedTrackerStatus.java, messaging/src/test/java/org/axonframework/eventhandling/AddedTrackerStatusTest.java, messaging/src/test/java/org/axonframework/eventhandling/EventTrackerStatusChangeListenerTest.java, messaging/src/test/java/org/axonframework/eventhandling/EventTrackerStatusTest.java, messaging/src/test/java/org/axonframework/eventhandling/FakeEventTrackerStatus.java, messaging/src/test/java/org/axonframework/eventhandling/RemovedTrackerStatusTest.java, messaging/src/test/java/org/axonframework/eventhandling/TrackingEventProcessorConfigurationTest.java
This pull request introduces the `EventTrackerStatusChangeListener`, which is a configurable option for the `TrackingEventProcessor`.
The `EventTrackerStatusChangeListener` will react to updates of the `EventTrackerStatus` objects (used by a `TrackingEventProcessor` to portray it's status to the outside world).
Users of the `EventTrackerStatusChangeListener` functional interface can choose to react only to ` boolean` status changes like when `isReplaying`/`isMerging` turns true/false, or if they want to include the positions of the status fields as well. The latter is turned off by default, as positions will likely shift _very often_. Lastly, special cases like the removal or addition of a status object are reflected by a `RemovedTrackerStatus` and `AddedTrackerStatus` object, allowing …
=> [#1338] EventTrackerStatusChangeListener for Tracking Event Processors

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java
The new connector implementation missed the use of the `AxonServerConfiguration#isForceReadFromLeader` when opening up the event stream. This PR resolve that, and as such resolves #1486
=> [#1486] Use force read from leader property

eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/SequenceEventStorageEngine.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemoryEventStorageEngine.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SequenceEventStorageEngineTest.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemoryEventStorageEngineTest.java, integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java
This PR resolves the issue that causes a Tracking Processor to possibly restream all events from the active storage when getting to the head of the stream.
Addresses #1491
=> Fixed infinite looping issue when tracking from a SequenceEventStorageEngine

messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStore.java, messaging/src/test/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStoreTest.java, messaging/src/test/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStoreTest.java
The storeToken did an attempt to use an update query to update the token contents. An empty token was stored as an empty byte array. However, upon retrieval, there is a check for null tokens, whereas an empty byte array is seen as a regular token type.
Resolves #1495
=> Fix loading issue when updating token with null token in JpaTokenStore

messaging/src/main/java/org/axonframework/messaging/unitofwork/MessageProcessingContext.java, messaging/src/main/java/org/axonframework/messaging/unitofwork/UnitOfWork.java, messaging/src/test/java/org/axonframework/messaging/unitofwork/BatchingUnitOfWorkTest.java
For some phases, exceptions thrown by Lifecycle handler should be suppressed. These are the phases where there is no more option to trigger a rollback. Suppressing these exceptions ensures that all lifecycle handlers are invoked.
=> Suppress exceptions thrown by UnitOfWork Lifecycle handlers

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java, pom.xml
When a dispatch exception occurred on a query, the resulting exception did not report the root cause. This commit adds the root cause, if available.
=> Complete the QueryResult with the error reported by the server

messaging/src/main/java/org/axonframework/common/lock/PessimisticLockFactory.java
When executing the test case repeatedly, it would fail after a few dozen attempts with a timeout.
A shorter lockAttemptTimeout greatly reduces the time needed to detect deadlocks, which in some cases would exceed the test timeout. Together they still represent a maximum of 60 seconds.
Also suppressed a ConcurrentModificationException, which may occur while iterating over LockFactories while the GC cleans unused entries.
=> Changed default values lockAttemptTimeout and maxLockAttempts

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConnectionManagerTest.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/PlatformService.java
This pull request introduces the means to have an Axon application enable heartbeats towards the Axon Server instance it is connected with. More specifically, it uses the `AxonServerConnection` of the default context this client is a part of.
Enabling is done through the `AxonServerConfiguration.HeartbeatConfiguration`, allowing the specification to simply enable heartbeats, the interval between heartbeats and the timeout of the connection of no response is received
=> Client side Heartbeat Message enabling 

eventsourcing/src/main/java/org/axonframework/eventsourcing/AbstractSnapshotter.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/EventCountSnapshotTriggerDefinition.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/AbstractSnapshotterTest.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/EventCountSnapshotTriggerDefinitionTest.java, messaging/src/main/java/org/axonframework/eventhandling/AbstractEventBus.java
In a single UOW we should schedule at most one snapshot to be created. 
Since all Axon components use UOW to process a message and since Axon holds a lock on the aggregate we assume that scheduling a snapshot outside of UOW or from several distinct UOWs is less probable so we don't have a guard against those situations.
=> Snapshotter optimization

integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java, integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest_MultiThreaded.java, integrationtests/src/test/java/org/axonframework/integrationtests/utils/AssertUtils.java, messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
This pull request introduce a minute change in the `TrackingEventProcessor#processBatch(Segment, BlockingStream<TrackedEventMessage<?>>)` method, namely moving the private `checkSegmentCaughtUp` method until after the first `eventAvailabilityTimeout` has been triggered.
Prior to this change, there was a window of opportunity within which an opened `BlockingStream` was referred to as empty whilst in actuality events were present. This can only occur of the underlying implementation of the  `BlockingStream` gets the events pushed (e.g. Axon Server), instead of pulling them itself (e.g. the `EmbeddedEventStore`). Further more, the `checkSegmentCaughtUp` validates whether the end of the `BlockingStream` has been reached and if this was true, the `caughtUp` flag was set to true. As an empty …
=> [#1505] isCaughtUp() always returns true for pushing-"Event Streams"

metrics/src/main/java/org/axonframework/metrics/EventProcessorLatencyMonitor.java, metrics/src/test/java/org/axonframework/metrics/EventProcessorLatencyMonitorTest.java
Method getMetrics() is only invoked when registering the metric (MessageMonitor) with the registry.
That method should not be used to compute the metric value. Only the lambda value in the Map is invoked when the metric is to be reported.
=> [#1516] getMetrics is not for computation of metric

eventsourcing/src/main/java/org/axonframework/eventsourcing/AbstractAggregateFactory.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/GenericAggregateFactoryTest.java
Change Optional#orElse(...) into Optional#orElseGet(...), because it is called wether or not the optional contains a value, possibly causing problems, because it is an abstract method that we do not know the implementation of.
=> Change Optional#orElse to Optional#orElseGet invocation

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerException.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/EventBuffer.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/EventBufferTest.java
The EventBuffer would throw an exception when unable to read events from the underlying stream, but it didn't report the original exception if the stream was closed due to an error. This made debugging very hard.
This commit adds the root cause of the closed connection to the exception thrown.
=> Added root cause exception to stacktrace on error reading events

messaging/src/main/java/org/axonframework/commandhandling/distributed/CommandMessageFilter.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/commandfilter/AcceptAll.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/commandfilter/AndCommandMessageFilter.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/commandfilter/CommandNameFilter.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/commandfilter/DenyAll.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/commandfilter/DenyCommandNameFilter.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/commandfilter/NegateCommandMessageFilter.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/commandfilter/OrCommandMessageFilter.java, messaging/src/test/java/org/axonframework/commandhandling/distributed/commandfilter/AcceptAllSerializationTest.java, messaging/src/test/java/org/axonframework/commandhandling/distributed/commandfilter/AndCommandMessageFilterSerializationTest.java, messaging/src/test/java/org/axonframework/commandhandling/distributed/commandfilter/CommandFilterTest.java, messaging/src/test/java/org/axonframework/commandhandling/distributed/commandfilter/CommandNameFilterSerializationTest.java, messaging/src/test/java/org/axonframework/commandhandling/distributed/commandfilter/DenyAllSerializationTest.java, messaging/src/test/java/org/axonframework/commandhandling/distributed/commandfilter/DenyCommandNameFilterSerializationTest.java, messaging/src/test/java/org/axonframework/commandhandling/distributed/commandfilter/NegateCommandMessageFilterSerializationTest.java, messaging/src/test/java/org/axonframework/commandhandling/distributed/commandfilter/OrCommandMessageFilterSerializationTest.java
This PR adjusts the `CommandMessageFilter` implementations such that they can be de-/serialized through the `JacksonSerializer`. This wasn't in place just yet, since the filters were only ever serialized through the `XStreamSerializer` instance in for example the [`SpringCloudCommandRouter`](https://github.com/AxonFramework/extension-springcloud/blob/master/springcloud/src/main/java/org/axonframework/extensions/springcloud/commandhandling/SpringCloudCommandRouter.java). Pull request [#25](https://github.com/AxonFramework/extension-springcloud/pull/25) on the Spring Cloud Extension however opened up the configuration of the `Serializer`, essentially allowing for an unusable configuration of the `JacksonSerializer`.
To allow jackson serialization, both the `@ConstructorProperties` and …
=> [#1520] Make CommandMessageFilter implementations Jackson serializable

eventsourcing/src/main/java/org/axonframework/eventsourcing/AbstractAggregateFactory.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/AbstractAggregateFactoryTest.java
This change introduces a constructor to the `AbstractAggregateFactory` which ingest both a `Class<A>` as well as a `Set<Class<? extends A>>`. This essentially simplifies the creation of a custom `AggregateFactory` when polymorphic aggregates are being used.
This PR resolves #1518
=> [#1518] Polymorphic AbstractAggregateFactory constructor

messaging/src/main/java/org/axonframework/common/ReflectionUtils.java, messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspector.java, messaging/src/test/java/org/axonframework/common/ReflectionUtilsTest.java, messaging/src/test/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspectorTest.java, modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedAggregateMetaModelFactory.java, modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedChildEntity.java, modelling/src/main/java/org/axonframework/modelling/command/inspection/ChildEntity.java, modelling/src/test/java/org/axonframework/modelling/command/inspection/AnnotatedRootMemberAggregateMetaModelFactoryTest.java, modelling/src/test/java/org/axonframework/modelling/command/inspection/AnnotatedRootMembersAggregateMetaModelFactoryTest.java
Whenever an Aggregate class is provided which contained an hierarchy, there were possibilities that `@AggregateMember` annotated fields/methods would result in duplicate `ChildEntity` instances inside the `AggregateModel`. More specifically, this occurred if the root in the hierarchy contained the entities, whilst all other levels in the hierarchy only contained message handling functions.
The reason for this occurring turned out to be two fold:
1. The `AnnotatedAggregateModel#inspectFieldsAndMethods` methods loops over all classes found by the `AnnotatedHandlerInspector`. For the loop it however used the key set from the `AnnotatedHandlerInspector#getAllHandlers` method. Due to this it was possible that levels in the implementation hierarchy which *did not* contain any message handling …
=> Child Entities Duplicated in Aggregate Model

integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java, messaging/src/main/java/org/axonframework/eventhandling/Segment.java, messaging/src/test/java/org/axonframework/eventhandling/SegmentTest.java
The split method used to throw an `IllegalArgumentException` although it is a zero-argument method. Changed to `IllegalStateException`.
=> Segment split validation fix

messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
Fix the usage of `EventTrackerStatusChangeListener` to get all the updates, instead of miss some. The previous implementation allowed for a time window where distinct threads in the `TrackingEventProcessor` would concurrently deal with the `activeSegments` `Map`. As the implementation based itself on the entirety of the `Map`, which was *not* concurrency safe, additions/changes/removals of `EventTrackerStatus` instances could get lost. 
This pull request resolves that by focusing on the _exact_ `EventTrackerStatus` change, and validate whether that occurred. If it did, the `EventTrackerStatusChangeListener` with that single object in mind.
=> EventTrackerStatusChangeListener Invocation Fix

messaging/src/main/java/org/axonframework/eventhandling/AnnotationEventHandlerAdapter.java, messaging/src/test/java/org/axonframework/eventhandling/AnnotationEventHandlerAdapterTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/TrackingEventProcessorIntegrationTest.java
The `AnnotationEventHandlerAdapter#canHandleType` should *not* take `@ResetHandler` annotated methods into account when being invoked, because the reset handling members will only be invoked through a `EventHandlerInvoker` directly instead of as a result of general message handling.
The fact this filter was not in place was the main reason of issue #1593, which noted that events were not filtered out of the entire stream when a plain `@ResetHandler` (thus without a "reset context" as the message) was present. This occurred, since a `@ResetHandler` without any specific reset context was capable of handling _any_ type of message. Due to this no events where ever filtered out of the stream, since the framework assumed everything could be handled.
Introducing the simple filter solves the …
=> [#1593] Filter ResetHandlers from canHandleType

messaging/src/main/java/org/axonframework/eventhandling/AnnotationEventHandlerAdapter.java, messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedMessageHandlingMember.java, messaging/src/main/java/org/axonframework/messaging/annotation/MessageHandlingMember.java, messaging/src/main/java/org/axonframework/messaging/annotation/WrappedMessageHandlingMember.java, messaging/src/test/java/org/axonframework/messaging/annotation/AnnotatedMessageHandlingMemberTest.java, messaging/src/test/java/org/axonframework/messaging/annotation/HandlerComparatorTest.java, messaging/src/test/java/org/axonframework/messaging/annotation/WrappedMessageHandlingMemberTest.java, modelling/src/main/java/org/axonframework/modelling/command/inspection/ChildForwardingCommandMessageHandlingMember.java, modelling/src/test/java/org/axonframework/modelling/command/inspection/ChildForwardingCommandMessageHandlingMemberTest.java
There are several scenarios where it is beneficial to request a `MessageHandlingMember` which `Message` implementations it is capable to handle. Prior to this PR, this required either retrieval of annotations attributes or unwrapping of the `MessageHandlingMember` to validate further information. With this pull request, a `canHandleMessageType(Class<? extends Message>)` operation has been introduced which allows direct validation of the type of message it can handle.
This can be regarded as a follow up of #1593, which directly required such a validation.
=> Allow message type validation on MessageHandlingMember

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/EventStoreImpl.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java
This pull request is a resolution for two issues discovered in the `AxonServerEventStore`:
1. `MetaData` could no be serialized, because the used `Serializer` wasn't of type `GrpcMetaDataAwareSerializer`.
2. Snapshots are provided when invoking `AxonServerEventStore#readEvents` with a sequence number of 0.
---
<h4>Issue 1</h4>
Issue one has been trailed back to the invocation of `AxonIQEventStorageEngine#readEventData(String, long)`, since this operation does no ensure the event/snapshot `Serializer` which has been wrapped in a `GrpcMetaDataAwareSerializer` has been used. Due to this, the original Jackson/XStream/Custom `Serializer` would be invoked directly, which does not assume the event data to come in the form of a gRPC event.
The problem occurred because of the introduction of the …
=> [#1611] MetaData deserilization and Ignoring Snapshots on readEvents for seqNo = 0

eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemoryEventStorageEngine.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngine.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/MultiStreamableMessageSourceTest.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/EventStorageEngineTest.java
The documentation of the `StreamableMessageSource#createTokenAt(Instant)` states the following:
```
/**
* Creates a token that tracks all events after given {@code dateTime}. If there is an event exactly at the given
* {@code dateTime}, it will be tracked too.
*
* @param dateTime The date and time for determining criteria how the tracking token should be created. A tracking
*                 token should point at very first event before this date and time.
* @return a tracking token at the given {@code dateTime}, if there aren't events matching this criteria {@code
* null} is returned
* @throws UnsupportedOperationException if the implementation does not support the creation of time-based tokens
*/
```
As noted on the `@param dateTime` line, a create tracking token should point at the …
=> [#1604] Create head token if tokenAt has no result

eventsourcing/src/main/java/org/axonframework/eventsourcing/CachingEventSourcingRepository.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/CachingEventSourcingRepositoryTest.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/utils/StubAggregate.java
In a load-or-create situation, the created aggregate may not have its identifier set, yet. The CachingEventSourcingRepository would fail when attempting to add a created aggregate to the cache, if null keys are not allowed.
This commit removes the addition of entries to the cache when creating an aggregate. Instead, it relies on the entry being added when the aggregate is saved (i.e. when the unit of work is preparing for commit).
=> Fixed issue using load or create in combination with Caching repository

messaging/src/main/java/org/axonframework/messaging/NoScopeDescriptor.java, messaging/src/main/java/org/axonframework/messaging/annotation/ScopeDescriptorParameterResolverFactory.java, messaging/src/main/resources/META-INF/services/org.axonframework.messaging.annotation.ParameterResolverFactory, messaging/src/test/java/org/axonframework/messaging/annotation/ScopeDescriptorParameterResolverFactoryTest.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_ScopeDescriptor.java, test/src/test/java/org/axonframework/test/saga/FixtureTest_ScopeDescriptor.java
This pull request introduces the `ScopeDescriptorParameterResolverFactory`, which will resolve the `ScopeDescriptor` of the current `Scope` into message handling functions. This would allow for automatically resolving the `AggregateScopeDescriptor` and `SagaScopeDescriptor` (for which tests are added) since those are the only current `ScopeDescriptor` implementations.
In absence of a current `Scope`, a `NoScopeDescriptor` will be returned, as otherwise an `IllegalStateException` would be thrown from within the parameter resolver. Added, this signals users there is no scope active at that moment in time.
=> Introduce ScopeDescriptor ParameterResolver

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModule.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/AbstractRoutingStrategy.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/AnnotationRoutingStrategy.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/MetaDataRoutingStrategy.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/UnresolvedRoutingKeyPolicy.java, messaging/src/test/java/org/axonframework/commandhandling/distributed/AnnotationRoutingStrategyTest.java, messaging/src/test/java/org/axonframework/commandhandling/distributed/MetaDataRoutingStrategyTest.java, messaging/src/test/java/org/axonframework/commandhandling/distributed/UnresolvedRoutingKeyPolicyTest.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
This pull request makes a couple of arguably minor adjustments around the `RoutingStrategy` implementations provided:
- The `UnresolvedRoutingKeyPolicy` has been changed to a `RoutingStrategy`. As such, the `ERROR`, `RANDOM_KEY` and `STATIC_KEY` implementations from this enumeration are currently an actual `RoutingStrategy` implementation. This thus removes the switch-case logic present in the `AbstractRoutingStrategy`.
- The `unresolvedRoutingKeyPolicy` is adjusted towards a `fallbackRoutingStrategy`, as that's how it acted in the first place.
- The old default `fallbackRoutingStrategy` used to be `ERROR` but is adjusted towards `RANDOM_KEY`. `ERROR` made sense for applications using a single JVM `CommandBus` implementation. As the bias has switched to a distributed `CommandBus` (e.g. …
=> Routing Strategy Implementation Adjustments

metrics-micrometer/src/main/java/org/axonframework/micrometer/MessageTimerMonitor.java, metrics-micrometer/src/test/java/org/axonframework/micrometer/MessageTimerMonitorTest.java, metrics/src/main/java/org/axonframework/metrics/MessageTimerMonitor.java, metrics/src/test/java/org/axonframework/metrics/MessageTimerMonitorTest.java
This pull request makes it friendlier to adjust the `MessageTimerMonitor` for both DropWizard Metrics and Micrometer.
It does so by firstly introducing a `Builder` to both, allowing for the removal of the old constructor/builder overloading.
The DropWizard `MessageTimerMonitor` now through the builder allows a means to adjust the `Reservoir` (DropWizard) for the `Timer`. The Micrometer `MessageTimerMonitor` adds the option to configure a `UnaryOperator<Timer.Builder>` which is invoked during the creation of the `Timer`. Either solution allows for more fine-grained control over what's being monitored.
The `MessageTimerMonitor` is arguably the sole `MessageMonitor` implementation for both DropWizard Metrics and Micrometer which benefits from such an adjustment. As such this PR can be …
=> [#1402] Enhance MessageTimerMonitor customizability

test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java, test/src/main/java/org/axonframework/test/aggregate/FixtureConfiguration.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CommandInterceptors.java
The current set up of handler and dispatch interceptors within an `AggregateTestFixture` causes them to be registered twice.
Once during the `givenCommands(...)` operation and once during the `when(...)` invocation. As such, any registered interceptor will be invoked more often than desired.
This pull request resolves this issue by immediately registering any `MessageDispatchInterceptor` or `MessageHandlerInterceptor` for `CommandMessage` to the used `CommandBus` instead of on the `finalizeConfiguration()` method (which is invoked during `givenCommands(...)` and `when(...)`).
By doing so this pull request resolves #1665
=> [#1665] Resolve Duplicate Interceptor Invocations on givenCommands

eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemoryEventStorageEngine.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/inmemory/InMemoryEventStorageEngineTest.java
This pull request introduces a test case to the `InMemoryEventStoreEngineTest` to check whether on the rollback of a `UnitOfWork`, events are no stored in the `InMemoryEventStoreEngine`.
This is achieved by wrapping the `InMemoryEventStoreEngine` in the `EmbeddedEventStore`, as (1) it would always be used in this context and (2) this ensure all event publication/storage operations are happening under the (current) `UnitOfWork`.
As the test succeeds, I deem this pull request resolves #1056.
=> [#1056] Validate event storage rollback in the InMemoryEventStoreEngine

config/src/main/java/org/axonframework/config/AggregateConfigurer.java, config/src/test/java/org/axonframework/config/AggregateConfigurerTest.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/snapshotting/RevisionSnapshotFilter.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/snapshotting/RevisionSnapshotFilterTest.java
This pull request introduces a new implementation of the `SnapshotFilter`: the `RevisionSnapshotFilter`.
This filter upon construction takes in an "allowed revision".
This `String` is validated against the revision on the type of the payload present in the `DomainEventData` when `test` is invoked.
Furthermore, the `AggregateConfigurer` checks for the existence of the `@Revision` annotation on the aggregate `Class`. If it's present, the attribute` revision` is used to create a `RevisionSnapshotFilter`, which is then set as the snapshot filter for this aggregate.
This pull request resolves #1588
=> [#1588] Automatic @Revision-based SnapshotFilter

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
Whenever a query handler is registered we should provide the same `QueryHandler` instance to the `QueryChannel`. 
If we don't, there is a window of opportunity that query handlers with the same query name but differing query-response types allow for double invocations of a query. 
This occurs because Axon Server does not know of the response type (and rightfully so) but only takes into account the query name. 
If for example two query handlers for the query "findAll" are registered, respectively responding with `String` and `Integer`, they would introduce two different `QueryHandler` instances for the same query name. 
Towards AxonServer a subscription is shared which does know the name/type combination, and as such sees two possible option to handle the query "findAll". 
Thus upon …
=> [#1663] Create a single QueryHandler instance to be used for registration

integrationtests/src/test/java/org/axonframework/integrationtests/deadline/AbstractDeadlineManagerTestSuite.java, modelling/src/main/java/org/axonframework/modelling/saga/AnnotatedSaga.java, modelling/src/main/java/org/axonframework/modelling/saga/EndSagaMessageHandlerDefinition.java, modelling/src/main/java/org/axonframework/modelling/saga/SagaMethodMessageHandlerDefinition.java, modelling/src/main/java/org/axonframework/modelling/saga/SagaMethodMessageHandlingMember.java, modelling/src/main/resources/META-INF/services/org.axonframework.messaging.annotation.HandlerEnhancerDefinition, spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java, test/src/test/java/org/axonframework/test/saga/FixtureTest_Deadlines.java, test/src/test/java/org/axonframework/test/saga/TriggerSagaStartEvent.java
This pull request changes when a message handling member in a Saga can end a saga.
It does so by adjusting the validation done in the `AnnotatedSaga`, to simply check whether a `MessageHandlingMember` contains the `@EndSaga` annotation.
As an `AnnotatedSaga` can only be invoked for message handling through `EventMessages` and `DeadlineMessages`, I deemed this adjusted easier than introduce a new Handler Enhancer Definition for this exact combination. Or, adjusting the `DeadlineMethodMessageHandlerDefinition` to include specifics about Sagas, which I feel don't belong there.
Tests have been included from the perspective of a `SagaTestFixture`, as well as the `DeadlineManager` test suite.
As such, this PR resolves #1469
=> [#1469] End Saga when Deadline expires

eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/SequenceEventStorageEngine.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SequenceEventStorageEngineTest.java
Mostly test cases that fails in the current 4.4.x branch, and a quick fix to the problem in #1682. 
`testAggregateEventsAreReadFromFirstSequenceNumberHistoricOnly` is for completeness, it also passes with the current implementation. 
The fix feels a bit of a hack, but I don't know the code well enough at this point. It could be that the `ConcatenatingDomainEventStream` should contain the first sequence number we tried to fetch as a member, and instead apply the fix in the private `nextSequenceNumber()`  method.
Something like:
````java
private final long firstSequenceNumber;
// ... 
private long nextSequenceNumber() {
Long lastSequenceNumber = historic.getLastSequenceNumber();
return lastSequenceNumber == null ? firstSequenceNumber : lastSequenceNumber + 1;
}
````
I can change the PR to …
=> [#1682] Ensure provided first sequence number is used as fallback in absence of events in the historic event store

.github/workflows/maven.yml
GitHub Actions rightfully does not open up the secrets in the repository towards forked pull requests.
However not having access to these complicates some of the current steps, like notifying Slack and pushing snapshots to sonatype.
GitHub did provide some enhancement towards this end to provide extra handles in exactly these scenarios, as is described in [this](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks) blog post. 
What is pointed out, is a dedicated [`pull_request_target`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) event, which signals pull requests from forked branches.
Although usable, as it simply runs the GHA of the main project instead …
=> Add forked-branch validation for GitHub Action steps

spring/src/main/java/org/axonframework/spring/config/annotation/SpringBeanDependencyResolverFactory.java, spring/src/main/java/org/axonframework/spring/config/annotation/SpringContextParameterResolverFactoryBuilder.java, spring/src/main/java/org/axonframework/spring/config/annotation/SpringParameterResolverFactoryBean.java, spring/src/main/java/org/axonframework/spring/eventsourcing/SpringAggregateSnapshotterFactoryBean.java, spring/src/test/java/org/axonframework/spring/config/annotation/SpringBeanResolverFactoryTest.java
This fixes #1620.  The Spring bean parameter resolver now uses Spring bean resolution.  This will behave exactly as if you were injecting a bean from anywhere within Spring.
Two tests are failing: `testMethodsAreProperlyInjected_ErrorOnMissingParameterType` and `testMethodsAreProperlyInjected_ErrorOnDuplicateParameterType`.  This is because Spring injection _does_ handle these cases, and the code will now behave accordingly (i.e. will trigger various forms of `BeansException` when there are problems).  It will also correctly inject `null` when dependencies are missing.
=> Resolve Spring beans using Spring dependency resolution

messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java
Provide the ability to construct an instance of the `QuartzEventScheduler` using the `QuartzEventScheduler.Builder` without the immediate construction of the `EventJobDataBinder` on initialisation of the builder.
Delay the defaulting of the EventJobDataBinder to the construction of the `QuartzEventScheduler` in the single constructor `protected QuartzEventScheduler(Builder builder)`. Delaying the default allows a user to specify an alternative `EventJobDataBinder` using the builder. If an alternative is set, the default is no longer applied.
The default `DirectEventJobDataBinder()` references XStream. By specifying an alternative `EventJobDataBinder`, a user can bypass the XStream hard dependency.
=> Remove QuartzEventScheduler hard dependency on XStream #1685

axon-server-connector/pom.xml, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/AxonServerSubscriptionQueryResult.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/subscription/AxonServerSubscriptionQueryResultTest.java
When a Subscription Query is cancelled the updates Flux is completed
normally instead of with an error. This causes the client to not be able
to recognize whether a Subscription Query was closed due to an error,
or on explicit request by emitting component.
This commit ensures that any errors reported on closing the stream are
propagated into the updates Flux.
=> Propagate errors on cancelled Subscription Query

disruptor/src/main/java/org/axonframework/disruptor/commandhandling/CommandHandlerInvoker.java, disruptor/src/main/java/org/axonframework/disruptor/commandhandling/DisruptorCommandBus.java, disruptor/src/test/java/org/axonframework/disruptor/commandhandling/DisruptorCommandBusTest.java, modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java
Implemented Repository#loadOrCreate on the DisruptorCommandBus.DisruptorRepository, so that the Creation Policy feature can be used in conjunction with the DisruptorCommandBus.
This issue resolves #1587.
=> [#1587] Added Creation Policy support for DisruptorCommandBus

messaging/src/main/java/org/axonframework/commandhandling/CommandBus.java, messaging/src/main/java/org/axonframework/commandhandling/gateway/CommandGateway.java
This PR attempts to clarify the command processing guarantees in `CommandBus#dispatch` Javadoc. For more info, you can read [this discussion](https://discuss.axoniq.io/t/detecting-whether-command-was-posted-to-command-bus-axonserver/2997).
P.S. this is my first PR to this repo, do I need to sign the CLA? If yes, is [this](https://www.clahub.com/agreements/AxonFramework/AxonFramework) site supposed to let me do it? It looks like a default page from the hosting provider. **UPDATE:** I was able to sign the CLA via the button below after creating a PR.
=> Updated command dispatching Javadoc

messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStore.java, messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jpa/JpaTokenStore.java
As the JavaDoc states, nothing happens when releasing a claim on a Segment that is not owned by the current node.
=> Removed misleading warnings from logging when releasing unowned claim

pom.xml, test/pom.xml, test/src/main/java/org/axonframework/test/aggregate/StubAggregateLifecycleExtension.java, test/src/main/java/org/axonframework/test/aggregate/StubAggregateLifecycleRule.java, test/src/test/java/org/axonframework/test/aggregate/StubAggregateLifecycleExtensionTest.java
Replacement of the StubAggregateLifecycleRule, which is now deprecated. (used with JUnit 4). The rule implementation is replaced with StubAggregateLifecycleExtension (JUnit 5).
=> [#1554] Implementation of StubAggregateLifecycleExtension (JUnit 5)

modelling/src/main/java/org/axonframework/modelling/saga/repository/jdbc/PostgresSagaSqlSchema.java
The event and token table already include `IF NOT EXISTS`.
See [here](https://github.com/AxonFramework/AxonFramework/blob/0bb5e66d5815e4b5a0f5aaf611402940a5275a7a/messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/GenericTokenTableFactory.java#L40) and [here](https://github.com/AxonFramework/AxonFramework/blob/0bb5e66d5815e4b5a0f5aaf611402940a5275a7a/eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/AbstractEventTableFactory.java#L35).
=> Skip table creation if already exists

modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateMemberAnnotatedChildEntityCollectionDefinition.java, modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateMemberAnnotatedChildEntityDefinition.java, modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateMemberAnnotatedChildEntityMapDefinition.java, modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedAggregateMetaModelFactory.java, modelling/src/test/java/org/axonframework/modelling/command/inspection/AnnotatedAggregateAggregateMemberMetaModelFactoryTest.java
At this moment, whenever somebody uses an `interface` as the field (generic) type on an `@AggregateMember` annotated element, a `NullPointerException` is thrown.
This occurs due to the fact that the `AnnotatedAggregateMetaModelFactory` is incapable to find the message handlers on the interface/aggregate-member, as a search is done for the superclass of the given type.
Firstly, the `NullPointerException` is resolved by adjusted the while-loop in the `AnnotatedAggregateMetaModelFactory` which checks the given type.
This makes it so that the message handlers present on the interface _will_ be taken into account.
However, this would still mean the message handlers on concrete implementations of the interface are not found at all.
Although this would be nice behaviour to support, as a stopgap …
=> Interface on @AggregateMember should not be allowed

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/GrpcMetaDataAwareSerializer.java
In order to make GrpcMetaDataAwareSerializer available, if needed for custom configuration of the communication with AxonServer.
=> Make public final GrpcMetaDataAwareSerializer.

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonAutoConfiguration.java
`NoClassDefFoundError` is misleading as the class is there only the bean is missing.
=> Better exception type for missing ObjectMapper

config/src/main/java/org/axonframework/config/AggregateConfigurer.java, config/src/test/java/org/axonframework/config/AggregateConfigurerTest.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/snapshotting/RevisionSnapshotFilter.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/snapshotting/RevisionSnapshotFilterTest.java
This pull request adds the aggregate type to the RevisionSnapshotFilter.
The type field is required for any SnapshotFilter implementation, as all filters are combined since they're configured on the EventStore level for the time being (issue #1769 marks an adjustment in this process).
By adding the aggregate's type, and setting it for that automatically created RevisionSnapshotFilter by the AggregateConfigurer, we should resolve any problems in the space of filtering out snapshots from other aggregates than where the filter was intended for.
=> Add Aggregate Type to RevisionSnapshotFilter

test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java, test/src/main/java/org/axonframework/test/aggregate/FixtureConfiguration.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_StateStorage.java
Adds an option to explicitly create an AggregateTestFixture for a state stored aggregate.
This enables the usage of givenCommands() in connection with a constructor handling the command for state stored aggregates.
P.S. Since this is my first PR to this repository, I would be grateful for any feedback or comments.
=> Added an option to create a fixture for a state stored aggregate

config/pom.xml, config/src/main/java/org/axonframework/config/Configuration.java, config/src/main/java/org/axonframework/config/Configurer.java, config/src/main/java/org/axonframework/config/DefaultConfigurer.java, config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java, spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java
This pull request adds a method to configure a `DeadlineManager`. 
This provides a straightforward method, instead of the default `registerComponent` method that would've been required to be used.
As an addition, a default `ScopeAwareProvider` (a requirement for the `DeadlineManager` implementations) is set in the `Configuration` too.
This can be used to further simplify the configuration of a `DeadlineManager` since it will require this component.
=> Simplified DeadlineManager configuration

test/src/main/java/org/axonframework/test/aggregate/ResultValidator.java, test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java, test/src/main/java/org/axonframework/test/aggregate/TestExecutor.java, test/src/main/java/org/axonframework/test/deadline/DeadlineManagerValidator.java, test/src/main/java/org/axonframework/test/deadline/StubDeadlineManager.java, test/src/main/java/org/axonframework/test/saga/FixtureExecutionResult.java, test/src/main/java/org/axonframework/test/saga/FixtureExecutionResultImpl.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_Deadlines.java, test/src/test/java/org/axonframework/test/saga/FixtureTest_Deadlines.java
This pull request makes a minor adjustment and includes some assert option.
Firstly, mentions of `deadlinesMet` have been replaced for `triggeredDeadlines`, as that more closely aligns the description around deadline scheduling and handling.
Secondly, a `expectTriggeredDeadlinesWithName` and `expectTriggeredDeadlinesOfType` method has been included.
This is in line with the other assert options, which also allow asserting deadlines based on name or type.
The triggered deadline validation adjustments have been made for both Aggregate and Saga test fixtures.
Lastly, a small warning was fixed in the Aggregate `TestExecutor`, which didn't include the Aggregate type generic when returning the `ResultValidator` instance.
=> Fine tune triggered Deadline validation for Test Fixtures 

messaging/src/main/java/org/axonframework/eventhandling/ReplayToken.java, messaging/src/test/java/org/axonframework/eventhandling/ReplayTokenTest.java
This pull request adjusts the `ReplayToken#createReplayToken(TrackingToken, TrackingToken)` to return the `startPosition` if `tokenAtReset` is `null`. 
When the replay mechanism was introduced, we assumed that a replay would *only* be initiated if there was already a token present for the given `StreamingEventProcessor` being replayed. 
It is however perfectly reasonable to reset a Streaming Processor before it has even started. 
If this is the case, the given `tokenAtReset` will be null, as there is no token present yet for that Processor.
Defaulting to `null` in that case means the reset will begin from the start, even if the start position may be in the future.
This PR thus adjusts that behaviour to comply with more current usages of the replay/reset mechanism on the …
=> [#1786] Return start position if Token-at-Reset is null

.github/dependabot.yml
This pull request changes the dependabot settings to only react on patch releases. 
This is achieved by ignoring all `major` and `minor` version changes. 
The `target-branch` option is added to point this behavior towards `axon-4.5.x` only, keeping `master` (which constructs our minor versions) as is.
Making this shift thus means that `master` sticks to receive all updates, whereas `axon-4.5.x` will only contain the patch and security releases.
=> React on patch releases only for bug branches

spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java, spring/src/test/java/org/axonframework/spring/config/UpcasterOrderingTest.java
This pull request ensures that the `@Order` annotation is considered when registering `EventUpcaster` instances.
It does so by retrieving all  `EventUpcaster` in the `SpringAxonAutoConfigurer`, sorting them with the `AnnotationAwareOrderComparator` (from Spring), and then invoking the `Configurer#registerEventUpcaster` method.
Next to this, a test is included to ensure the ordering is honored.
This pull request resolves issue #1810.
=> [#1810] Honor @Order annotation on EventUpcasters

messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java, messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java, messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
When using the default Executor Service instances, the framework should shut them down when shutting down the PooledStreamingEventProcessor.
Custom ExecutorServices will not be shut down.
Resolves #1806
=> Shutdown default ExecutorService when stopping PooledStreamingEventProcessor

messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java, messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java, messaging/src/main/java/org/axonframework/eventhandling/pooled/WorkPackage.java, messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
Especially the Messages for which no handler for the type of payload was available did not always cause the tokens to be updated. This commit changes that behavior, to ensure that tokens are updated based on every message received, whether handled or not.
=> Ensure the Tracking Tokens are updated for ignored Event Messages

messaging/src/main/java/org/axonframework/common/ObjectUtils.java, messaging/src/test/java/org/axonframework/common/ObjectUtilsTest.java, modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java, modelling/src/main/java/org/axonframework/modelling/command/LockAwareAggregate.java, modelling/src/main/java/org/axonframework/modelling/command/LockingRepository.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CreationPolicy.java
This PR fixes a lingering bug that causes the `ALWAYS` creation policy to not invoke `@CommandHandlerInterceptor` or `@EventSourcingHandler` annotated functions during the command handling process.
This follows from the fact the handle method is invoked directly on the message handler instead of the constructed Aggregate.
To enable this, the `LockingRepository` and `LockAwareAggregat` now use a `Lock` `Supplier`.
The `Lock` needs to be constructed at the exact moment it is required since the factory method used by the `ALWAYS` creation policy does not construct an aggregate identifier just yet.
The `FixtureTest_CreationPolicy` is expanded to contain interceptor validation and a test case that expects the event sourcing handler to be invoked for the command handling result.
Lastly, a …
=> Creation Policy Always now invokes Command Handler Interceptors and Event Sourcing Handlers

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/PlatformService.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/EventStoreImpl.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java
If the `AxonServerEventStore` fails with reading a snapshot event, the implementation will currently start reading with events.
Sometimes, however, the exception might be a known exception for which it doesn't make sense to proceed.
Thus, this pull request validates whether the received exception carries a `Status.Code` that **does not** equal `UNKNOWN`.
If this is the case, the exception is rethrown inside an `EventStoreException`.
If this isn't the case, we proceed with the regular flow.
A test case has been added to validate this behavior.
Additionally, the stub server implementations have received some improvements to increase the testing speed.
=> Rethrow known gRPC exceptions

modelling/src/main/java/org/axonframework/modelling/command/LockAwareAggregate.java, modelling/src/main/java/org/axonframework/modelling/command/LockingRepository.java, test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CreationPolicy.java
The NPE would be caused by the LockingRepository being unable to get the aggregate identifier of an aggregate whose creation attempt resulted in an exception.
A similar NPE would occur in the test fixtures. This has been addressed too.
=> Fix issue where exception in creation handler causes NPE

messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
The adjusted start/shutdown mechanics, including a count of the active processor threads, have brought to light that sometimes segments are still claimed for processing even though the TEP-shutdown operation has been completed successfully. 
The only process constructing these threads is the private `WorkerLauncher` class. 
By adding a validator in the form of an `AtomicBoolean`, noting when the `WorkerLauncher` is active, we can solve this issue.
The boolean is added next to invocations of `activeProcessorThreads()`, so to overcome the issue of accidentally sharing the shutdown is finalized.
=> Add WorkerLauncher thread activity validation

spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java, spring/src/test/java/org/axonframework/spring/config/UpcasterOrderingTest.java
The current solution in the `SpringAxonAutoConfigurer` will not check whether a bean creation method has the `@Order` annotation.
It instead only works if the `@Order` annotation is added to the class of the upcaster itself.
Although this works fine, allowing the `@Order` annotation to be paired with the `@Bean` annotation is friendlier.
This pull request adjusts the behavior in the `SpringAxonAutoConfigurer` such that we look for the `@Order` annotation through the `ListableBeanFactory#findAnnotationOnBean(String beanName, Class<A> annotationClass)`.
This method takes bean creation methods into account, hence allowing us to check for the order on those.
With these adjustments, issue #1892 is resolved.
=> [#1892] Adjust Upcaster ordering logic in Spring environments

test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_StateStorage.java
When using the `AggregateTestFixture#givenState` method, any events published by invocation of the provided state object are kept.
This might occur for example if the constructor of a state-stored aggregate publishes an event *and* when the constructor is invoked in the `givenState` method.
This setup wrongfully adds events published in the given phase to the expect phase.
This pull request fixes that issue by invoking (the private) `AggregateTestFixture#clearGivenWhenState` after the repository is configured.
=> Clear givenWhen state after setting the repository for State-Stored Aggregate testing  

modelling/src/main/java/org/axonframework/modelling/saga/PayloadAssociationResolver.java, modelling/src/test/java/org/axonframework/modelling/saga/AnnotatedSagaTest.java
This is a pull request for issue #1898.
Signed-off-by: Nils Christian Ehmke <nils@rhocas.de>
=> [#1898] Empty associationProperty leads to IndexOutOfBoundsException

modelling/src/main/java/org/axonframework/modelling/saga/repository/jpa/JpaSagaStore.java
Fixes  #1931
Supersedes #1932
XStream-Dependency was hard coded therefore it could not be excluded. Now it is initialized lazy if no serializer was provided.
Based on Axon 4.5.x
=> Move init of default XStream Serializer to the init()-Method

config/src/main/java/org/axonframework/config/AggregateConfigurer.java, config/src/test/java/org/axonframework/config/AggregateConfigurerTest.java, spring/src/main/java/org/axonframework/spring/config/SpringAxonAutoConfigurer.java, spring/src/main/java/org/axonframework/spring/stereotype/Aggregate.java, spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
This change introduces two features.
Firstly, it allows configuration of the `LockFactory` through the `AggregateConfigurer`.
Doing so enables users to utilize the `configureLockFactory` method to define the `LockFactory` used by the aggregate `Repository`, instead of having to configure a complete `Repository` from scratch.
Secondly, it enables defining a `LockFactory` bean name on the `@Aggregate` annotation.
Axon's auto-configuration checks the Application Context for a bean with the defined name of type `LockFactory`, and in turn uses the `configureLockFactory` to configure it for a given Aggregate.
This pull request resolves #1490.
=> [#1490] Simplify LockFactory configuration for Aggregates

eventsourcing/pom.xml, integrationtests/pom.xml
This PR explicitly sets the `junit-jupiter-api` version to override any alternative version pulled in by the testcontainers junit 5 extension wherever the latter is used. This should avoid version mismatches in the future if JUnit is updated without updating the testcontainers JUnit extension.
=> Align junit jupiter versions between 

messaging/src/main/java/org/axonframework/serialization/json/JacksonSerializer.java, messaging/src/main/java/org/axonframework/serialization/json/JsonNodeToObjectNodeConverter.java, messaging/src/main/java/org/axonframework/serialization/json/ObjectNodeToJsonNodeConverter.java, messaging/src/test/java/org/axonframework/serialization/json/JacksonSerializerTest.java, messaging/src/test/java/org/axonframework/serialization/json/JsonNodeToObjectNodeConverterTest.java, messaging/src/test/java/org/axonframework/serialization/json/ObjectNodeToJsonNodeConverterTest.java
This pull request introduces two new `ContentTypeConverter` instances:
1. the `ObjectNodeToJsonNodeConverter`, and
2. the `JsonNodeToObjectNodeConverter`.
Both are registered with the `JacksonSerializer`.
This allows the `JacksonSerializer` to deserialize/serialize directly to the `ObjectNode` type.
This is beneficial for writing `EventUpcasters`, as 9 out of 10 the serialized JSON event format *is* an `ObjectNode`.
Furthermore, adjusting the contents of a serialized JSON event requires working with an `ObjectNode`.
With these converters in place, users do not have to cast the `JsonNode` to  `ObjectNode` before making any changes to the event format.
This PR resolves #1645
=> [#1645] Introduce ObjectNode-to/from-JsonNode `ContentTypeConverter` for the `JacksonSerializer`

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/XStreamAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/util/XStreamSecurityTypeUtility.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/util/XStreamSecurityTypeUtilityTest.java
Sadly, using the `ComponentScan` annotation is not recommended by the Spring team, as can be found [here](https://stackoverflow.com/questions/50808941/how-to-get-basepackages-of-componentscan-programatically-at-runtime). 
Instead, the team recommends basing ourselves around the `EntityScan` annotation. 
Added, in the absence of the `EntityScan` annotation, we should use the outcome from the `AutoConfigurationPackages#get(BeanFactory)` method to set the packages.
The description above is exactly what this pull request adjusts in the framework. 
It adjusts the `XStreamSecurityTypeUtility` to prefer `EntityScan` annotated beans to set the secured types.
In the absence of this annotation, the outcome from `AutoConfigurationPackages#get(BeanFactory)` is used.
This pull request resolves #1963
=> [#1963] Adjust secured type search approach in for the XStreamAutoConfiguration

messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java, messaging/src/main/java/org/axonframework/eventhandling/pooled/WorkPackage.java
This pull request changes how a token is updated in absence of events to be handled by that segment.
Normally, both the Tracking and Pooled Streaming processor would eagerly update the `TrackingToken` in all scenarios.
Thus, event-full batches (read: events that the segment is in charge of) would update the token, but also event-less batches (read: when the segment is in charge of no events), would incur an immediate token update.
This pull request changes that behavior for both Streaming Processor implementations.
For the Pooled Streaming Processor, the `WorkPackage` now uses the `extensionClaimThreshold` to wait before doing _any_ token update in absence of events it should handle.
The Tracking Processor now also introduces such a deadline.
It uses the "batch processing start time" and …
=> Reduce token update frequency

spring/src/main/java/org/axonframework/spring/config/AbstractAnnotationHandlerBeanPostProcessor.java, spring/src/test/java/org/axonframework/spring/config/annotation/AnnotationCommandHandlerBeanPostProcessorTest.java, spring/src/test/java/org/axonframework/spring/config/annotation/AnnotationQueryHandlerBeanPostProcessorTest.java
In Spring 2.6, the default behavior is to disallow getting beans from the application context that are in creation. Since this is what happens when checking whether a factory bean is a singleton through the bean factory.
=> Skip FactoryBean instances in bean post processors

messaging/src/main/java/org/axonframework/queryhandling/QueryBus.java
The default implementation invoked the same default method on the interface, instead of defaulting to the method recommended in the javadoc.
=> Fix default implementation of deprecated method

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java
Fixes an issue where subscription queries wouldn't close properly when an update to such query failed to serialize.
=> Close subscription queries on serialization issues

test/pom.xml, test/src/main/java/org/axonframework/test/server/AxonServerEEContainer.java, test/src/main/java/org/axonframework/test/server/AxonServerSEContainer.java, test/src/test/java/org/axonframework/test/server/AxonServerEEContainerTest.java, test/src/test/java/org/axonframework/test/server/AxonServerSEContainerTest.java
As a follow up on https://github.com/testcontainers/testcontainers-java/pull/4607, we decided to add the classes to our `test` module ourselves making it easier for people to write end-to-end tests with AxonFramework when using AxonServer.
This PR introduces 2 containers implementations:
- AxonServerSEContainer
- simpler one with an easy way to enable `devMode` and also some utils methods to get host/port/address
- AxonServerEEContainer
- more complex one with the possibilities to set lots of AS attributes
=> Added AxonServerEEContainer and AxonServerSEContainer as an easier way for people to write tests

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventScheduler.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/heartbeat/HeartbeatMonitor.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java, config/src/main/java/org/axonframework/config/LifecycleHandlerInspector.java, config/src/main/java/org/axonframework/config/MessageHandlerRegistrar.java, config/src/test/java/org/axonframework/config/LifecycleHandlerInspectorTest.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/DistributedCommandBus.java, messaging/src/main/java/org/axonframework/deadline/SimpleDeadlineManager.java, messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java, messaging/src/main/java/org/axonframework/eventhandling/SubscribingEventProcessor.java, messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java, messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java, messaging/src/main/java/org/axonframework/eventhandling/scheduling/java/SimpleEventScheduler.java, messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java, messaging/src/main/java/org/axonframework/lifecycle/LifecycleAware.java, messaging/src/main/java/org/axonframework/lifecycle/Phase.java
Instead of relying on annotations out of the box, using an interface makes it easier to configure and tune the lifecycles.
The annotations can still be used for custom components. The Axon-provided components all use the LifecycleAware interface.
=> Introduce LifecycleAware interface for managing component lifecycle

config/src/main/java/org/axonframework/config/EventProcessingModule.java, config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java, messaging/src/main/java/org/axonframework/eventhandling/EventProcessor.java, messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java, messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessorConfiguration.java
This may not fit with the improvements that are being discussed for startup and graceful shutdown, but may be worthwhile as a stopgap until those improvements are ready. It's what I'm using locally to prevent `TrackingEventProcessor` from polling the event store and calling event handlers before my application is fully initialized.
=> Allow TrackingEventProcessor start to be deferred

config/src/main/java/org/axonframework/config/Configurer.java, config/src/main/java/org/axonframework/config/DefaultConfigurer.java, config/src/test/java/org/axonframework/config/DefaultConfigurerLifecycleOperationsTest.java
This pull request introduces a means to adjust the lifecycle phase timeout. 
This is useful for users that know their start-up and/or shutdown process takes longer than the default of 5 seconds.
Resolves #1981
=> Allow lifecycle phase timeout configuration

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventScheduler.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/heartbeat/HeartbeatMonitor.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java, config/src/main/java/org/axonframework/config/Configuration.java, config/src/main/java/org/axonframework/config/Configurer.java, config/src/main/java/org/axonframework/config/DefaultConfigurer.java, config/src/main/java/org/axonframework/config/LifecycleHandlerInspector.java, config/src/main/java/org/axonframework/config/LifecycleOperationConfiguration.java, config/src/main/java/org/axonframework/config/LifecycleOperations.java, config/src/main/java/org/axonframework/config/MessageHandlerRegistrar.java, config/src/test/java/org/axonframework/config/DefaultConfigurerLifecycleOperationsTest.java, config/src/test/java/org/axonframework/config/LifecycleHandlerInspectorTest.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/DistributedCommandBus.java, messaging/src/main/java/org/axonframework/deadline/SimpleDeadlineManager.java, messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java, messaging/src/main/java/org/axonframework/eventhandling/SubscribingEventProcessor.java, messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java, messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java, messaging/src/main/java/org/axonframework/eventhandling/scheduling/java/SimpleEventScheduler.java, messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java, messaging/src/main/java/org/axonframework/lifecycle/Lifecycle.java, messaging/src/main/java/org/axonframework/lifecycle/Phase.java
This pull request introduces the `LifecycleOperationConfiguration` interface.
It contains the `onStart` and `onShutdown` methods that original resided on the `Configuration` interface.
The `LifecycleOperationConfiguration` is extended by the `Configuration` and the `Configurer` .
This allows the registration of start and shutdown operations both during configuration of an Axon application (thus, on the `Configurer`) and once the configuration is done (thus, on the `Configuration`).
This pull request resolves #1711.
=> [#1711] Simplify attachment of Lifecycle Operations

.github/workflows/main.yml, .github/workflows/pullrequest.yml, coverage-report/pom.xml, integrationtests/pom.xml, pom.xml
This pull request introduces several changes to the `pom.xml` to separate the unit tests from integration tests and to include aggregated coverage reports.
These changes can be defined as such:
- It adjusts the `maven-surefire-plugin` run to not include integration tests
- It includes a `coverage-report/pom.xml` project that uses the `jacoco:report-aggregate` goal to collect the coverage data from all its dependencies into one report
- It updates the `coverage` profile to attach the `coverage-report` module
- It includes an `integration-test` profile to run the integration tests
- It introduces the `coverage` property that enables both the `coverage` and `integration-test` profiles. This allows a combined coverage report of both unit and integration tests
- It updates the `main.yml` and …
=> Separate Integration Tests and Aggregate coverage reports

eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngine.java
When using custom DomainEventEntry instances, and thus subclassing the JpaEventStorageEngine, it is useful to still have access to this method
#2065
I noticed there was also a very similar method in the `JdbcEventStorageEngineStatements` class, but since I don't use that I don't know the context of it, nor if it's actually needed if you use JDBC for storage instead of JPA, so I left that alone.
=> Make asDomainEventMessage available to subclasses

messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java, messaging/src/main/java/org/axonframework/eventhandling/pooled/WorkPackage.java, messaging/src/test/java/org/axonframework/eventhandling/pooled/WorkPackageTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/PooledStreamingEventProcessorIntegrationTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/utils/AssertUtils.java
The `PooledStreamingEventProcessor` (PSEP) ignores upcasted events from an `EventMultiUpcaster` due to the `TrackingToken#covers` validation within the `WorkPackage#scheduleEvent` method. 
Just as the `TrackingEventProcessor` (TEP), the PSEP should include events with the same token in the same batch *and* handle them.
This warrants changes in both the `Coordinator` and the `WorkPackage`.
The `Coordinator` should `peek` the event stream to validate if following events contain the same `TrackingToken`.
If so, they should be scheduled on the work packages.
For the `WorkPackage`, the validation within the `schedulEvent` method should ignore the event in case it covers the event *and* if it isn't equal to the `lastDeliveredToken` (read: the last event).
This pull request includes a unit test …
=> Make the `PooledStreamingEventProcessor` compatible with an `EventMultiUpcaster`

eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStore.java
The log was on warning level and sometime misleading. Changed the wording and the log level to reduce the feeling of urgency of this particular situation.
Resolves #1193
=> Changed logging about "processor falling behind"

messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java, messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
When the token store contains a token for some, but not all, segments, the processor fails when trying to calculate the lower bound of these tokens.
This commit fixed that, accepting a null token as the lowerbound, instead of attempting to continue calculating it.
=> PooledStreamingEventProcessor fails when a single token entry is null

messaging/src/main/java/org/axonframework/commandhandling/GenericCommandMessage.java, messaging/src/main/java/org/axonframework/commandhandling/gateway/CommandGateway.java, messaging/src/test/java/org/axonframework/commandhandling/GenericCommandMessageTest.java, messaging/src/test/java/org/axonframework/commandhandling/gateway/DefaultCommandGatewayTest.java
This pull request introduces new `default` methods for the `CommandGateway`.
Namely:
* `<R> CompletableFuture<R> send(Object command, MetaData metaData)`
* `<R> R sendAndWait(Object command, MetaData metaData)`
* `<R> R sendAndWait(Object command, MetaData metaData, long timeout, TimeUnit unit)`
Each of these uses the `GenericCommandMessage#asCommandMessage` method to first construct a `CommandMessage` and then attach the given `metaData` through `Message#andMetaData`.
This change allows for a friendlier API when users, for example, require to attach the correlation data directly to the command they want to dispatch.
Additionally, the `GenericCommandMessage#asCommandMessage` method is updated to include a `Message` branch.
This addition is in line with the JavaDoc of the `CommandGateway`, …
=> Allow insertion of `MetaData` on the `CommandGateway`'s API

test/src/main/java/org/axonframework/test/aggregate/ResultValidator.java, test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java, test/src/main/java/org/axonframework/test/saga/FixtureExecutionResult.java, test/src/main/java/org/axonframework/test/saga/FixtureExecutionResultImpl.java, test/src/test/java/org/axonframework/test/aggregate/ResultValidatorImplTest.java, test/src/test/java/org/axonframework/test/saga/FixtureExecutionResultImplTest.java
Added some additional validation methods to the `ResultValidator` and `FixtureExecutionResult`, allowing to check for the absence of a deadline within a certain timeframe instead of only at a specific `Instant`.
Since there is already a large amount of test methods for deadlines, the new methods add this new functionality in the simplest manner posible, to avoid having an exessive amount of methods, which could cause more confusion to users instead.
This PR resolves issue https://github.com/AxonFramework/AxonFramework/issues/1466
=> Feature/1466 Additional deadline validation methods

pom.xml
This pull request updates the version of XStream to 1.4.19.
By doing so, we resolve any possible security predicaments, as described in [CVE-2021-43859](https://x-stream.github.io/CVE-2021-43859.html).
=> Update XStream version to 1.4.19

messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java, spring/pom.xml, spring/src/main/java/org/axonframework/spring/eventhandling/scheduling/quartz/QuartzEventSchedulerFactoryBean.java, spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
Currently, the `QuartzEventSchedulerFactory` uses the default `XStreamSerializer`, which presents issues with the XStream updgrade in Axon Framework 4.5.4.
This PR changes this behaviour to use the `eventSerializer` bean instead.
NOTE/WARNING: This change is not fully backwards compatible. If currently someone uses the `QuartzEventSchedulerFactoryBean`, but has changed the `eventSerializer` into a `JacksonSerializer` (for  example), it will not be able to deserialize any already serialized and scheduled events. This can be resolved by manually setting the serializer to be used by the factory.
This resolves issue #2088
=> Wire eventSerializer into QuartzEventSchedulerFactoryBean

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/StreamingEventProcessorInfoMessage.java, integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java, messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
Let maxCapacity for tracking event processor return the total number of threads, availableProcessorThreads returns the still available threads.
=> Fix `StreamingEventProcessor#maxCapacity` for the `TrackingEventProcessor`

test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_ExceptionHandling.java
The `ResultValidator#expectExceptionMessage` would complete successfully if there's no exception present while using the `AggregateTestFixture`. 
This is off, as expecting an "exception message" means the user expects an exception to be present. 
This pull request makes the minor adjustment of a null-check for the existence of an exception at all.
=> Fail Aggregate Fixture if there's no exception while `ResultValidator#expectExceptionMessage` is invoked.

modelling/src/main/java/org/axonframework/modelling/saga/SagaLifecycle.java, modelling/src/test/java/org/axonframework/modelling/saga/AnnotatedSagaTest.java
Proposal for adding a method to the `SagaLifecycle`, based on [this discuss question](https://discuss.axoniq.io/t/a-way-to-programmatically-retrieve-saga-associations/3973).
This PR will resolve #1125.
=> [#1125] Introduce `SagaLifecycle.associationValues()`

messaging/src/main/java/org/axonframework/eventhandling/pooled/WorkPackage.java, messaging/src/test/java/org/axonframework/eventhandling/pooled/WorkPackageTest.java
Unlike the TEP, the PSEP does not propagate the WrappedToken instance to the handling UoW. This causes `ReplayStatus` injections to have the wrong value, as well as the `@DisallowReplay` annotation not to work. 
This PR resolves #2154.
=> [#2154] Fix missing propagation of ReplayToken to UnitOfWork for PooledStreamingEventProcessor

modelling/src/main/java/org/axonframework/modelling/command/ApplyMore.java, modelling/src/test/java/org/axonframework/modelling/command/AnnotatedAggregateTest.java
The org.axonframework.modelling.command.ApplyMore interface provides the two methods ...#andThenApply and ...#andThen which are used e.g. in the AggregateLifecycle to apply a payload or execute some code in the correct order.
The conditional variants of these two methods provided in this commit make it easier to conditionally apply a payload or execute code in a more fluent api (see example below).
This refers to https://github.com/AxonFramework/AxonFramework/issues/2173
=> Introduce conditional variants for `ApplyMore`

messaging/src/main/java/org/axonframework/serialization/upcasting/event/EventTypeUpcaster.java, messaging/src/main/java/org/axonframework/serialization/upcasting/event/InitialEventRepresentation.java, messaging/src/main/java/org/axonframework/serialization/upcasting/event/IntermediateEventRepresentation.java, messaging/src/main/java/org/axonframework/serialization/upcasting/event/UpcastedEventRepresentation.java, messaging/src/test/java/org/axonframework/serialization/upcasting/event/EventTypeUpcasterTest.java, messaging/src/test/java/org/axonframework/serialization/upcasting/event/InitialEventRepresentationTest.java, messaging/src/test/java/org/axonframework/serialization/upcasting/event/UpcastedEventRepresentationTest.java
As [dakr0013](https://github.com/dakr0013) mentioned in #2169, the `EventTypeUpcaster` causes issues further down the upcasting chain as it expects the intermediate type `Object`.
Using this as the `expectedRepresentationType` causes the intermediate representation to become a concrete type.
This obstructs further upcasters that, for example, expect `JsonNode`, to break.
This pull request uses earlier commits from [dakr0013](https://github.com/dakr0013) but solves the search for the `expectedRepresentationType` differently.
I have expanded the `IntermediateEventRepresentation` with the `getContentType` method.
This method returns the representation type of the contained payload.
This method is in turn used by the `EventTypeUpcaster` to **not** change the intermediate type, allowing …
=> Fix for EventTypeUpcaster

messaging/src/main/java/org/axonframework/eventhandling/ReplayStatus.java
Currently, the javadoc of the ReplayStatus enum still points to tracking event processors. This is not correct any longer, since `TrackingEventProcessor` are an implementation of the `StreamingEventProcessor` interface, which are all asynchronous and support replaying. The javadoc has been updated to reflect this.
=> Improve javadoc of the ReplayStatus enum to reflect changes to the StreamingEventProcessors

config/src/main/java/org/axonframework/config/EventProcessingModule.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationTest.java
The eager initialization of event processors can cause circular dependencies when one of the event handlers relies on the configuration. This is espectially the case when using an external dependency injection mechanism to wire some beans.
Event Processors are initialized at the latest when the configuration starts, or earlier when the processors are retrieved from the configuration.
=> EventProcessingModule should lazily initialize processors

modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java
During a pair programming session yesterday, @smcvb got into a discussion about a validation that was present in the `AggregateCreateOrUpdateCommandHandler`, which is triggered by an `AggregateCreationPolicy` annotation with value `CREATE_IF_MISSING`. 
We found that:
- Other command handlers do not validate this. 
- It's valid not to have an identifier set, by not applying an event at all (thus the aggregate not being created). 
- Setting the identifier explicitly to null later will throw an error in the EventStore when applying events.
Because of this, we removed the validation, also fixing the issue a customer had.
=> Remove unnecessary validation of aggregate identifier

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/GrpcMetaDataAwareSerializer.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/GrpcMetaDataConverter.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/EventStoreImpl.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java
This commit fixes an issue where a new context was created for each individual event. This caused a context aware upcaster to lose any contextual information while upcasting a single stream of events when loading events for an aggregate.
This commit also fixes an issue where snapshots would be considered when loading an aggregate from its initial position, even when an explicit attempt to load snapshots had already been performed.
=> Ensure the context is maintained between upcaster invocations in single stream

messaging/src/main/java/org/axonframework/common/ReflectionUtils.java, messaging/src/test/java/org/axonframework/common/ReflectionUtilsTest.java, test/src/main/java/org/axonframework/test/aggregate/Reporter.java, test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java, test/src/main/java/org/axonframework/test/matchers/EqualFieldsMatcher.java, test/src/main/java/org/axonframework/test/saga/CommandValidator.java, test/src/test/java/org/axonframework/test/aggregate/ResultValidatorImplTest.java, test/src/test/java/org/axonframework/test/matchers/EqualFieldsMatcherTest.java, test/src/test/java/org/axonframework/test/saga/CommandValidatorTest.java
JDK17 does not allow reflective access to `java.lang` class, like the primitives and `String`. 
Due to this, if a user uses a primitive type in commands, events, queries, and deadlines, as we frequently do in our tests, the `EqualFieldsMatcher` will throw an exception. 
Ideally, the `EqualFieldsMatcher` wouldn't be exposed through the `Matchers` utility directly, since that would allow us to attach an equals check before proceeding with the fields equals. 
However, the `ResultValidatorImpl` and `CommandValidator` rely on the `Matchers` return type being the `EqualFieldsMatcher` for error descriptions.
Due to this, this pull request changes the `EqualFieldsMatcher` to check if it deals with a primitive "expected" or "actual" type.
If this is the case, a regular `equals` check is done …
=> [#2189] Validate primitive types differently in the EqualFieldsMatcher

messaging/src/main/java/org/axonframework/messaging/responsetypes/FluxResponseType.java, messaging/src/main/java/org/axonframework/messaging/responsetypes/MultipleInstancesResponseType.java, messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java
`FluxResponseType` should conform to the new way of `ResponseType` matching using ranks.
Besides the beforementioned change. I noticed that getting handlers was not implemented correctly, we were getting matches only for the highest ranks, and not for all of them. It doesn't have to mean that the highest will work, it's fine to have a fallback.
=> Flux response type rank matching

spring/src/main/java/org/axonframework/spring/config/SpringAxonConfiguration.java, spring/src/main/java/org/axonframework/spring/event/AxonStartedEvent.java, spring/src/test/java/org/axonframework/spring/config/SpringAxonConfigurationTest.java
Publishes an `AxonStartedEvent` when the Configuration module has fully started. This means that Event processors are up and running, command handlers are registered and all other things Axon provides.
=> Spring event for indication that Axon has started

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventScheduler.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java, messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java, messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java, messaging/src/test/java/org/axonframework/serialization/upcasting/event/SingleEventUpcasterTest.java, modelling/src/main/java/org/axonframework/modelling/saga/repository/jdbc/JdbcSagaStore.java, modelling/src/main/java/org/axonframework/modelling/saga/repository/jpa/JpaSagaStore.java, spring/src/test/java/org/axonframework/spring/config/SpringAxonAutoConfigurerTest.java
The intention of this PR is to remove the usage of the `XStreamSerializer::defaultSerializer` deprecated method.
By doing that, we are now using up to date methods (and Builders) but also removed a double `warn` message, before logged by both the Component using it but also the Serializer itself.
=> Removed deprecated code by updating the default serializer initialization

messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspector.java, messaging/src/test/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspectorTest.java, modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java, modelling/src/test/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandlerTest.java
When the AggregateAnnotationCommandHandler subscribes to the commandBus, it does so once for every payload type. This is independent of how many handlers are present for that type, since it does so using a set. In addition, it passes itself as the handler, making the DuplicateCommandHandlerResolver useless since comparing handlers is impossible (both handler arguments are the AggregateAnnotationCommandHandler itself, instead of the conflicting handlers).
In this PR this has been changed so the AggregateAnnotationCommandHandler subscribes the child command handlers to the CommandBus, instead of itself. This bypasses its handle and canHandle methods (since it is never really subscribed), but then uses these of the handlers in its list.
In addition, this PR solves an issue with the …
=> Fix duplicate command handler resolver not being used for annotated aggregates

messaging/src/main/java/org/axonframework/common/ReflectionUtils.java, test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
This avoids performing reflection on classes that may not be declared
open to the module that contains the fixtures. Typically, these classes
would implement a suitable equals method.
This change will test equality using equals first, before attempting to
check fields. If equals returns false, it will still check whether an
equals method is explicitly implemented. Only when that is not the case,
a field-to-field comparison is performed using the same approach for
each individual field.
=> Use equals() first for aggregate state check

axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/QueryProcessingTaskIntegrationTest.java, messaging/src/main/java/org/axonframework/messaging/responsetypes/AbstractResponseType.java, messaging/src/main/java/org/axonframework/messaging/responsetypes/MultipleInstancesResponseType.java, messaging/src/main/java/org/axonframework/messaging/responsetypes/PublisherResponseType.java, messaging/src/main/java/org/axonframework/messaging/responsetypes/ResponseTypes.java, messaging/src/main/java/org/axonframework/queryhandling/GenericStreamingQueryMessage.java, messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java, messaging/src/main/java/org/axonframework/queryhandling/StreamingQueryMessage.java, messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryGatewayTest.java
Switched FluxResponseType to PublisherResponseType due to compatibility with apps that do not have Project Reactor on the classpath.
=> Publisher Response Type

eventsourcing/src/main/java/org/axonframework/eventsourcing/MultiStreamableMessageSource.java, integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/MultiStreamableMessageSourceTest.java, messaging/src/main/java/org/axonframework/eventhandling/MultiSourceTrackingToken.java, messaging/src/main/java/org/axonframework/eventhandling/MultiStreamableMessageSource.java, messaging/src/test/java/org/axonframework/eventhandling/MultiSourceTrackingTokenTest.java
This pull request solves two issues, one minor and one major.
Firstly (minor), the `MultiStreamableMessageSource` is moved from the `eventsourcing` module to the `messaging` module.
It was wrongly situated there, as nothing defines it is `eventsourcing` specific at all.
It **is** `eventhandling` specific though, due to the `TrackedEventMessage` generic assumption.
To solve this predicament but not break existing users, I have copied the `MultiStreamableMessageSource` to `org.axonframework.eventhandling` and deprecated the version in `eventsourcing`.
Lastly, the deprecated variant extends the copied variant, to ensure everybody will use the intended version from now on.
Secondly (major), the `MultiSourceTrackingToken#lowerBound` had an opportunity to throw a `NullPointerException`. …
=> Move the `MultiStreamableMessageSource` and allow `null` in `MultiSourceTrackingToken#lowerBound`

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
There was a mismatch between the configured constant
`private static final int DEFAULT_GRPC_PORT = 8124;``
and the statement in the javadoc.
=> fix javadoc: default port is 8124, not 8123

messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java, messaging/src/test/java/org/axonframework/eventhandling/pooled/CoordinatorTest.java
**Steps to reproduce**
When using a RDBMS as Event Store/Bus and Token Store, and the database goes offline, the scenario below occurs:
1. The CoordinationTask starts abortAndScheduleRetry logic;
2. In abortAndScheduleRetry, the application tries to release claim in token store, but as the database is offline, this throws another exception;
3. The completable future chain is not handling exceptional completation, and because it, the task reschedule are not being executed;
4. When the database comes online again, as the reschedule is not happening and there is no CoordinationTask running, the application does not recover by itself, requiring a restart of the JVM.
**Expected behaviour**
The coordination task reschedule should execute always.
So, when the DB comes online again, the …
=> fix: CoordinationTask doesn't reschedule itself when token release claim fails

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java, messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java, messaging/src/main/java/org/axonframework/queryhandling/StreamingQueryMessage.java, pom.xml, reactorless-test/pom.xml, reactorless-test/src/main/java/org/axonframework/reactorlesstest/ReactorlessStartup.java, reactorless-test/src/test/java/org/axonframework/reactorlesstest/ReactorlessStartupTest.java
Rationale: lambdas are compiled into inner classes. If they have a reference to Project Reactor types, it is not possible to create a bean of an outer class. Static inner classes have no reference to outer class, hence, they don't have this problem.
Food for thought: Currently, there aren't any tests (but `axon-minimal` project created by @gklijs) confirming these changes. We could create a new test module without Reactor dep. I am wondering whether we want to have something like this, having in mind that Reactor will become a required dependency pretty soon.
Resolves #2238
=> Extracted lambdas to inner static classes

messaging/src/test/java/org/axonframework/commandhandling/distributed/ConsistentHashTest.java
Hey 😊
I want to contribute the following test:
Test that `consistentHashModified.equals(new ConsistentHash())` is false when `equals` is called with the parameter `o = new ConsistentHash()`.
This tests the method [`ConsistentHash.equals`](https://github.com/AxonFramework/AxonFramework/blob/1577eee6e536719c7f0e4c4f9e21ff75af3c80ad/messaging/src/main/java/org/axonframework/commandhandling/distributed/ConsistentHash.java#L177).
This test is based on the test [`testConflictingHashesDoNotImpactMembership`](https://github.com/AxonFramework/AxonFramework/blob/1577eee6e536719c7f0e4c4f9e21ff75af3c80ad/messaging/src/test/java/org/axonframework/commandhandling/distributed/ConsistentHashTest.java#L104).
Curious to hear what you think!
(I wrote this test as part of a research study at TU Delft. [Find …
=> Add test for ConsistentHash.equals

test/src/main/java/org/axonframework/test/matchers/DeepEqualsMatcher.java, test/src/main/java/org/axonframework/test/matchers/MatchAllFieldFilter.java, test/src/test/java/org/axonframework/test/matchers/DeepEqualsMatcherTest.java
Since 4.5.10 when I register a field to be ignored in a fixture test, the field is not ignored. In the DeepEqualsMatcher a check is missing when before calling the equals method of the object.
=> Check attribute filter deep equals

spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AggregateStereotypeAutoConfigurationTest.java, spring/src/main/java/org/axonframework/spring/config/SpringAggregateLookup.java, spring/src/main/java/org/axonframework/spring/stereotype/Aggregate.java
When we introduced the [new Spring configuration](https://github.com/AxonFramework/AxonFramework/pull/2105), we unintentionally broke Aggregate stereotype configuration.
More specifically, a `Cache` and `LockFactory` bean name weren't taken into account when constructing the `AggregateConfigurer`.
This pull request resolves this predicament, by checking whether `cache` and `lockFactory` have a non-null and non-empty bean name on the `@Aggregate` annotation.
When this is the case, they are provided to the `AggregateConfigurer`.
We've introduced a dedicated test case for all Aggregate stereotype configurable components within this pull request.
Lastly, the JavaDoc of the stereotype has been improved slightly.
=> Support `Cache` and `LockFactory` configuration on `@Aggregate` stereotype

config/src/main/java/org/axonframework/config/EventProcessingConfigurer.java, config/src/main/java/org/axonframework/config/EventProcessingModule.java, config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java
This pull request contains two adjustments around `PooledStreamingEventProcessor` configuration:
1. We introduced a `usingPooledStreamingEventProcessors` method to the `EventProcessingConfigurer` that takes in the `PooledStreamingProcessorConfiguration`. With this users can define their default `PooledStreamingEventProcessor` in one go.
2. The thread pool size for the Worker Executor is changed to four in the `EventProcessingModule`. This is inline with the Spring Boot auto configuration, which also defaults to four.
Point one is most definitely a simplification.
Point two is arguably a bug fix, as there's an unintended difference between Java configuration and Spring Boot auto configuration.
Due to point two, this pull request targets the `axon-4.5.x` instead of `master`.
=> Pooled Streaming Event Processor configuration enhancement

core/src/main/java/org/axonframework/messaging/unitofwork/CurrentUnitOfWork.java, core/src/test/java/org/axonframework/messaging/unitofwork/CurrentUnitOfWorkTest.java
This pull request changes the behavior of the `CurrentUnitOfWork#isStarted()` and `CurrentUnitOfWork#get()` methods (strictly speaking the private `isEmpty` method for the latter).
It purges any `UnitOfWork` instances on the stack that are in the `Phase#CLOSED`.
Note that this required a change in the `CurrentUnitOfWork#clear(UnitOfWork)` static method too.
Said operation performed an `CurrentUnitOfWork#isStarted()` check before clearing the `UnitOfWork`.
But as `CurrentUnitOfWork#isStarted()` now clears closed entries, as is the intention of `CurrentUnitOfWork#clear(UnitOfWork)`, we ended up in an undesired state.
Doing so eliminates the possibility that life cycle handlers are attached on a `CLOSED` unit of work when nesting is involved.
Although this is an off chance, it does cause …
=> Purge `CLOSED` Unit of Work instances on `CurrentUnitOfWork#isStarted()` and `CurrentUnitOfWork#get()`

eventsourcing/src/main/java/org/axonframework/eventsourcing/EventSourcingRepository.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/EventSourcingRepositoryTest.java, integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/AbstractPolymorphicAggregateAnnotationCommandHandlerTestSuite.java, integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/PolymorphicESAggregateAnnotationCommandHandlerTest.java, integrationtests/src/test/java/org/axonframework/integrationtests/polymorphic/PolymorphicJpaAggregateAnnotationCommandHandlerTest.java, modelling/src/main/java/org/axonframework/modelling/command/AbstractRepository.java, modelling/src/main/java/org/axonframework/modelling/command/GenericJpaRepository.java, modelling/src/main/java/org/axonframework/modelling/command/LockingRepository.java, modelling/src/test/java/org/axonframework/modelling/command/GenericJpaRepositoryTest.java
When a user needs to construct a custom `Repository` for a polymorphic aggregate, they're currently required to manually construct the `AggregateModel` since this is where subtypes may be defined. 
Although this works, this is not in line with the fact the `AggregateModel` **is not** a hard requirement during the construction of the `Repository`.
As such, chances are high that the user forgets to mention the subtypes, assuming they're picked up through annotations, for example.
By allowing configuration of the subtypes of the `aggregateType` on the `Repository.Builders` directly, we ease the configuration of a custom `Repository` for polymorphic aggregates.
=> Allow subtype definition on the `Repository` builders for Polymorphic Aggregates

eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngine.java
Hi :) This PR is an enhancement to override fetchTrackedEvents queries.
**Event**
We faced a problem using Tracking Event Processes and wrote a [medium story](https://medium.com/trendyol-tech/axon-tracking-event-processor-optimization-8baba7946a96) about it. Then We decided to change the queries on the fetchTrackedEvents method on JpaEventStorageEngine class because sometimes they run very slowly, especially when there is at least one gap. (details are in the story)
**Problem**
While overriding these queries, we had to duplicate other methods and some fields. ([a sample implementation](https://github.com/altuntasfatih/axon-tracking-event-processor-optimization/blob/main/src/main/java/com/tep/config/CustomJpaEventStorageEngine.java) ).
**Solution**
If there is a protected method like the …
=> Create a protected method to fetch tracking events on JpaEventStorageEngine

messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java, messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessorConfiguration.java
TrackingEventProcessor does not wait for his worker threads to shut down
Signed-off-by: Nils Christian Ehmke <nils-christian.ehmke@bmiag.de>
This pull request resolves #2290.
=> [#2290] `TrackingEventProcessor` does not wait for his worker threads to shut down

messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryUpdateEmitter.java, messaging/src/main/java/org/axonframework/queryhandling/UpdateHandlerRegistration.java, messaging/src/test/java/org/axonframework/queryhandling/SimpleQueryBusTest.java, messaging/src/test/java/org/axonframework/queryhandling/UpdateHandlerRegistrationTest.java
Users are not inclined to subscribe to the `Flux` returned by the `QueryBus`.
If they don't subscribe, the `QueryUpdateEmitter` does not remove the update handler registration since it's only removed through closing the `Flux`. 
This pull request adjusts the `UpdateHandlerRegistration` to remove the registered handler from the `SimpleQueryUpdateEmitter` whenever `UpdateHandlerRegistration#complete` is invoked.
Doing so, this pull request resolves #2299.
=> Remove update handler registration on `UpdateHandlerRegistration#complete`

messaging/src/main/java/org/axonframework/common/ReflectionUtils.java, messaging/src/test/java/org/axonframework/common/ReflectionUtilsTest.java, modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java, modelling/src/test/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandlerTest.java
This fix is achieved by registering for each signature instead of each Executable. The signature is a combination of the method's name and its parameters. Different Executables can have the same signature, for example in polymorphic aggregates. When the signature is the same, we only want to register once, since this is not a true duplicate handler. At runtime, the AnnotatedHandlerInspector will resolve the right Executable based on the aggregate type and the command.
Fixes #2243
=> Fix duplicate command handler detection.

axon-server-connector/pom.xml, eventsourcing/pom.xml, integrationtests/pom.xml, pom.xml, test/pom.xml
Introduced the testcontainers and junit boms in the main project to ensure both direct and transitive dependencies resort to the same versions.
=> Using boms to streamline test framework dependencies

messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java
Turns out there were a few edge cases left. I also restructured a bit, to make both workers more the same. Now when a worker 'switches jobs' it will always be from the cleanup/finally.
The main left over problem was that the `AtomicBoolean` for the `workLauncherRunning` was set from the worker thread. So it could happen that it would switch to true, after calling `start()`, which in turn prevented the thread to be stopped at `shutdown()` which in turn caused an error when calling `start()` again, since it was not properly shutdown, as expected.
Additionally a `removeThread(String name)` method was added, where the expectation is that it will never actually log the message, but would provide valuable information if it does.
This was locally tested as fix for …
=> Improve the concurrent behaviour of the tracking event processor.

pom.xml
This pull request upgrades the `axonserver-connector-java` dependency from 4.5.6  to 4.5.7.
=> Upgrade Axon Server Connector Java to 4.5.7

config/src/main/java/org/axonframework/config/ConfigurationScopeAwareProvider.java, config/src/test/java/org/axonframework/config/ConfigurationScopeAwareProviderTest.java
Signed-off-by: Nils Christian Ehmke <nils-christian.ehmke@bmiag.de>
=> [#2317] Using deadlines with DefaultConfigurer leads to NPE

pom.xml, reactorless-test/pom.xml
Needed some additional fixes. It does give a warning currently, as there was a breaking change in the `org.slf4j.spi.SLF4JServiceProvider` interface `getRequesteApiVersion` -> `getRequestedApiVersion`. We might want to wait till the new impl versions are available, likely 2.18.0 -> 3.0.0? See [tags](https://github.com/apache/logging-log4j2/tags). But we already moved to 2.0.0 for some extensions.
=> Update slf4j version to 2.0.0

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/GrpcBackedSubscriptionQueryMessage.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/subscription/SubscriptionMessageSerializerTest.java, messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryUpdateEmitter.java, messaging/src/test/java/org/axonframework/queryhandling/SimpleQueryUpdateEmitterTest.java
See https://github.com/AxonFramework/AxonFramework/issues/2331
=> [#2331] Fix deserialization bug `GrpcBackedSubscriptionQueryMessage` and filter non-handler-matching updates

messaging/src/main/java/org/axonframework/common/Priority.java, messaging/src/main/java/org/axonframework/messaging/annotation/SimpleResourceParameterResolverFactory.java, test/src/test/java/org/axonframework/test/saga/FixtureTest_RegisteringMethodEnhancements.java, test/src/test/java/org/axonframework/test/saga/StubSaga.java
The `SimpleResourceParameterResolverFactory` had the same priority as the `DefaultParameterResolverFactory`. Because of this it was possible for both the `SagaFixture` and `AggregateFixture` to inject the wrong values into message handling methods in certain cases. This behavior in tests deviates from normal application behavior, so should be fixed. 
This was done by lowering the priority on the `SimpleResourceParameterResolverFactory`, essentially making it the last to resolve. 
A notable case where the issue occurred is when injecting an `Object` value of the `MetaDataValue` annotation, like so:
```java
public void handleSagaStart(TriggerSagaStartEvent event, @MetaDataValue("extraIdentifier") Object extraIdentifier) {
}
```
Since Object matches any resource present in the …
=> Parameter resolver ordering is wrong for test fixtures

spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationTest.java, spring/src/main/java/org/axonframework/spring/config/SpringConfigurer.java, spring/src/test/java/org/axonframework/spring/config/SpringConfigurerTest.java
When multiple candidates exist for a certain component, the Axon Configurer should throw an exception if not exactly one of these is marked as a Primary bean.
=> Throw exception on ambiguous dependencies

config/src/main/java/org/axonframework/config/DefaultConfigurer.java, config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java, messaging/src/main/java/org/axonframework/util/HandlerTypeResolver.java
This will prevent starting an event processor when there is no need for it.
=> Check if a certain handler contains certain methods before registering it.

messaging/src/main/java/org/axonframework/messaging/correlation/CorrelationDataProvider.java, messaging/src/main/java/org/axonframework/messaging/unitofwork/AbstractUnitOfWork.java, messaging/src/test/java/org/axonframework/messaging/GenericMessageTest.java, messaging/src/test/java/org/axonframework/messaging/correlation/ThrowingCorrelationDataProvider.java, messaging/src/test/java/org/axonframework/messaging/unitofwork/AbstractUnitOfWorkTest.java
Current implementation always catches exceptions from correlation providers.
Optionally we might only do this when the message is an exception or when called from the catch block in the `UnitOfWork`?
Resolves https://github.com/AxonFramework/AxonFramework/issues/2328
=> Catch exceptions from correlation data providers.

messaging/src/main/java/org/axonframework/tracing/NoOpSpanFactory.java, messaging/src/main/java/org/axonframework/tracing/SpanFactory.java, messaging/src/test/java/org/axonframework/tracing/TestSpanFactory.java, tracing-opentelemetry/src/main/java/org/axonframework/tracing/opentelemetry/OpenTelemetrySpanFactory.java
There is a naming error in the `SpanFactory` interface. This PR corrects it.
=> Rename SpanFactory.registerTagProvider to registerSpanAttributeProvider

.github/workflows/slack-release-notification.yml
Some customers would like to get an announcement on Slack when a new version has been released. 
To make this work a Github secret (secrets.SLACK_WEBHOOK) needs to be added.
=> Added Slack release announcement

messaging/src/main/java/org/axonframework/serialization/SerializedMessage.java, messaging/src/test/java/org/axonframework/serialization/SerializedMessageTest.java
If, while de-serializing a message payload or meta data, a SerializationException is thrown, re-throw it with a more specific error message that includes the message identifier. This makes analysis of de-serialization errors easier.
=> Include message identifier in error message if de-serialization fails

messaging/src/main/java/org/axonframework/tracing/SpanUtils.java, messaging/src/test/java/org/axonframework/tracing/SpanUtilsTest.java
Currently, the deadline only contains the payload type in the trace name. However, it's useful to know the deadlineName and the payload class.
=> Improve deadline span name.

eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java, messaging/src/main/java/org/axonframework/serialization/AbstractXStreamSerializer.java, messaging/src/main/java/org/axonframework/serialization/xml/XStreamSerializer.java
In later JDK versions, and earlier on Windows (it seems), Axon Framework 4.6.0 fails to boot due to a ClassNotFoundException.
This happens when XStream is not included on the classpath.
It seems like the JDK can handle not being able to find a class unless it's called. However, it can not handle being able to find a class but not the interface it implements (like the case in `CompactDriver`, implementing an XStream class). 
The `XStreamSerializer` now defaults to a `new XStream(new CompactDriver())`, instead of relying on the caller to do this. This allows the JDK to happily boot Axon Framework again.
=> [#2364] Fix framework failing to start due to a `ClassNotFoundException`

spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithDisruptorTest.java, spring/src/main/java/org/axonframework/spring/config/SpringAggregateLookup.java, spring/src/main/java/org/axonframework/spring/eventsourcing/SpringRepositoryFactoryBean.java, spring/src/main/java/org/axonframework/spring/modelling/SpringRepositoryFactoryBean.java
The revised Spring configuration classes did not include registering `Repository` beans to the application context, as pointed out in #2367.
This PR introduces a `FactoryBean` to achieve this that retrieves the `Repository` for a certain class from Axon's `Configuration`.
This pull request resolves #2367.
=> [#2367] Fix Repository beans not being registered to the Spring application context

modelling/src/main/java/org/axonframework/modelling/command/NoArgumentConstructorCreationPolicyAggregateFactory.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CreationPolicy.java
This PR introduces changes to the `NoArgumentConstructorCreationPolicyAggregateFactory`.
More specifically, it ensures that `@CreationPolicy` annotated methods using `CREATE_IF_MISSING` or `ALWAYS` may still have a `private` or `protected` method.
This is done by using the `ReflectionUtils` to make the `private`/`protected` accessible.
For validation, four test cases have been introduced:
1. A `private` constructor with `CREATE_IF_MISSING` policy,
2. a `protected` constructor with `CREATE_IF_MISSING` policy,
3. a `private` constructor with `ALWAYS` policy, and
4. a `protected` constructor with `ALWAYS` policy.
Doing so, this pull request resolves #2389.
=> [#2389] Make constructors accessible in `NoArgumentConstructorCreationPolicyAggregateFactory` 

messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStore.java
Fixes #2409
The previous `size` column in the select has been renamed to `segmentCount`, since `size` is a reserved keyword in oracle.
=> Renamed size column name in JdbcTokenStore

modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedAggregate.java, modelling/src/main/java/org/axonframework/modelling/command/inspection/ForwardingCommandMessageHandlingMember.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CommandInterceptors.java
With the introduction of #2093, the `AnnotatedAggregate` started validating whether there's an entity inside the Aggregate that's eligible to handle the command in question.
This validation will check for the existence of a concrete instance of an entity.
As described in issue #2393, this breaks the support for an `@CommandHandlerInterceptor` annotated method that handles a command targeted towards an Entity / Aggregate Member.
More specifically, `@CommandHandlerInterceptor` annotated methods having an `InterceptorChain` parameter, as those specifically give power to the user to decide whether to move into the command handler, yes or no.
By moving the retrieval of a suitable command handler inside the `InterceptChain`, we ensure the chain is invoked _before_ we actually enter the command …
=> [#2393] Move retrieval of Command Handler to the end of the InterceptorChain

axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/EventBufferTest.java, pom.xml
This pull request upgrades the `axonserver-connector-java` dependency from 4.6.1 to 4.6.2.
=> Upgrade to `axonserver-connector-java` 4.6.2

test/src/main/java/org/axonframework/test/aggregate/Reporter.java, test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java, test/src/test/java/org/axonframework/test/aggregate/ResultValidatorImplTest.java
This is the first pull request related to issue #2400, improving the mismatch reporting. This is done by using the describeMismatch Method to identify the actual difference.
=> Improve mismatch messages for Hamcrest Matchers #2400

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventScheduler.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AbstractEventStorageEngine.java, messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java, messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java, messaging/src/main/java/org/axonframework/serialization/xml/XStreamSerializer.java, modelling/src/main/java/org/axonframework/modelling/saga/repository/jdbc/JdbcSagaStore.java, modelling/src/main/java/org/axonframework/modelling/saga/repository/jpa/JpaSagaStore.java
This pull request replaces the local construction of the `XStreamSerializer` through it's builder in several of Axon Framework's infrastructure components.
Doing so, ensure an end user can safely exclude the XStream dependency, without the component in question failing with `NoClassDefFoundError`.
Instead, we reintroduce the use of `XStreamSerializer#defaultSerializer`, as this moves the statements to the `XStreamSerializer` instance.
To maintain the logged exception trace, the warning *with* the `AxonConfigurationException` is completely moved to the `XStreamSerializer`.
Previously, every infrastructure component logged this warning itself.
Through this fix, we resolve bug #2431.
=> [#2431] Use `XStreamSerializer#defaultSerializer` to mitigate XStream exclusion issues

spring/pom.xml
This pull request adds the `test` scope to the `mysql-connector-java` dependency in the `axon-spring` module.
Without the `test` scope, users may accidentally retrieve an additional and undesired data source.
=> Add test scope to `mysql-connector-java` dependency

spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerPropertiesTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithHibernateTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AggregateStereotypeAutoConfigurationTest.java, spring/src/main/java/org/axonframework/spring/config/SpringAggregateConfigurer.java, spring/src/main/java/org/axonframework/spring/config/SpringAggregateLookup.java
When annotating an aggregate with `@Entity`, the autoconfiguration should configure a GenericJpaRepository, instead of an EventSourcingRepository. In 4.6.0 and 4.6.1, this was not the case anymore.
This commmit re-introduces the autoconfiguration of the GenericJpaRepository.
Additionaly, configuring a repository based on the naming convention `aggregateName+"Repository"` resulted in a circular dependency due to a bug. This is also resolved in this commit.
=> Fix regression for GenericJpaRepository autoconfig

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/InfraConfiguration.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfigurationTest.java
There is a regression in the Spring Autoconfiguration since 4.6, causing the Resource Injector to not be available as a bean in the application context. As a result, the Resource Injector used by default is the one taking resources from the Configuration, rather than using Spring to autowire dependencies. In most cases, this will behave the same way. Only when using Qualifiers or spring-specific dependency injection options, this may lead to issues.
This commit will enforce the same behavior as 4.5, where a user-defined resource injector takes precedence, while defaulting to the SpringResourceInjector.
=> Added Spring Resource Injector to Application Context

modelling/src/main/java/org/axonframework/modelling/saga/repository/AnnotatedSagaRepository.java, modelling/src/main/java/org/axonframework/modelling/saga/repository/CachingSagaStore.java, modelling/src/test/java/org/axonframework/modelling/saga/repository/CachingSagaStoreTest.java
When adjusting the `CachingSagaStore` in 4.6.1, I have accidentally introduced a lambda that replaced the `AssociationValue` cache entries into a `boolean`.
This was done by simply invoking `Set#add` on the association values directly, instead of returning the set.
This pull request fixes that issue, by returning the set i.o. the result of `Set#add`.
For testing, the `sagaAndAssociationsRemovedFromCacheOnDelete` now updates the saga entry.
Doing so, we impose an adjustment on the association value cache too, ensuring the right result is consistently returned from the `Cache#computeIfPresent` invocation.
=> Fix `Cache#computeIfPresent` return value in `CachingSagaStore`

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerRemoteCommandHandlingException.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerRemoteQueryHandlingException.java, messaging/src/main/java/org/axonframework/commandhandling/CommandExecutionException.java, messaging/src/main/java/org/axonframework/common/AxonException.java, messaging/src/main/java/org/axonframework/messaging/HandlerExecutionException.java, messaging/src/main/java/org/axonframework/messaging/RemoteHandlingException.java, messaging/src/main/java/org/axonframework/queryhandling/QueryExecutionException.java, messaging/src/test/java/org/axonframework/messaging/HandlerExecutionExceptionTest.java
This pull request reintroduces the changes @dmurat provided in pull request #1905.
Due to an unintentional (force) push to the `master` branch, those changes were overwritten.
As they weren't retrievable directly by commit referral, I  downloaded the source as a zip based on the merge operation within #1905.
More specifically, the status of Axon Framework as depicted [here](https://github.com/AxonFramework/AxonFramework/tree/7fc435b5624ae83ccebbb6df07b937d444617660).
With this in hand, I was able to reintroduce the changes made by @dmurat.
Although this sadly means his user tag is not attached to the commit, I've been careful in naming the commit such that the credentials still point back to @dmurat.
In doing so, this pull request resolves #2454.
=> [#2454] Reintroduce changes from PR #1905

modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java, modelling/src/main/java/org/axonframework/modelling/command/AnnotationCommandTargetResolver.java, modelling/src/test/java/org/axonframework/modelling/command/AnnotationCommandTargetResolverTest.java
This PR replaces the `IdentifierMissingException` in the `AnnotationCommandTargetResolver` for the `IllegalArgumentException`. 
This is a revert compared to 4.6.0, which introduced the `IdentifierMissingException`.
We need to revert this as users may anticipate an `IllegalArgumentException` to be thrown. 
Hence, the introduction of the `IdentifierMissingException` is a breaking change. 
A revert also requires another catch-case on the `AggregateAnnotationCommandHandler` to check the type of `IllegalArgumentException`, to correctly react to the missing identifier scenario.
=> Replace `IdentifierMissingException` in `AnnotationCommandTargetResolver` for `IllegalArgumentException`

disruptor/src/main/java/org/axonframework/disruptor/commandhandling/DisruptorUnitOfWork.java, messaging/src/main/java/org/axonframework/commandhandling/SimpleCommandBus.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/DistributedCommandBus.java, messaging/src/main/java/org/axonframework/common/Registration.java, messaging/src/main/java/org/axonframework/common/caching/AbstractCacheAdapter.java, messaging/src/main/java/org/axonframework/common/caching/Cache.java, messaging/src/main/java/org/axonframework/common/property/PropertyAccessStrategy.java, messaging/src/main/java/org/axonframework/messaging/MessageDispatchInterceptorSupport.java, messaging/src/main/java/org/axonframework/messaging/MessageHandlerInterceptorSupport.java, messaging/src/main/java/org/axonframework/messaging/unitofwork/UnitOfWork.java, messaging/src/main/java/org/axonframework/queryhandling/SimpleQueryBus.java, test/src/main/java/org/axonframework/test/aggregate/StubAggregateLifecycleExtension.java, test/src/main/java/org/axonframework/test/aggregate/StubAggregateLifecycleRule.java
As mentioned in #2456, the use of unregister is incorrect use of the English language. 
Unregister may only be used if something was never registered to begin with. 
All occurrences are, however, describing the removal of an existing registration, which should be called deregister instead.
This pull request adjusts that and in doing so resolves #2456.
=> [#2456] Replace use of unregister for deregister

config/src/main/java/org/axonframework/config/DefaultConfigurer.java, config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/InfraConfigurationTest.java
When implementing the new Spring configuration approach for AF 4.6.0, we adjusted how the `DefaultConfigurer` constructs the default `EventUpcasterChain`. 
It would now look for the "default" components like the chain first.
The `DefaultConfigurer` did not implement this method at all, causing it to revert to the old behavior:
- grouping all `EventUpcaster` components in a single `EventUpcasterChain`. 
However, in the `SpringConfigurer`, this method assumes a single, or otherwise primary, bean to be returned. 
Although this suffices for the majority of Axon's infra components, it does not for the `EventUpcasterChain`.
As mentioned under #2445, users were able to provide several `EventUpcasterChain` in their application context (or on the `DefaultConfigurer` for that matter), which Axon's …
=> [#2445] Revert default `EventUpcasterChain` construction in `DefaultConfigurer`

spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/InfraConfigurationTest.java, spring/src/main/java/org/axonframework/spring/config/MessageHandlerLookup.java
Message Handling Components should adhere to the presence of the `@Order` annotation when in a Spring environment. 
This allows users to impose an ordering on their event handling classes within a given Event Processor.
With the Spring auto wiring changes introduced in 4.6.0, the support around this got lost.
This pull request introduces a similar behavior as present in the (deprecated) `SpringAxonAutoConfigurer` for upcaster beans.
This solution uses an implementation of the `ListableBeanFactory` to check for the existence of the `@Order` annotation.
If present, the value is retrieved. 
Otherwise, we default to `Ordered.LOWEST_PRECEDENCE` to sort the bean on.
We then use these values to sort the bean references in the `MessageHandlerLookup` class, before they're given to the constructor …
=> [#2449] Adhere to Spring's `@Order` annotation for Message Handling Component registration

spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AggregatePolymorphismAutoConfigurationTest.java, spring/src/main/java/org/axonframework/spring/config/SpringAggregateLookup.java
We missed adding the sub-types of a polymorphic aggregate when building the `SpringPrototypeAggregateFactory` in the `SpringAggregateLookup`. 
Due to this, the combination of Axon Framework 4.6.[0..1], Spring Boot and Aggregate polymorphism no longer worked
This pull request fixes that by setting the aforementioned sub-types on the `SpringPrototypeAggregateFactory` when the `SpringAggregateLookup` constructs the factory.
In doing so, this PR resolves #2464.
=> [#2464] Set subtypes on `SpringPrototypeAggregateFactory`

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/QueryProcessingTask.java, config/src/main/java/org/axonframework/config/EventProcessingConfigurer.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/AggregateSnapshotter.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/PostgresEventTableFactory.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/CachingRepositoryWithNestedUnitOfWorkTest.java, messaging/src/main/java/org/axonframework/commandhandling/distributed/ReplyMessage.java, messaging/src/main/java/org/axonframework/common/CollectionUtils.java, messaging/src/main/java/org/axonframework/common/lock/PessimisticLockFactory.java, messaging/src/main/java/org/axonframework/eventhandling/ConcludesBatchParameterResolverFactory.java, messaging/src/main/java/org/axonframework/messaging/unitofwork/UnitOfWork.java, test/src/main/java/org/axonframework/test/aggregate/TestExecutor.java
I found some typos in the Javadocs. These have been resolved in this PR.
=> Fix typos in Javadoc

messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/DeadLetterJpaConverter.java, messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/EventMessageDeadLetterJpaConverter.java, messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/JpaSequencedDeadLetterQueue.java, messaging/src/test/java/org/axonframework/eventhandling/deadletter/jpa/EventMessageDeadLetterJpaConverterTest.java, messaging/src/test/java/org/axonframework/eventhandling/deadletter/jpa/JpaSequencedDeadLetterQueueTest.java
In some cases, differentiation is wanted when serializing a dead letter to the database. This PR allows users to configure an event serializer, and a generic serializer.
The event serializer is used for serialization of the event payload, event metadata, and diagnostics of the Dead letter.
The generic serialize is used for the serialization of the tracking token. 
The builder still has the `serializer()` method and I have decided not to deprecate it. In a lot of cases, setting one serializer for both types is enough.
Closing #2485
=> Allow usage of specific serializers for the JpaDLQ

config/src/main/java/org/axonframework/config/MessageHandlerRegistrar.java, config/src/test/java/org/axonframework/config/DefaultConfigurerTest.java, config/src/test/java/org/axonframework/config/MessageHandlerRegistrarTest.java
The `MessageHandlerRegistrar#shutdown` operation might cause a `NullPointerException` if it wasn't started yet.
Although the chances of this are slim, it does cause noise in the shutdown procedure of a `Configuration`.
As such, we should check whether the `handlerRegistration` is not null before invoking it.
If it's null, we can log the fact it was never started to begin with.
By doing so, we resolve #2481.
=> [#2481] Check `MessageHandlerRegistrar` registration to be non-null

messaging/src/main/java/org/axonframework/tracing/NestingSpanFactory.java, messaging/src/test/java/org/axonframework/tracing/NestingSpanFactoryTest.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/TracingProperties.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/OpenTelemetryAutoConfiguration.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithOpenTelemetryTest.java
Allows handler traces to be child traces of their dispatching trace within a certain time limit.
Can be configured using properties in Spring boot:
```properties
axon.tracing.nested-handlers=true
axon.tracing.nested-time-limit=3m
```
Default to a time limit of two minutes. Within this time limit messages will become part of the dispatching span. After this time, they will become their own span.  This prevents replays from adding activity to ancient spans.
=> Introduce the NestingSpanFactory

messaging/src/main/java/org/axonframework/messaging/annotation/AggregateType.java, messaging/src/main/java/org/axonframework/messaging/annotation/AggregateTypeParameterResolverFactory.java, messaging/src/main/resources/META-INF/services/org.axonframework.messaging.annotation.ParameterResolverFactory, messaging/src/test/java/org/axonframework/messaging/annotation/AggregateTypeParameterResolverFactoryTest.java
@smcvb not sure if this is the proper process, but we found this parameter resolver very useful in our projects. The aggregate type may be needed, if you use aggregate polymorphism, where events are potentially shared across different types. This information might be useful for event handlers, i.e. knowing the originating aggregate type.
=> Added parameter resolver for aggregate type retrieval from domain event messages

integrationtests/src/test/java/org/axonframework/integrationtests/deadline/AbstractDeadlineManagerTestSuite.java, messaging/src/main/java/org/axonframework/deadline/jobrunr/DeadlineDetails.java, messaging/src/main/java/org/axonframework/deadline/jobrunr/JobRunrDeadlineManager.java, messaging/src/test/java/org/axonframework/deadline/jobrunr/DeadlineDetailsSerializationTest.java
Expend the test to make sure the deadline message has the correct timestamp. Improved the JobRunrDeadlineManager by creating the id, instead of taking it from the message. It also no longer stores the original id and original timestamp of the message, as it's not needed.
=> Small test and code improvement for JobRunr deadline manager

messaging-jakarta/pom.xml, messaging/pom.xml, messaging/src/main/java/org/axonframework/deadline/jobrunr/JobRunrDeadlineManager.java, messaging/src/main/java/org/axonframework/eventhandling/scheduling/jobrunr/JobRunrEventScheduler.java, messaging/src/main/java/org/axonframework/eventhandling/scheduling/jobrunr/JobRunrScheduleToken.java, messaging/src/main/java/org/axonframework/eventhandling/scheduling/quartz/QuartzEventScheduler.java, messaging/src/test/java/org/axonframework/eventhandling/scheduling/jobrunr/JobRunrEventSchedulerBuilderTest.java, messaging/src/test/java/org/axonframework/eventhandling/scheduling/jobrunr/JobRunrEventSchedulerTest.java, messaging/src/test/java/org/axonframework/eventhandling/scheduling/jobrunr/JobRunrScheduleTokenTest.java
Last issue to fix https://github.com/AxonFramework/AxonFramework/issues/1106.
Will encapsulate the uuid from Jobrunr for the token and will call one of the `publish` methods, depending on whether there was metadata, to publish the event from JobRunr.
=> Implement the JobRunr implementation of the event scheduler.

messaging/src/main/java/org/axonframework/common/StringUtils.java, messaging/src/test/java/org/axonframework/common/StringUtilsTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AggregatePolymorphismAutoConfigurationTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AggregateStereotypeAutoConfigurationTest.java, spring/src/main/java/org/axonframework/spring/config/SpringAggregateLookup.java
With the recent switch to a newer Spring integration, the naming of the `Repository` and `AggregateFactory` beans.
More specifically, the fully qualified class name of the `@Aggregate` annotated class, combined with `"Repository"` and `"AggregateFactory"` was the bean.
Instead, as in pre-AxonFramework-4.6, the name should be the **simple** name of the `@Aggregate` annotated class, combined with `"Repository"` and `"AggregateFactory"` was the bean.
This pull request rectifies this, by registering the `Repository` and `AggregateFactory` beans through the aforementioned naming scheme.
Doing so, this pull request resolves #2514.
=> [#2514] Fix naming of registered `Repository` and `AggregateFactory` beans

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/InfraConfiguration.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/InfraConfigurationTest.java
This pull request adds `ConditionalOnMissingBean` to the `SpringAxonConfiguration` and `SpringConfigurer` bean creation methods of the `InfraConfiguration` class. 
This will allow users to provide a custom implementation of both beans to override Axon's default behavior.
Doing so, this PR resolves #2383.
=> [#2383] Add `ConditionalOnMissingBean` to `SpringAxonConfiguration` and `SpringConfigurer`

spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/RepositoryWiringTest.java, spring/src/main/java/org/axonframework/spring/config/SpringAggregateLookup.java
First and foremost, this pull request aims to cover the problematic scenarios in #1123.
We assumed that with the recent Spring adjustments (made in 4.6. of Axon Framework), the `NullPointerException` should've been resolved.
This assumption proves to be correct, based on the `RepositoryWiringTest`.
However, as mentioned in #1123, Spring Framework 4 and up should support bean wiring through generics.
This is done internally through the `ResolvableType`, which encapsulates the Java typing system for Spring.
By using the `ResolvableType` to construct a `RootBeanDefinition` in the `SpringAggregateLookup`, and modifying the target type of the `FactoryBean`, we can expose the Aggregate `Repository` beans through their generic aggregate type as well.
Through the above, we feel comfortable that …
=> [#1123] Support `Repository` bean wiring through generics

integrationtests/src/test/java/org/axonframework/integrationtests/cache/CachingIntegrationTestSuite.java, messaging/src/main/java/org/axonframework/common/caching/WeakReferenceCache.java, modelling/src/main/java/org/axonframework/modelling/saga/repository/CachingSagaStore.java, modelling/src/test/java/org/axonframework/modelling/saga/repository/CachingSagaStoreTest.java
The current fix can still trigger the ConcurrentModificationException.
This PR contains a testcase that will reliably create an exception by using the CachingSagaStore directly without modelling intervention. It does so by ending/creating saga's and querying saga's from multiple threads, causing the exception.
It also contains a fix which should be discussed. It introduces locking on the associationsCache.
=> Proposed changes to caching saga fix

config/src/main/java/org/axonframework/config/EventProcessingModule.java, config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java
The `EventProcessingConfigurer#registerTrackingEventProcessorConfiguration(Function<Configuration, TrackingEventProcessorConfiguration>)` did not overrule the default Saga `TrackingEventProcessorConfiguration`.
This is an unintended side effect when we introduced the default configuration for Sagas in issue #1019.
This pull request resolves that by adding the default `TrackingEventProcessorConfiguration` in the map of `TrackingEventProcessorConfigurations` when `EventProcessingConfigurer#registerTrackingEventProcessorConfiguration` is invoked.
This provides a simple location to validate this customization when constructing the `TrackingEventProcessor` and when defining the Saga configuration.
=> Ensure default `TrackingEventProcessorConfiguration` is taken into account for Sagas

integrationtests/src/test/java/org/axonframework/integrationtests/cache/CachedSaga.java, integrationtests/src/test/java/org/axonframework/integrationtests/cache/CachingIntegrationTestSuite.java, messaging/src/main/java/org/axonframework/common/caching/WeakReferenceCache.java, modelling/src/main/java/org/axonframework/modelling/saga/repository/CachingSagaStore.java, modelling/src/test/java/org/axonframework/modelling/saga/repository/CachingSagaStoreTest.java
This pull request does a couple of things:
1. It enhances the `CachedSaga` instance to construct N associations. This is done, as the number of associations may impact the cache invocations
2. It adjusts the `CachingIntegrationTestSuite` to use a `TrackingEventProcessor` instead of a `SubscribingEventProcessor`. This adjustments lets the IT mirror Saga Caching use cases more closely, as we recommend the use of a `StreamingEventProcessor` (like the `TrackingEventProcessor`) to our users. Furthermore, as this makes event handling asynchronous, the validation process is adjusted to wait for the expected amount of events to be handled.
3. It adjusts the `CachingIntegrationTestSuite` to use a custom `Cache.EntryListener` to validate the `Cache` is accessed as expected.
4. It ensures the …
=> Saga Caching Enhancements

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java, messaging/src/main/java/org/axonframework/queryhandling/DefaultQueryGateway.java, messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryGatewayTest.java
The canceling of the completable future result of a direct query should cause the canceling of the query to be propagated to AxonServer too.
=> Cancel of direct query

.github/dependabot.yml, .github/release-notes.yml
Instead of pushing patch upgrades to Axon Framework's patch branch only, this PR adjusts the behavior towards making all adjustments to `master`.
The intent of the patch version to the patch branch was to (1) deal with security fixes quicker and (2) to tag along quicker until a new minor release was made.
The security fixes are something we've decided to be diligent about ourselves.
The fact the last minor release (4.6) took so long is something we're not planning to reiterate anytime soon.
Hence, argument two should be covered as well.
Next to this minor dependabot adjustment, I've added the `dependabot[bot]` user the the ignore list when constructing the release notes.
=> Adjust dependabot behavior

eventsourcing/src/test/java/org/axonframework/eventsourcing/AbstractSnapshotterTest.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/utils/InMemoryAppender.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/utils/RecordingAppender.java, eventsourcing/src/test/resources/log4j2.properties, messaging/src/main/java/org/axonframework/serialization/AbstractXStreamSerializer.java, messaging/src/main/java/org/axonframework/serialization/GapAwareTrackingTokenConverter.java, messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java, messaging/src/test/java/org/axonframework/eventhandling/pooled/WorkPackageTest.java, messaging/src/test/java/org/axonframework/serialization/xml/GapAwareTrackingTokenConverterTest.java, messaging/src/test/java/org/axonframework/utils/DelegateScheduledExecutorService.java, pom.xml, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/SagaCustomizeIntegrationTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/InfraConfigurationTest.java, test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java, test/src/main/java/org/axonframework/test/saga/FixtureExecutionResultImpl.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_Deadlines.java, test/src/test/java/org/axonframework/test/saga/FixtureTest_Deadlines.java
This pull request aims to ensure the build of Axon Framework fully succeeds through all the test cases present.
Although Axon Framework is *already* usable within a JDK17 project, some of the framework's tests took approaches no longer valid in higher version of the JDK.
To sum up, the following adjustments have been made to make Axon Framework `mvn clean install` succeed:
- Removed `Logger` validation from the `AbstractSnapshotterTest`, as this was set through some (undesired) reflective operations. Furthermore, they did not provide any direct benefit for the test case.
- Introduce a `GapAwareTrackingTokenConverter` for the `XStreamSerializer`. This is necessary, as the `GapAwareTrackingToken` uses a `ConcurrentSkipListSet` internally. This is part of `java.util.concurrent`, a package …
=> Several fixes to successfully run a JDK17 build

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java
Until now, heartbeats have been disabled when using the default Axon Server configuration. However, we see many connection problems resolves after enabling this. In order to reduce support calls and customer problems preemptively, this PR enables them by default
=> Enable heartbeats to Axon Server by default

config/src/main/java/org/axonframework/config/Configurer.java, config/src/main/java/org/axonframework/config/DefaultConfigurer.java, config/src/test/java/org/axonframework/config/DefaultConfigurerHandlerRegistrationTest.java, messaging/src/main/java/org/axonframework/messaging/annotation/MultiHandlerDefinition.java, messaging/src/main/java/org/axonframework/messaging/annotation/MultiHandlerEnhancerDefinition.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/InfraConfigurationTest.java
This pull request introduces a method to the `Configurer` to register `HandlerEnhancerDefinitions`. 
The `DefaultConfigurer#defaultHandlerDefinition` operation is adjusted to combine all `HandlerEnhancerDefinitions` registered through the `Configurer` with enhancer definitions originating from the ServiceLoader mechanism.
It does so through construction of the default `HandlerDefinition` through the `ClasspathHandlerDefinition`.
This implementation in turn uses the `ClasspathHandlerEnhancerDefinition` to retrieve enhancers through the ServiceLoader mechanism.
The service-loaded instances and registered instances are flattened into a single collection and given to a new `MultiHandlerDefinition.
Lastly, this PR validates this behavior to work for non-Spring *and* Spring environments.
=> Add `Configurer#registerHandlerEnhancerDefinition`

test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java, test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java, test/src/main/java/org/axonframework/test/aggregate/TestExecutor.java, test/src/test/java/org/axonframework/test/aggregate/FixtureWhenPhaseAggregateInvocationTest.java
This pull request introduces two new when-phase operations:
- `whenConstructing(Callable<T>)`
- `whenInvoking(String, Consumer<T>)`
These when-phase operations allow the users to simulate a test environment where they do not have an annotated command model.
In other words, the `@CommandHandler` annotation is not used on the Aggregate.
Instead, users would wire the `Repository` of their aggregate in a separate class, invoking `Repository#newInstance(Callable<T>)` and `Repository#load(String)` manually before interacting with the Aggregate (of type T).
Although users can register an (annotated-)command handler with the `AggregateTestFixture` that typically performs the `Repository` invocations, having direct Aggregate method operations in the when-phase can be considered as additional user …
=> [#1509] Add `whenConstructing` and `whenInvoking` to the `AggregateTestFixture`

test/src/main/java/org/axonframework/test/saga/FixtureConfiguration.java, test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java, test/src/test/java/org/axonframework/test/saga/FixtureMessageHandlerInterceptorTest.java
This pull request introduces a new operation to the `FixtureConfiguration`: `registerEventHandlerInterceptor(MessageHandlerInterceptor<? super EventMessage<?>>)`.
This new method allows users to register `MessageHandlerInterceptors` for the events passed to their saga event handler.
Registered handler interceptors are combined in an `InterceptorChain`, invoking the Saga event handler as the last entry.
Doing so, we mirror the behavior of the `AbstractEventProcessor` that, in a live system, would invoke the `MessageHandlerInterceptors` for events.
Note that the interceptors are invoked in the order they've been registered in.
With this introduction, users can more closely mirror their entire Saga process within the `SagaTestFixture`.
Doing the above, this pull request resolves #2476.
=> [#2476] Support `EventMessage` handler interceptor registration on the `SagaTestFixture`

messaging/src/main/java/org/axonframework/eventhandling/deadletter/DeadLetteredEventProcessingTask.java, messaging/src/main/java/org/axonframework/messaging/deadletter/DeadLetterParameterResolverFactory.java, messaging/src/main/java/org/axonframework/messaging/unitofwork/CurrentUnitOfWork.java, messaging/src/main/resources/META-INF/services/org.axonframework.messaging.annotation.ParameterResolverFactory, messaging/src/test/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventIntegrationTest.java, messaging/src/test/java/org/axonframework/messaging/deadletter/DeadLetterParameterResolverFactoryTest.java, spring/pom.xml
This pull request introduces a mechanism to resolve the `DeadLetter` as a parameter for message handling methods.
It does so through the `DeadLetterParameterResolverFactory`, which constructs a `DeadLetterParameterResolver<DeadLetter<?>>` whenever the parameter at the given index is of type `DeadLetter<?>`.
The parameter resolver implementation will match for any type of `Message` (as in essence, dead letter support can be built for any type of `Message`).
It will resolve the `DeadLetter<?>` parameter by retrieving it from the `UnitOfWork#resources`.
If there is no active `UnitOfWork` or there is no `DeadLetter` in the resources, the resolver will return `null`.
Hence, the component processing the dead letters (the component initiating the `UnitOfWork`) is required to add the current …
=> [#2351] The `DeadLetter` Parameter Resolver

modelling/src/main/java/org/axonframework/modelling/command/GenericJpaRepository.java, modelling/src/test/java/org/axonframework/modelling/command/GenericJpaRepositoryTest.java
This pull request introduces the `GenericJpaRepository.Builder#disableSequenceNumberGeneration` method.
Invoking this method during the construction of the `GenericJpaRepository` will disable the generation of sequence numbers for events published by the Aggregate store repository manages.
The result of this invocation is that published events will become regular `EventMessages` instead of `DomainEventMessages`. 
The benefit of this is that a user is capable of *reusing* aggregate identifiers whenever they remove a state-stored aggregate instance. 
This follows from the uniqueness constraint present on the `EventStore`, enforcing the combination of aggregate identifier *and* sequence number to be unique.
However, the downside is that the published events can *no longer* be queried based …
=> [#1630] Allow disabling of sequence number generation in the `GenericJpaRepository`

test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java, test/src/test/java/org/axonframework/test/aggregate/FixtureRepositoryRegistrationTest.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_StateStorage.java
This pull request adjusts two pointers around the `AggregateTestFixture's` `Repository` usage:
1. It ensures the registered `Repository` is added to the `resources` collection of the fixture. By adding it to the resources, users are able to wire the `Repository` inside the aggregate or registered annotated command handling components. Since the framework already does this in a production environment, this adjustment allows the fixture to more closely align with the a production setup,
2. A `FixtureExecutionException` is thrown when a `RepositoryProvider`, `ParameterResolverFactory`, `HandlerDefinition` or `HandlerEnhancerDefinition` is registered while the `Repository` is already defined for the fixture. Since all four of these components impact the `Repository` within the fixture, none …
=> [#2129] Fine tune `Repository` registration in the `AggregateTestFixture`

messaging/src/main/java/org/axonframework/eventhandling/pooled/WorkPackage.java, messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
The `TrackingEventProcessor` adds the token and segment into the resources of the `UnitOfwork` while processing. The `PooledStreamingEventProcessor` is still lacking this, while it can be very useful in some cases.
This PR introduces these resources to the `PooledStreamingEventProcessor` in the same way as the `TrackingEventProcessor`
=> Add Segment and Token to UnitOfWork of PooledStreamingEventProcessor

.github/workflows/main.yml, .github/workflows/pullrequest.yml, coverage-report/pom.xml, spring-boot-3-integrationtests/pom.xml
Adding the Spring Boot 3 integration tests to the coverage report, and change the github actions to enable sonar for JDK 17 instead of 11.
This will resolve #2561.
=> [#2561] Move Sonar to JDK17

eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EmbeddedEventStore.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationTest.java, spring/src/test/java/org/axonframework/spring/eventsourcing/benchmark/JpaStorageEngineInsertionReadOrderTest.java
By moving the trigger for the shutdown of the `EmbeddedEventStore` from using an annotation, to implementing `LifeCycle` it's no longer `javax` or `jakarta` specific. This makes sure it always works, and removes the need for a legacy `EmbeddedEventStore`.
Fixes https://github.com/AxonFramework/AxonFramework/issues/2584
=> Fix not calling shutdown on `EmbeddedEventStore` in combination with `javax`

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java
Make `SnapshotFilter` a hard requirement inside the event store configuration. In case there is no `SnapshotFilter`, `AxonConfigurationException` should be thrown.
=> Make SnapshotFilter a hard requirement

modelling/src/main/java/org/axonframework/modelling/saga/PayloadAssociationResolver.java, modelling/src/main/java/org/axonframework/modelling/saga/SagaMethodMessageHandlerDefinition.java, modelling/src/main/java/org/axonframework/modelling/saga/StartSaga.java, modelling/src/test/java/org/axonframework/modelling/saga/PayLoadAssociationResolverTest.java, modelling/src/test/java/org/axonframework/modelling/saga/SagaMethodMessageHandlerDefinitionTest.java, modelling/src/test/java/org/axonframework/modelling/utils/ConcurencyUtils.java, modelling/src/test/java/org/axonframework/modelling/utils/ConcurrencyUtils.java
This pull request switches to use a `ConcurrentHashMap` for the `PayloadAssociationResolver` and the `SagaMethodMessageHandlerDefinition`.
Furthermore, tests are added to validate both classes to be thread-safe.
In doing so, this pull request resolves #2555.
=> [#2555 Switch to `ConcurrentHashMap` in Saga related classes

modelling/src/main/java/org/axonframework/modelling/saga/repository/CachingSagaStore.java, modelling/src/test/java/org/axonframework/modelling/saga/repository/CachingSagaStoreTest.java
This pull request introduces a test case to reproduce a `ConcurrentModificationException` through the `AnnotatedSagaRepository#find` method.
This exception only occurs in particularly heavy use cases of the Saga utilizing a `CachingSagaStore`.
This follows from the returned saga identifiers collection from the `CachingSagaStore`.
Although a synchronized collection (through Collections#synchronized`) was returned, this approach expects *all* usages of the wrapped set to go through it.
As we cannot guarantee this, it is safer to construct a new thread-safe set based on the retrieved saga identifiers.
=> Ensure retrieved Saga Identifiers collection is thread-safe

.github/workflows/dependabot-automation.yml
This pull request aims to further automize Dependabot pull requests.
Earlier, we introduced automation to approve pull requests.
The adjustments below aim to automatically merge pull requests originating from the "actor" `dependabot[bot]`.
Note that part of this pull request is branch protection settings within this repository, which since they are GitHub settings cannot be part of the PR.
These settings require a successful run of the JDK8, JDK11, and JDK17 builds for a given pull request. 
So when any of the three fails, the branch protection rule ensures the pull request cannot be automatically merged.
Furthermore, to minimize the impact of this automation, for now, I've set it to only act on patch version increments.
This is done through the `if` block validating whether the …
=> Add an auto-merge step for Dependabot Pull Request

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/AxonServerCommandBus.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java, coverage-report/pom.xml
During the last change for OpenTelemetry on 4.6.x branch, an error was made by wrapping the response processing task in a span that is then executed multiple times. This wrap has been removed, and the span is now started by the task itself when appropriate.
For all makeCurrent calls, we now use try-with-resources statements. That ensures scopes are closed even when exceptions occur while the bus is shutting down or a dispatch interceptor throws an exception.
=> Fix OpenTelemetry support on queries

modelling/src/main/java/org/axonframework/modelling/command/AbstractRepository.java, modelling/src/main/java/org/axonframework/modelling/command/Repository.java
This pull request does two things:
1. Expand the `Repository` JavaDoc to clarify the expectation of an active `UnitOfWork` containing a `CommandMessage` implementation. If there's no active `UnitOfWork` and `IllegalStateException` is thrown (by the `CurrentUnitOfWork`).
2. Add WARN-level logging to the `AbstractRepository`, validating whether the active `UnitOfWork` does not contain a `CommandMessage`. If it does not, that signals `Repository` invocation from an Event Handler or Query Handler, making it so that the context is unexpected down the line.
Point two specifically helps to resolve #2611, wherein an end-user invoked the `Repository` from within an `@EventHandler` annotated method.
This succeeded on the fact a `UnitOfWork` is active, but further down the line in Aggregate command …
=> [#2611] Clarify active `UnitOfWork` expectation in the `Repository`

integrationtests/src/test/java/org/axonframework/integrationtests/deadline/AbstractDeadlineManagerTestSuite.java
This pull request adds a test to the `AbstractDeadlineManagerTestSuite` validating that correlation data is propagated when a deadline is scheduled.
to that end, a test is added for both Aggregate and Saga scheduling.
Through this, I've confirmed that a vanilla configuration of the `SimpleDeadlineManager` correctly retrieves correlation data.
This PR thus resolves #2620, describing this not to work  for the `SimpleDeadlineManager`.
=> [#2620] Test correlation data population for `DeadlineManager` implementations

test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java, test/src/main/java/org/axonframework/test/aggregate/FixtureConfiguration.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_Annotated.java
This pull request ensures that `AggregateTestFixture#andGivenCurrentTime` can follow up `AggregateTestFixture#given` without losing the given events.
The fix is luckily quite easy: move the `clearGivenWhenState` method to the `AggregateTestFixture#givenCurrentTime`.
In doing so, this pull request resolves #2604.
=> [#2604] Ensure `given(Object...)` can be followed up by `andGivenCurrentTime`

migration/README.md, migration/src/main/resources/META-INF/rewrite/axon-jakarta-47.yml, migration/src/main/resources/META-INF/rewrite/axon-javax-47.yml
Noticed this step was missing when upgrading https://github.com/Axoniq/hotel-demo .
Figured add the Spring Boot upgrade command to the README as well, as it was only on the blog.
Hotel-demo migrates successfully using only the command in the README now for me.
=> Include dependency upgrades with migration

axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreTest.java, messaging/src/main/java/org/axonframework/eventhandling/AbstractEventBus.java, tracing-opentelemetry/src/main/java/org/axonframework/tracing/opentelemetry/OpenTelemetrySpan.java
When a command handler applies an event and stages events for publication in the UoW, but then fails, an error is logged by Axon Framework: Span was attempted to be ended while not started yet
This is because the cleanup phase (that ends the span) is called even when the span is not started. Since it's nearly impossible to tell what has been executed and what hasn't, the commit span has been split up for each phase in the UnitOfWork - preCommit, commit and postCommit.
Last but not least, the error logs have been reduced to warn - we can handle the issues gracefully.
=> Fix OpenTelemetry warning

integrationtests/src/test/resources/log4j2.properties, messaging/src/main/java/org/axonframework/eventhandling/tokenstore/inmemory/InMemoryTokenStore.java, messaging/src/test/resources/log4j2.properties, modelling/src/test/resources/log4j2.properties, spring-boot-3-integrationtests/src/test/resources/log4j2.properties, spring-boot-autoconfigure/src/test/resources/log4j2.properties, spring/src/test/resources/log4j2.properties
End users are often surprised when an event processor rereads events when no persistent token store is configured. The warning will help them to notice why this is the case earlier.
=> Add a warning to the creation of the in memory token store.

metrics-micrometer/src/main/java/org/axonframework/micrometer/GlobalMetricRegistry.java, metrics-micrometer/src/test/java/org/axonframework/micrometer/GlobalMetricRegistryTest.java
The latency per payload type makes no sense to track for an event processor. When monitoring this metric, this will make the value dependent on the rate of certain types of events.
For example, when an event only takes place once a week, and is delayed because of an error, this metric will stay at a high value for the remainder of the week
=> Remove payloadType tag from EventProcessorLatencyMetric

spring/src/main/java/org/axonframework/spring/config/BeanHelper.java, spring/src/main/java/org/axonframework/spring/config/SpringAggregateLookup.java, spring/src/main/java/org/axonframework/spring/modelling/SpringRepositoryFactoryBean.java, spring/src/test/java/org/axonframework/spring/config/BeanHelperTest.java
The combination of a FactoryBean, defining a targetType on the bean definition and Spring AOT caused problems. As the FactoryBean wasn't strictly required to retrieve a Repository, it has been replaced by a static method.
=> Spring AoT fix

config/src/main/java/org/axonframework/config/EventProcessingModule.java, config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java, messaging/src/main/java/org/axonframework/eventhandling/deadletter/DeadLetteredEventProcessingTask.java, messaging/src/main/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventHandlerInvoker.java, messaging/src/test/java/org/axonframework/eventhandling/deadletter/DeadLetteredEventProcessingTaskTest.java, messaging/src/test/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventHandlerInvokerTest.java, messaging/src/test/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventIntegrationTest.java
Handler Interceptor support for Dead Letter Processing, using the same interceptors as the processing group.
Fixes https://github.com/AxonFramework/AxonFramework/issues/2639
=> [#2639] Handler Interceptor support for Dead Letter Processing

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerBusAutoConfiguration.java
When using other libraries, like Inspector Axon, the right `SpanFactory` is not picked up.
In the old situation, it received a `NoOpSpanFactory` through the `SpanFactory` parameter, while the `Configuration` contains an `InspectorSpanFactory` and got the right one. 
This is probably due to bean initialization ordering. This has been corrected by always using `Configuration.spanFactory`
=> Fix autoconfiguration not picking up SpanFactory for AxonServerQueryBus 4.6

messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java, messaging/src/main/java/org/axonframework/eventhandling/pooled/WorkPackage.java, messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
Fixes https://github.com/AxonFramework/AxonFramework/issues/2694
=> Wait till processing is done until setting the caughtUp flag for the PooledStreamingEventProcessor.

config/src/main/java/org/axonframework/config/EventProcessingModule.java
Make Configuration protected, so it's accessible by other components that extend EventProcessingModule. 
Change needed for multi tenancy extension
=> Make Configuration accessible

metrics-micrometer/src/main/java/org/axonframework/micrometer/EventProcessorLatencyMonitor.java, metrics/src/main/java/org/axonframework/metrics/EventProcessorLatencyMonitor.java
The `EventProcessorLatencyMonitor` JavaDoc incorrectly depicts the intent of the monitor, which changed in December 2020.
With the provided changes, the documentation correctly describes that the monitored time is the time difference between the `EventMessage#getTimestamp` and the current time.
=> Adjust the JavaDoc of the `EventProcessorLatencyMonitor`

config/src/main/java/org/axonframework/config/EventProcessingModule.java, config/src/test/java/org/axonframework/config/SagaConfigurerTest.java, coverage-report/pom.xml, hibernate-6-integrationtests/pom.xml, spring-boot-3-integrationtests/pom.xml
This fixes the problem of having multiple saga handlers for the same saga. By switching to a map, only the last one is kept. Making it possible to do custom overrides in Spring without creating duplications.
=> When registering the same Saga multiple times, only the last one is kept.

spring-boot-3-integrationtests/src/test/java/org/axonframework/springboot/JpaAutoConfigurationTest.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/TokenStoreProperties.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JdbcAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/legacyjpa/JpaJavaxAutoConfiguration.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/JdbcAutoConfigurationTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/legacyjpa/JpaJavaxAutoConfigurationTest.java
Fixes https://github.com/AxonFramework/AxonFramework/issues/2708.
This will also need to be implemented in the Mongo and Kafka extensions for consistency. This is easiest done after this has been merged.
=> Make the token store claim timeout easily configurable.

.github/workflows/main.yml, .github/workflows/pullrequest.yml
This PR adds the [test-summary](https://github.com/test-summary/action) step for pull requests.
In doing so, this PR resolves #2228.
=> Add `test-summary` step

config/src/main/java/org/axonframework/config/EventProcessingModule.java, config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java
When using the `registerPooledStreamingEventProcessor` function, it will not take effect for saga's, since the EventProcessingModule overwrites the config because it sets it to the default TEP one.
=> Fix Inititalization of PSEP when using Saga

test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java, test/src/main/java/org/axonframework/test/aggregate/Reporter.java, test/src/main/java/org/axonframework/test/deadline/DeadlineManagerValidator.java, test/src/main/java/org/axonframework/test/saga/CommandValidator.java, test/src/main/java/org/axonframework/test/saga/EventValidator.java, test/src/main/java/org/axonframework/test/saga/RepositoryContentValidator.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_MatcherParams.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_RegularParams.java
Ensure all assertion messages thrown by Axon Framework's test fixtures are aligned. 
As part of this, align the `actual` and `expected` values on separate lines for clarity to the user.
In doing so, this PR resolves #2755.
=> [#2755] Align assertion messages

config/src/main/java/org/axonframework/config/EventProcessingModule.java, messaging/src/main/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventHandlerInvoker.java, messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/DeadLetterEntry.java, messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/JpaDeadLetter.java, messaging/src/main/java/org/axonframework/eventhandling/deadletter/legacyjpa/JpaDeadLetter.java, messaging/src/main/java/org/axonframework/messaging/deadletter/GenericDeadLetter.java, messaging/src/main/java/org/axonframework/messaging/deadletter/ThrowableCause.java, messaging/src/test/java/org/axonframework/eventhandling/deadletter/DeadLetteringEventIntegrationTest.java, messaging/src/test/java/org/axonframework/messaging/deadletter/ThrowableCauseTest.java
The `Cause` generated by the `SequencedDeadLetterQueue` implementations may exceed the desired column width for the `causeMessage` field.
To resolve this predicament, I've added three operations to the `ThrowableCause` (the default `Cause` implementation used):
1. `asCause(Throwable)` - Check whether the given `Throwable` is an instance of `ThrowableCause`. If `true`, return as is. If `false`, wrap the `Throwable` in a `ThrowableCause`.
2. `truncate(Throwable)` - Truncates the `Throwable#getMessage` to a maximum size of `1023`. 
3. `truncate(Throwable, int)` - Truncates the `Throwable#getMessage` to the given `int` messageSize`.
On top of this, the default `EnqueuePolicy` as configured in the `EventProcessingModule` and `DeadLetteringEventHandlerInvoker` now truncates the given …
=> [#2752] Truncate `Cause` message to fit default column width

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/EventProcessorControlServiceTest.java
This pull request introduces a property-based configuration of load-balancing strategies. 
This is done by expanding the `AxonServerConfiguration` with `EventProcessingConfiguration` (added under `axon.axonserver.eventhandling` to align with regular event processing configuration).
The `EventProcessingConfiguration`, in turn, contains `ProcessorSettings` and a `LoadBalancingStrategy`, reflecting the options "disabled" and "thread number."
The properties are, in turn, used by the `EventProcessorControlService` to set the configured load balancing strategy through the `AdminChannel`.
When an event processor or token store identifier cannot be found, information is logged to the user.
Similarly, when requesting to set load-balancing strategies through the `AdminChannel`, both successes and …
=> Allow property based configuration of load balancing strategies

axon-server-connector/pom.xml, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/StreamingQueryEndToEndTest.java, integrationtests/src/test/java/org/axonframework/integrationtests/axonserverconnector/MessagePriorityIntegrationTest.java, test/pom.xml, test/src/main/java/org/axonframework/test/server/AxonServerContainer.java, test/src/main/java/org/axonframework/test/server/AxonServerContainerUtils.java, test/src/main/java/org/axonframework/test/server/AxonServerEEContainer.java, test/src/main/java/org/axonframework/test/server/AxonServerSEContainer.java, test/src/test/java/org/axonframework/test/server/AxonServerContainerTest.java
As of Axon Server 2023.0.0, there are no longer combined releases of Axon Server Standard Edition and Axon Server Enterprise Edition.
Instead, there is now a single runnable that allows single-node mode and multi-node mode.
Due to this shift, the existence of `AxonServerSEContainer` and `AxonServerEEContainer` isn't very reasonable anymore.
As such, this pull request introduces the `AxonServerContainer`; essentially a merger and minor clean-up of the previous containers.
Next to the new container, we have included the `AxonServerContainerUtils`, which allows simplified operation towards cluster initialization, context creation, and context deletion.
Lastly, test cases constructed their own `GenericContainer` of the Axon Server image are reverted to use the new `AxonServerContainer`.
=> Introduce `AxonServerContainer` as test-container

modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedAggregateMetaModelFactory.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_Hierarchy.java
This pull request resolves a predicament within the registration of Command Handling functions on entities within an Aggregate class hierarchy.
The `AnnotatedAggregateMetaModelFactory#prepareChildEntityCommandHandlers`  did investigate one layer down the hierarchy for existing Aggregate Members to register its Command Handling functions with the top Aggregate.
But, it would stop as soon as it had found **any**.
Hence, if there was another layer deeper down the Aggregate hierarchy that contained `@AggregateMember` annotated fields with command handlers in them, those would be disregarded.
I have solved the predicament by having the `AnnotatedAggregateMetaModelFactory#prepareChildEntityCommandHandlers` operation move further down the class hierarchy until it reaches the `Object`.
The …
=> Ensure Aggregate Member Command Handlers are retrievable in complex Aggregate Hierarchy

messaging/src/main/java/org/axonframework/queryhandling/DefaultQueryGateway.java, messaging/src/test/java/org/axonframework/queryhandling/DefaultQueryGatewayTest.java
The streaming query operation on the `QueryGateway` did not take into account that you may want to provide a `Message` instead of an `Object`.
The specific use case is to be able to provide custom `MetaData` for specific gateway operations.
As we support this throughout the other gateways, it's only feasible that `QueryGateway#streamingQuery` supports it too.
=> Enable provisioning a `Message` with custom `MetaData` for `QueryGateway#streamingQuery`

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/command/CommandSerializer.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/QuerySerializer.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/SubscriptionMessageSerializer.java, modelling/src/main/java/org/axonframework/modelling/command/AbstractRepository.java
This pull request adds additional logging in conceptually two spots of the framework:
1. Whenever loading or creation fails on the Repository
2. Whenever an exception is serialized to be sent back to the dispatcher
For spot one, the `AbstractRepository` wraps the `doLoad`, `doCreateNew`, and `doLoadOrCreate` operations in a try-catch block.
This ensures that it is clearer to the user the `Repository` failed in loading/constructing an aggregate.
Scenario two is covered by adjusting the `CommandSerializer`, `QuerySerializer`, and `SubscriptionQuerySerializer` (these serializers are Axon Server specific).
These serializers will serialize `HandlerExecutionException` details if they are present.
It is these details that the user is suggested to fill to provide exception info (details) to the …
=> Log when `HandlerExecutionException#details` are missing and on `AbstractRepository` failures

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerBusAutoConfiguration.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfigurationTest.java
With this `axon.axonserver.event-store.enabled=false` can be used to easily leverage Axon Server as command and query router, while not creating an `EventStore` or `EventScheduler` bean using Axon Server.
=> Add property to easily disable using Axon Server as event store.

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/EventProcessorControlServiceTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/LoadBalancingStrategyAutoConfigurationTest.java
Although Spring resolved the name for the load balancing properties based on the `@ConfigurationProperties` annotation on the getter of the `AxonServerConfiguration.EventHandlingConfiguration`, it was unable to set the properties in this format. 
I assume this has to do with the discrepancy between the defined property and the field and its getter/setter.
To keep the property path name that's already propagated throughout our user base, I've opted to rename the `AxonServerConfigurationEventProcessorConfiguration` to `AxonServerConfiguration`Eventhandling`.
By doing so, we align with the path `"axon.axonserver.eventhandling"`. 
Although we should strictly regard this as a breaking change, I think the chances are minimal somebody interacts with the object, i.o. through a property file.
Next …
=> Fix property-based Load Balancing Strategy configuration bug

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModule.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreFactory.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModuleTest.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStoreFactoryTest.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerBusAutoConfiguration.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithMetricsWithoutConfigurerTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfigurationTest.java
This pull request introduces the so-called `AxonServerEventStoreFactory`.
The intent of this component is to be able to more easily construct a publication path to a different context.
For example, whenever a user utilizes the multi-context feature from Axon Server, there's a chance they use a so-called "integration context."
Without this functionality, you are required to construct an `AxonServerEventStore` instance from scratch, retrieving all the store's components.
The `AxonServerEventStoreFactory` simplifies this by providing the `constructFor(String context)` operation.
By default, the `AxonServerEventStoreFactory` is configured with the same components as the `AxonServerEventStore`.
As such, by invoking `AxonServerEventStoreFactory#constructFor(String context)`, you construct a …
=> Introduce the `AxonServerEventStoreFactory`

axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/StreamingQueryEndToEndTest.java, integrationtests/src/test/java/org/axonframework/integrationtests/axonserverconnector/MessagePriorityIntegrationTest.java, test/src/main/java/org/axonframework/test/server/AxonServerContainer.java, test/src/test/java/org/axonframework/test/server/AxonServerContainerTest.java
This pull request adds a default constructor for the `AxonServerContainer`.
In doing so, users can base themselves on the default container the Axon Server team provides for their tests.
Next to adding the container, the Framework's tests using the container are adjusted to use the default constructor, too (where feasible).
=> Add default constructor for the `AxonServerContainer` 

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/subscription/SubscriptionMessageSerializer.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConfigurationTest.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/command/AxonServerCommandBusTest.java
This pull request resolves numerous minor and greater predicaments found in the `AxonServerConfiguration`.
Some of these may be regarded as bugs, whilst others are more enhancements.
Here's a list of the made adjustments, decreasing in importance:
1. Actually set the `commandPermits` on the `AxonServerConnectionFactory` constructed in the `AxonServerConnectionManager`, based on the command flow control of the `AxonServerConfiguration`.
2. Actually set the `queryPermits` on the `AxonServerConnectionFactory` constructed in the `AxonServerConnectionManager`, based on the command flow control of the `AxonServerConfiguration`.
3. Deprecate the suppress download message property on the `AxonServerConfiguration`, as the control over this message resides fully with the …
=> Fix inconsistencies around the `AxonServerConfiguration` 

messaging/src/main/java/org/axonframework/eventhandling/deadletter/jdbc/DefaultDeadLetterStatementFactory.java, messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/JpaSequencedDeadLetterQueue.java, messaging/src/main/java/org/axonframework/eventhandling/deadletter/legacyjpa/JpaSequencedDeadLetterQueue.java, messaging/src/test/java/org/axonframework/eventhandling/deadletter/jdbc/JdbcDeadLetteringEventIntegrationTest.java, messaging/src/test/java/org/axonframework/messaging/deadletter/SequencedDeadLetterQueueTest.java, spring-boot-3-integrationtests/src/test/java/org/axonframework/spring/eventhandling/deadletter/SpringJpaDeadLetteringIntegrationTest.java, spring/src/test/java/org/axonframework/spring/eventhandling/deadletter/SpringJpaDeadLetteringIntegrationTest.java
The JavaDoc of the `SequencedDeadLetterQueue#deadLetterSequence(String)` method states the following:
```java
/**
* Return all the {@link DeadLetter dead letters} for the given {@code sequenceIdentifier} in insert order.
*
* @param sequenceIdentifier The identifier of the sequence of {@link DeadLetter dead letters}to return.
* @return All the {@link DeadLetter dead letters} for the given {@code sequenceIdentifier} in insert order.
*/
```
However, the JPA and JDBC implementations of the `SequencedDeadLetterQueue` did not enforce any ordering open retrieval of the dead letters for a given sequence identifier.
This pull request rectifies that, by adding a test to the unit test suite, and integration tests for the JDBC, JPA, and legacy JPA implementation of the `SequencedDeadLetterQueue`. …
=> Ensure insert order is maintained for `SequencedDeadLetterQueue#deadLetterSequence(String)` invocations

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java
The configuration file would complain about not being able to inspect the AxonServerConnectionDetails class, as it implements the ConnectionDetails interface. This commit separates the beans into nested configuration files with proper Classpath conditions to ensure only compatible beans are considered.
=> Resolve classloading issue with ConnectionDetails

pom.xml
This is required for Spring AOT and may also help other cases where reflection is used to retrieve parameter names.
=> Instruct compiler to include parameter names metadata

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/InfraConfiguration.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/InfraConfigurationTest.java
When using Spring Boot autoconfiguration, only Spring's bean orderings mechanism  was taken into account. This commit adds sorting based on the ConfigurerModule's order, followed by Spring's ordering mechanism.
Resolves #2845
=> [#2845] Ensure ConfigurerModulue order is respected in Spring Autoconfiguration

integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/TrackingEventProcessorTest.java, messaging/src/main/java/org/axonframework/eventhandling/StreamingEventProcessor.java, messaging/src/main/java/org/axonframework/eventhandling/TrackingEventProcessor.java, messaging/src/main/java/org/axonframework/eventhandling/pooled/ClaimTask.java, messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java, messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java, messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
In order to provide smoother Event Processor operations in the Framework going forward, we have decided to implement a specific action that claims a token for a processor.
Previously, moving processing from one instance to another could only be done by releasing the segment on all instances but the desired, and awaiting the token claim interval of the desired instance. This led to a prolonged period of not processing of events, which is undesirable.
The action will be handled in the context of the processor and claim the token in the store. Then upon the next WorkerLauncher/Coordinator operation (which is queued at the same time) processing of it will start. This works both for the PSEP and the TEP.
Fixes #2803
=> Implement StreamingEventProcessor.claimSegment

spring-boot-3-integrationtests/pom.xml, spring-boot-3-integrationtests/src/test/java/org/axonframework/springboot/TrackingEventProcessorIntegrationTest.java, spring-boot-3-integrationtests/src/test/java/org/axonframework/springboot/service/connection/SpringBootDockerComposeIntegrationTest.java
Because of an earlier change, we were testing against Spring Boot 2. Two tests are failing, which need to be looked into. They are disabled for now to be sure Github actions run fine.
The problem seems to be that the `JpaEventStoreAutoConfiguration` isn't working. But its not clear to me why.
=> Execute the axon-spring-boot-3-integrationtests actually with spring 3

hibernate-6-integrationtests/pom.xml, pom.xml, spring-boot-3-integrationtests/pom.xml, tracing-opentelemetry/pom.xml
This pull request upgrades the following dependencies:
* Update hsqldb from 2.5.2 to 2.7.2 for the hibernate-6 and spring-boot-3 modules **only**
* Update hibernate from 5.6.14 to 5.6.15
* Update hibernate-6 from 6.1.6 to 6.3.1
* Update postgresql from 42.5.1 to 42.6.0
* Update gson from 2.8.9 to 2.10.1
* Update jakarta persistence from 3.0.0 to 3.1.0 for the hibernate-6 and spring-boot-3 modules **only**
* Update jackson from 2.13.4 to 2.14.3
* Update db-scheduler from 11.7 to 12.5.0
* Update spring-security from 5.7.3 to 5.8.7
* Update junit jupiter from 5.9.1 to 5.10.0
* Update hibernate validator from 8.0.0 to 8.0.1
* Update opentelemtry from 1.19.0 to 1.30.1
* Update msql-connector from 8.0.30 to 8.0.33
We would've expected `dependabot` to have made these changes, but for some reason …
=> Several dependency upgrades

.github/workflows/main.yml, .github/workflows/pullrequest.yml, pom.xml
This pull request adds JDK21 to the GitHub actions for merged code in `master` and pull requests.
In doing so, we keep validating whether Axon Framework works with the most commonly used versions of Java.
Although issue #2710 is specific on Virtual Thread support, I still feel it's feasible to see this PR as part of that effort.
=> Add JDK21 to GitHub Actions

spring/src/main/java/org/axonframework/spring/config/SpringConfigurer.java, spring/src/test/java/org/axonframework/spring/config/SpringConfigurerTest.java
This pull request adjusts the `SpringConfigurer.ComponentLocator` to take into account beans may originate from ancestor Spring Contexts.
Furthermore, when it has found bean names, it assumes it may need a merged bean definition.
Next to the adjustments in the `SpringConfigurerTest`, I have tested the changes against [my sample project](https://github.com/smcvb/gamerental) and the sample provided in #2855, with success.
In doing the above, this pull request resolves #2855.
=> [#2855] Support Hierarchical Spring Contexts within `SpringConfigurer.ComponentLocator`

spring-boot-3-integrationtests/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerPropertiesTest.java, spring-boot-3-integrationtests/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerTest.java, spring-boot-3-integrationtests/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithHibernateTest.java, spring-boot-3-integrationtests/src/test/java/org/axonframework/springboot/JpaEventStoreAutoConfigurationWithAxonServerTest.java, spring-boot-3-integrationtests/src/test/java/org/axonframework/springboot/JpaEventStoreAutoConfigurationWithSnapshottingTest.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JdbcAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaEventStoreAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/legacyjpa/JpaJavaxEventStoreAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/util/RegisterDefaultEntities.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/SagaCustomizeIntegrationTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/legacyjpa/JpaEventStoreAutoConfigurationWithAxonServerTest.java
This pull request checks whether the property `axon.axonserver.enabled` is consciously set to `false`.
Only when that is the case will the autoconfiguration try to construct a `JpaEventStorageEngine` bean (either `javax` or `jakarta`, depending on whether the Spring Boot version is 2 or 3 respectively), or a `JdbcEventStorageEngine` whenever the JPA version didn't succeed.
As a side effect, this change ensures that users combining Axon Framework, JPA, and Axon Server, do not automatically receive or have to validate the existence of the `domain_event_entry` and `snapshot_entry` tables.
This follows from the (Axon Framework-specific) `@RegisterDefaultEntities` annotation, that is triggered in conjunction with the introduced `@ConditionalOnExpression("${axon.axonserver.enabled:true} == …
=> Disable JPA and JDBC `EventStorageEngine` creation when Axon Server is enabled

eventsourcing/src/main/java/org/axonframework/eventsourcing/EventSourcedAggregate.java, modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedAggregate.java
Work in Progress for discussion.
A customer of ours had difficulties due to Jackson not being able to find the fields of an aggregate for a snapshot. This is the third customer I helped with this, and can cause a lot of confusion.
This PR will extend the `EventSourcedAggregate` exception to throw a more specific exception to the situation if it detects the aggregate identifier to be null if the event that is being applied is a snapshot. 
Tests will be added after we verify the approach.
=> Detect empty snapshots due to Serializer misconfiguration

.github/workflows/main.yml, .github/workflows/pullrequest.yml, messaging/src/main/java/org/axonframework/eventhandling/async/EventProcessorTask.java, pom.xml
This pull request adjusts some basic things in Axon Framework to move to JDK21, like:
- Changing the `maven-compiler-plugin` source and target
- Changing the `maven-enforcer-plugin` required version
- Dropping the JDK11 and JDK17 module configuration
- Adjusting the `main` and `pullrequest` GHA to only use JDK21
- Replacing the use of `yield()`, as that's a reserved word (since I believe JDK13)
This PR can be seen as a preparation to remove Javax from the project, as well as **all** deprecated code.
=> Move to JDK21

config/src/main/java/org/axonframework/config/Configurer.java, config/src/main/java/org/axonframework/config/ModuleConfiguration.java, config/src/main/java/org/axonframework/config/SagaConfigurer.java
This pull request removes all deprecated code from the `config` module.
Noteworthy drops are:
* The `registerCommandHandler` and `registerQueryHandler` methods from the `Configurer` using a phase, as lifecycle logic should not reside here.
* The start, shutdown, and phase methods of the `ModuleConfiguration, as lifecycle logic no longer resides here.
* Drop the deprecation mention on a concrete method. The exposed `SagaConfiguration#eventProcessor` still has value. Furthermore, if removing the deprecation warning proves incorrect: the chances are high the configuration will be adjusted quite heavily any how.
=> Remove all deprecated code from the `config` module

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/AxonServerEventStore.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java
This pull request ensures that the assertion done in the `JpaEventStorageEngine`, `JdbcEventStorageEngine`, and `AxonServerEventStore.AxonIQEventStorageEngine` all three do a similar assert.
Although the JPA and JDBC versions already shared the "wrong" token they received, the Axon Server version did not.
With this change, all three share what they expect and what they got, in similar wording.
=> Align the `TrackingToken` assert for JPA, JDBC, and AxonServer

axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/QueryProcessingTaskIntegrationTest.java, disruptor/src/main/java/org/axonframework/disruptor/commandhandling/DisruptorCommandBus.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/GenericAggregateFactory.java, integrationtests/pom.xml, messaging/src/main/java/org/axonframework/commandhandling/distributed/AnnotationRoutingStrategy.java, messaging/src/main/java/org/axonframework/common/ReflectionUtils.java, messaging/src/main/java/org/axonframework/common/property/MethodAccessedProperty.java, messaging/src/main/java/org/axonframework/eventhandling/ReplayToken.java, messaging/src/main/java/org/axonframework/eventhandling/scheduling/ScheduleToken.java, messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedMessageHandlingMember.java, messaging/src/main/java/org/axonframework/serialization/json/JacksonSerializer.java, messaging/src/test/java/org/axonframework/common/ReflectionUtilsTest.java, messaging/src/test/java/org/axonframework/serialization/json/JacksonSerializerTest.java, messaging/src/test/java/org/axonframework/serialization/json/MetaDataDeserializerTest.java, modelling/src/main/java/org/axonframework/modelling/command/AnnotationCommandTargetResolver.java, modelling/src/main/java/org/axonframework/modelling/command/NoArgumentConstructorCreationPolicyAggregateFactory.java, modelling/src/main/java/org/axonframework/modelling/saga/AbstractResourceInjector.java, pom.xml, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/EventProcessorConfigurationTest.java, test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java, test/src/main/java/org/axonframework/test/server/AxonServerContainerUtils.java, test/src/test/java/org/axonframework/test/matchers/EqualFieldsMatcherTest.java
This pull request resolves warnings that pop up during the build of the project.
The majority of these are deprecation warnings, of which most are resolved.
The noteworthy leftover deprecation in Axon Framework is our own `ReflectionUtils`, which requires some investigation (as drafted up in #2901).
=> Resolve warnings within the build

spring-boot-3-integrationtests/pom.xml
For some reason, the version was pinned to 4.9.0-SNAPSHOT, causing tests to fail.
=> Integration test should use current Axon version

spring-boot-3-integrationtests/src/test/java/org/axonframework/springboot/TrackingEventProcessorIntegrationTest.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JdbcAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaEventStoreAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/legacyjpa/JpaJavaxEventStoreAutoConfiguration.java
Fixed the ordering of AutoConfiguration to remove the need of the `axon.axonserver.enabled` property to enable alternatives of AxonServer when the connector is not on the classpath.
=> Removed requirement for property to disable AxonServer EventStore and enable another one

eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngine.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngine.java, messaging/src/main/java/org/axonframework/eventhandling/GapAwareTrackingToken.java, messaging/src/test/java/org/axonframework/eventhandling/GapAwareTrackingTokenTest.java
When using a JPA or JDBC based event store, the tracking token need to track gaps to avoid missing events in uncommitted rows in the table. The creation of tokens in the presence of large gaps was inefficient. This caused a large number of java objects to be created, even though these gaps did not need to be tracked. Deleting events and performing a replay would have the same effect.
This commit changes how gaps are copied between tracking tokens, reducing the number of entries in TreeSets and therefor reducing the number of created objects.
=> Resolved apparent memory leak in GapAwareTrackingToken

test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java, test/src/test/java/org/axonframework/test/saga/StubSaga.java
This change allows annotated Sagas that rely on the TrackingToken parameter in their event handler methods to be tested with the Saga Test Fixture. Each event is wrapped in a TrackedEventMessage with a monotonically increasing sequence number.
=> Added support for TrackingToken parameter in SagaTestFixture

migration/README.md, migration/pom.xml, migration/src/main/resources/META-INF/rewrite/axon-jakarta-4.yml, migration/src/main/resources/META-INF/rewrite/axon-javax-4.yml, migration/src/test/java/org/axonframework/migration/AxonJakartaTest.java, migration/src/test/java/org/axonframework/migration/AxonJavaxTest.java
Seeing how there's been no breaking changes, yet still quite some releases on 4.x since 4.7, I figured update the existing recipes to pick up any 4.x version going forward.
=> Automate migration to Axon 4.9+

test/src/main/java/org/axonframework/test/aggregate/FixtureConfiguration.java
A default implementation was added for `registerInjectableResource(Object resource)` that accepts a collection of resources.
=> Inject multiple test resources

messaging/src/main/java/org/axonframework/eventhandling/SimpleEventHandlerInvoker.java, messaging/src/test/java/org/axonframework/eventhandling/SimpleEventHandlerInvokerTest.java
If an event-processor is used in multiple service-classes and one of those classes is annotated with @AllowReplay(false), the processor is no longer replayable, but it should.
This pull request resolves #2955.
=> [#2955] Fix ability to replay when at least one Event Handling Component supports a reset

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/query/AxonServerQueryBusTest.java, messaging/src/test/java/org/axonframework/tracing/TestSpanFactory.java
The onClose handler on ScatterGather queries calls the `end` operation on Spans a second time. This, however, has been restricted by an exception as this can indicate thread leaks.
However, calling the `Span.end` on both `close` and finishing of advancing the stream is necessary, as users might not always close a stream explicitly. Likewise, the stream may be closed without reading it completely.
I have added an AtomicBoolean as close gate on the closeHandler, so it's always called exactly once.
The TestSpanFactory has been extended with the same behavior as the OpenTelemetrySpan to catch any other instances of this happening during the tests
=> Fix Exception on using OpenTelemetry and ScatterGather queries

eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/MysqlJdbcEventStorageEngineTest.java, pom.xml, spring-boot-3-integrationtests/pom.xml, spring/src/test/java/org/axonframework/spring/utils/MysqlTestContainerExtension.java
The docker container with the latest release has problems starting. This PR pins the version of mysql to 8.0, which doesn't seem to have that problem.
Included other version updates of related libraries for integration tests.
=> Resolved MySQL startup problems in integration tests

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/JpaEventStoreAutoConfiguration.java
This ensures that the required beans for autoconfiguration have had the chance to be defined before the Axon Autoconfiguration kicks in.
=> Added explicit AutoConfigureBefore and AutoConfigureAfter in JpaAutoConfiguration

.github/workflows/main.yml, .github/workflows/pullrequest.yml
Builds are now failing on Java 21 because jacoco isn't working correctly, we don't need to run jacoco for coverage if we don't send the report to sonar.
=> Skip jacoco if `sonar-enabled` is false.

test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java, test/src/test/java/org/axonframework/test/saga/AnnotatedSagaTest.java, test/src/test/java/org/axonframework/test/saga/AssociationResolverStub.java, test/src/test/java/org/axonframework/test/saga/StubSaga.java, test/src/test/java/org/axonframework/test/saga/TriggerAssociationResolverSagaEvent.java
Hi,
based on @abuijze commit https://github.com/AxonFramework/AxonFramework/commit/a8ee8f894c03551eb980eb16c03d4b637d23f665 the AssociationResolver does not received a DomainEventMessage.
I used the `EventUtils.asTrackedEventMessage` to receive a `GenericTrackedDomainEventMessage`
=> Fix SagaTestFixture use DomainEventMessage

docs/reference/modules/ROOT/pages/index.adoc
A link was removed from the documentation index page because the file to which it linked no longer exists.
=> Update index.adoc, remove link to how-to's

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/processor/EventProcessorControlService.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/processor/EventProcessorControlServiceTest.java
This pull request adds usage of the `TransactionManager` to the `TokenStore#retrieveStorageIdentifier` operation in the `EventProcessorControlService`.
Without wrapping this task in a transaction, some databases will throw exceptions.
Thus, for users of databases with this requirement, load balancing simply doesn't occur at all through the load balancing strategy properties.
=> Use `TransactionManager` in the `EventProcessorControlService` to invoke `TokenStore#retrieveStorageIdentifier`

messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java, messaging/src/test/java/org/axonframework/eventhandling/pooled/CoordinatorTest.java
The unit test uses reflection rather than replying the actual scenario happening to keep the test simple.
Validated the test indeed fails without the change.
=> Add additional check for NoToken so we never try to open a stream with it.

messaging/src/main/java/org/axonframework/eventhandling/GapAwareTrackingToken.java, messaging/src/test/java/org/axonframework/eventhandling/GapAwareTrackingTokenTest.java
When a GapAwareTrackingToken advances to a new position, it should never clean up any gaps ahead of that position, even if that means gaps are older than the given "maxGapOffset". Removing these gaps may result in problems with processors not being able to advance.
Resolves #2958
=> Resolve issue with eager gap cleanup

messaging/src/main/java/org/axonframework/messaging/deadletter/ThrowableCause.java, messaging/src/test/java/org/axonframework/messaging/deadletter/ThrowableCauseTest.java
Fixes
```
Error occurred. Starting retry mode.: java.lang.NullPointerException: Cannot invoke "String.length()" because the return value of "java.lang.Throwable.getMessage()" is null
at org.axonframework.messaging.deadletter.ThrowableCause.truncated(ThrowableCause.java:107)
at org.axonframework.messaging.deadletter.ThrowableCause.truncated(ThrowableCause.java:90)
at org.axonframework.config.EventProcessingModule.lambda$null$20(EventProcessingModule.java:181)
at org.axonframework.eventhandling.deadletter.DeadLetteringEventHandlerInvoker.invokeHandlers(DeadLetteringEventHandlerInvoker.java:177)
at org.axonframework.eventhandling.deadletter.DeadLetteringEventHandlerInvoker.handle(DeadLetteringEventHandlerInvoker.java:146)
[...]
```
Rebased version of #2989.
=> fix(deadletter): NPE on on throwables with null message

docs/reference/modules/ROOT/pages/index.adoc
The home for all the tutorials in the doc has been removed, I've changed the reference to that tutorials home page by the link to the specific "Building your first AxonFramework application from scratch" (the Bike Rental demo) tutorial in the index of the AxonFramework Reference guide
=> Changed reference to Home tutorial page with Bike Rental demo tutorial

test/src/main/java/org/axonframework/test/server/AxonServerContainer.java, test/src/test/java/org/axonframework/test/server/AxonServerContainerTest.java
Instead of using the latest-dev tag, the testcontainer should use the latest tag. Otherwise, the user wouldn't be able to set their own tag, as they would not be considered compatible with the default container name. Also, all changes are pushed with the "latest" tag.
=> Set axoniq/axonserver:latest as default AxonServer image

spring/src/main/java/org/axonframework/spring/config/SpringAxonConfiguration.java, spring/src/test/java/org/axonframework/spring/config/SpringAxonConfigurationTest.java
This means that we "start" Axon before starting the web server and "stop" axon after stopping the web server.
[#3007](https://github.com/AxonFramework/AxonFramework/issues/3007)
=> [#3007] Set a SmartLifecycle phase lower than the ones written in the spring WebServer lifecycle ones.

config/src/test/java/org/axonframework/config/EventProcessingModuleTest.java, messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java, messaging/src/main/java/org/axonframework/eventhandling/pooled/MaxSegmentProvider.java, messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java, messaging/src/test/java/org/axonframework/eventhandling/pooled/CoordinatorTest.java, messaging/src/test/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessorTest.java
- Currently, The EventProcessors in Axon Framework (specifically PooledStreamingEventProcessor) [parallelize](https://docs.axoniq.io/reference-guide/axon-framework/events/event-processors/streaming#parallel-processing) the processing of events by the number of Segments allocated per event processor (processing group). 
- The current Implementation of [PooledStreamingEventProcessor](https://github.com/AxonFramework/AxonFramework/blob/master/messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java#L445) keeps a maximum number of segments that can be claimed once the processing starts. The highest values are set to SHORT.max in the current implementation, as a result as soon as the processing begins, Most of the segments are claimed by the first …
=> Rebalance Segments in PooledStreamingEventProcessor

test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_SpawningNewAggregate.java
When spawning an aggregate from another, the test fixtures were unable to resolve custom resources. This change adds support for that.
=> Made test fixture resources available for handlers in spawned aggregates

docs/old-reference-guide/modules/axon-framework-commands/pages/infrastructure.adoc, docs/old-reference-guide/modules/events/pages/event-bus-and-event-store.adoc, docs/old-reference-guide/modules/events/pages/event-processors/README.adoc, docs/old-reference-guide/modules/events/pages/event-processors/subscribing.adoc, docs/old-reference-guide/modules/messaging-concepts/pages/supported-parameters-annotated-handlers.adoc, docs/old-reference-guide/modules/monitoring/pages/tracing.adoc
I've updated a few of the broken links in the Old Axon Framework reference guide to point to the modules corresponding to Extensions and appendices from the old docs moved to the library.
=> Updated links to Extensions and appendices

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModule.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/AxonServerConnectionManagerTest.java, spring-boot-3-integrationtests/src/test/java/org/axonframework/springboot/service/connection/SpringBootDockerComposeIntegrationTest.java, spring-boot-3-integrationtests/src/test/java/org/axonframework/springboot/service/connection/SpringBootTestContainerIntegrationTest.java, spring-boot-3-integrationtests/src/test/java/org/axonframework/springboot/service/connection/SpringBootTestContainerIntegrationWithAxonServerPropertiesFileTest.java, spring-boot-3-integrationtests/src/test/resources/application-custom.properties, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/service/connection/PropertiesAxonServerConnectionDetails.java
This pull request introduces the `PropertiesAxonServerConnectionDetails` object.
This object implements the `AxonServerConnectionDetails` interface and is constructed in the absence of an `AxonServerConnectionDetails` instance.
Furthermore, this introduces the `AxonServerConnectionManager.Builder#routingServers` as a means to set the routing servers separately from the `AxonServerConfiguration` object.
Whenever Axon Framework constructs the `AxonServerConnectionManager` for a user, we ensure `AxonServerConnectionManager.Builder#routingServers` is invoked.
The occasions are:
1. In the `ServerConnectorConfigurerModule`, which defaults to providing the `AxonServerConfiguration#getServers` output.
2. In the `AxonServerAutoConfiguration`, which uses the …
=> [#3022] Introduce `PropertiesAxonServerConnectionDetails` to ensure expected property ordering with `ConnectionDetails`

integrationtests/src/test/java/org/axonframework/integrationtests/deadline/quartz/QuartzDeadlineManagerTest.java, messaging/src/main/java/org/axonframework/deadline/quartz/QuartzDeadlineManager.java
This pull request adjusts the `QuartzDeadlineManager#cancelAllWithinScope` by serializing and immediately deserializing the given `ScopeDescriptor`.
I have introduced this to ensure the outcome of `DeadlineJob.DeadlineJobDataBinder.deadlineScope(Serializer, JobDataMap)`, which similarly has been serialized and deserialized, has the same type for the `ScopeDescriptor#identifier` field.
This, in turn, is done to ensure that non-String aggregate identifiers are correctly recognized in the `QuartzDeadlineManager#cancelAllWithinScope` method.
Without doing so, the `QuartzDeadlineManager#cancelAllWithinScope` would simply not cancel anything, as the `AggregateScopeDescriptor#identifier` (as it's an `Object`) does not match the serialized `identifier` at all.
Another approach to tackle this, is …
=> [#3042] De-/Serialize given `ScopeDescriptor` on each `QuartzDeadlineManager#cancelAllWithinScope` invocation

docs/README.md
Added readme.md to docs folder  with:
-  the list and description of the different doc source folders (and links to the corresponding published version in AxonIQ Library)
- Explanation of how the docs are built and invitation to contribute to the docs. (The Contribution Guide is not directly reachable from nav menus in AxonIQ Library)
- Instructions to build the docs locally.
=> Added docs/Readme.md

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamScheduledExecutorBuilder.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/PersistentStreamMessageSourceRegistrar.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfigurationTest.java
This pull request introduces the `PersistentStreamScheduledExecutorBuilder` functional interface. 
This interface replaces the **single** and, by default, **single-threaded** `ScheduledExecutorService` that Axon Framework's autoconfiguration constructs for **all** Persistent Streams. 
In doing so, we can provide an easier means to configure a `ScheduledExecutorService` per Persistent Stream.
This can be achieved by switching based on the `streamName` provided to the `PersistentStreamScheduledExecutorBuilder#build(Integer,String)` operation. 
Furthermore, the `threadCount` can be adjusted per Persistent Stream through this interface as well.
Lastly, a property is added to the `AxonServerConfiguration`, called `threadCount`.
Through this, an `application.properties`/`application.yml` file …
=> Introduce `PersistentStreamScheduledExecutorBuilder`

axon-5/api-changes.md, eventsourcing/src/test/java/org/axonframework/eventsourcing/StubProcessingContext.java, messaging/src/main/java/org/axonframework/common/FutureUtils.java, messaging/src/main/java/org/axonframework/messaging/unitofwork/AbstractUnitOfWork.java, messaging/src/main/java/org/axonframework/messaging/unitofwork/AsyncUnitOfWork.java, messaging/src/main/java/org/axonframework/messaging/unitofwork/BatchingUnitOfWork.java, messaging/src/main/java/org/axonframework/messaging/unitofwork/CurrentUnitOfWork.java, messaging/src/main/java/org/axonframework/messaging/unitofwork/DefaultUnitOfWork.java, messaging/src/main/java/org/axonframework/messaging/unitofwork/ExecutionResult.java, messaging/src/main/java/org/axonframework/messaging/unitofwork/MessageProcessingContext.java, messaging/src/main/java/org/axonframework/messaging/unitofwork/NoProcessingContext.java, messaging/src/main/java/org/axonframework/messaging/unitofwork/ProcessingContext.java, messaging/src/main/java/org/axonframework/messaging/unitofwork/ProcessingLifecycle.java, messaging/src/main/java/org/axonframework/messaging/unitofwork/ResourceOverridingProcessingContext.java, messaging/src/main/java/org/axonframework/messaging/unitofwork/UnitOfWork.java, messaging/src/test/java/org/axonframework/messaging/unitofwork/AsyncUnitOfWorkTest.java, messaging/src/test/java/org/axonframework/messaging/unitofwork/ProcessingLifecycleTest.java
This pull request serves as an addition to #2953.
We merged #2953 as it was a very important milestone, mandatory to proceed with working on other infrastructure components.
However, as the Unit of Work rewrite and introduction of the `ProcessingLifecycle` and `ProcessingContext` are extremely central to Axon Framework, I deemed an early revamp of the JavaDoc and API changes documentation to be paramount for further development.
Hence, that is exactly what this pull request does.
It adds JavaDoc, adjusts JavaDoc, renames parameters, reorders variables and methods, and further cleans up any irregularities to provide a strong basis for proceeding with Axon Framework 5's development.
Added, as the `UnitOfWork`, and the other deprecated and soon-to-be-removed implementations of this …
=> [#2966] Add and enhance JavaDoc for the new Unit of Work

messaging/src/main/java/org/axonframework/common/property/AbstractMethodPropertyAccessStrategy.java, messaging/src/test/java/org/axonframework/common/property/BeanPropertyAccessStrategyTest.java
This is a new merge request for the change already requested with pull request 3113.
It contains already changes based on the comments from Steven.
Following is the original description of the pull request 3113
___
In our project we are applying around 1,9 billion events in around 21 hours.
This is a migration of an old system, which happens weekly, as long as we are in developing the product. At least one additional year. In this migration only events are applied.
While applying events, I was wondering why the client uses 50 % of the CPU, while the Axon Server only needs around 5 %.
After profiling the client, I realized that about 65 % of the CPU Time was used for throwing exceptions while applying events.
This should be a fix, which decrease the CPU time and the duration of a property …
=> Adjust the `AbstractMethodPropertyAccessStrategy` to filter better on none-matching methods 

modelling/src/main/java/org/axonframework/modelling/command/ForwardMatchingInstances.java, modelling/src/test/java/org/axonframework/modelling/command/ForwardMatchingInstancesTest.java
This PR adds a cache to the properties that have been discovered in each of the message payloads that an entity has a handler for.
This prevents lookup of properties to occur for each instance of an event that is applied to an aggregate.
With this optimization, a lookup is only required for each new payload type that is being applied.
=> Reduce the number of property lookups for matching entities

messaging/src/main/java/org/axonframework/queryhandling/SubscriptionQueryResult.java, messaging/src/test/java/org/axonframework/queryhandling/DefaultSubscriptionQueryResultTest.java
The `SubscriptionQueryResult#handle(Consumer<? super I>, Consumer<? super U>)` would swallow exceptions that reside in the `Mono<I> initialResult`.
As this is not helpful to the end user, this pull request provides an implementation of `SubscriptionQueryResult#handle(...)` that expects a `Consumer<Throwable>` to be given.
This so-called `errorConsumer` is invoked when subscribing the `initialResult()` generates an exception, when subscribing to the `updates()` generates an exception, and when the `initialResultConsumer` or `updateConsumer` throw an exception.
As such, the `errorConsumer` is invoked each time the `SubscriptionQueryResult#cancel` would be triggered.
Lastly, this PR deprecates `SubscriptionQueryResult#handle(Consumer<? super I>, Consumer<? super U>)` in favor of …
=> [#3123] Introduce `SubscriptionQueryResult#handle` default implementation that expects a `Consumer<Throwable>`

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/PersistentStreamConnection.java
The back-off rescheduling of a failed Persistent Stream picked the maximum value between `60` and `current * 2`, causing the value to increase indefinitely.
This PR corrects that behavior to pick the minium value, ensuring the back-off rescheduling "maxes out" at 60 (seconds).
=> Fix rescheduling of failed Persistent Streams

test/src/main/java/org/axonframework/test/server/AxonServerContainerUtils.java, test/src/test/java/org/axonframework/test/server/AxonServerContainerTest.java
When a container is not initialized (first run), the method to check if it's initialized hits the endpoint...
`/v1/public/context`
this fails with a `400` and subsequently the `contexts` method throws an IllegalArgumentException using this we can draw the conclusion that the container is not yet initialized. (This assumption needs to be verified)
Also added a test that calls the doStart method twice to test that we do not try to initialize a container that has been initialized and that the reuse works.
=> Account for contexts call on un-initialized containers

messaging/src/main/java/org/axonframework/eventhandling/deadletter/jdbc/DefaultDeadLetterStatementFactory.java, messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/EventMessageDeadLetterJpaConverter.java, messaging/src/test/java/org/axonframework/eventhandling/deadletter/jpa/EventMessageDeadLetterJpaConverterTest.java
Currently the DLQ does not enqueue messages with deserialization errors, due to the following stack trace:
```
SerializedMessage.getPayload(SerializedMessage.java:81)
MessageDecorator.getPayload(MessageDecorator.java:56)
MessageDecorator.getPayload(MessageDecorator.java:56)
EventMessageDeadLetterJpaConverter.convert(EventMessageDeadLetterJpaConverter.java:59)
```
In this trace the message is first deserialized (if it wasn't yet, through the `LazyDeserializingMessage`) before being serialized again. Besides being inefficient, this causes any deserialization error to occur again during enqueuement in the DLQ, causing the event processor to go into error mode.
This PR switches the call to the `Message.serializePayload` call, which is overridden by the SerializedMessage to not …
=> Allow DLQ to handle deserialization errors

docs/old-reference-guide/modules/events/pages/event-processors/streaming.adoc
I would like to link the AxonIQ Console docs to it, as follows:
```adoc
If the segment claim percentage is higher than 100%, this can mean two things:
- You have an `InMemoryTokenStore` configured with multiple applications deployed, which can be a valid use-case if you want all application instances to process the same events.
- Your applications are xref:xref:axon-framework-reference:events:event-processors/streaming.adoc#token-stealing[stealing tokens from each other] because the work in a batch takes longer than the configured `tokenClaimInterval` of the token store.
```
This way it doesn't have to be explained twice. However, it's missing a nice anchor. This PR adds that.
=> Make a nice link to Token Stealing to refer it in the AxonIQ Console guide

messaging/src/test/java/org/axonframework/messaging/annotation/AnnotatedMessageHandlingMemberTest.java
`hasAnnotation` test within `AnnotatedMessageHandlingMemberTest.java` can fail, if `getMethods` returns a different order. It was expecting a `true` result, but could get `false`.
To fix this test, the `getMethods()[0]` call within the `setUp` was replaced with `getMethod("handlingMessage", String.class)`. A try catch block was added to handle the change to make sure that `EventHandler` was returned.
The change/addition was confirmed by running the [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool.
To reproduce the problem, you can run the NonDex tool, using this command:
```
mvn -pl messaging edu.illinois:nondex-maven-plugin:2.1.7:nondex -Dtest=org.axonframework.messaging.annotation.AnnotatedMessageHandlingMemberTest#hasAnnotation
```
=> fixed hasAnnotation test

messaging/src/test/java/org/axonframework/messaging/GenericMessageTest.java
`messageSerialization` test within `GenericMessageTest.java` can fail based on the order of keys in the JSON output. It was expecting a `<{"key":"value","foo":"bar"}>` but actually returned: `<{"foo":"bar","key":"value"}>`.
To fix this test, the comparison of the raw serialized strings was replaced by parsing the JSON and comparing the actual content of the serialized metadata with the use of a map. The `HashMap` of the `expectedMetaData` and the `Map` of the `actualMetaData` was made and then compared for equality, regardless of key order. A `throws IOException` was added to handle the deserialization process. 
The change/addition was confirmed by running the [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool.
To reproduce the problem, you can run the NonDex tool, using …
=> Fixed messageSerialization test in GenericMessageTest

test/src/test/java/org/axonframework/test/server/AxonServerEEContainerTest.java, test/src/test/java/org/axonframework/test/server/AxonServerSEContainerTest.java
This pull request skips Axonserver TestContainer tests for legacy versions not supporting ARM64 architecture.
Resolves #3157.
=> [#3157] Skip Axon Server Docker tests on ARM64 for older Axon Server versions

messaging/src/main/java/org/axonframework/eventhandling/deadletter/jdbc/JdbcSequencedDeadLetterQueue.java, messaging/src/main/java/org/axonframework/eventhandling/deadletter/jpa/JpaSequencedDeadLetterQueue.java, messaging/src/main/java/org/axonframework/eventhandling/deadletter/legacyjpa/JpaSequencedDeadLetterQueue.java, messaging/src/main/java/org/axonframework/messaging/deadletter/InMemorySequencedDeadLetterQueue.java
Resolves #3160
@smcvb I saw the `Cause` interface exposes the original exception `type()`, so instinctively I went for that. Though, the exception message might be interesting in some cases, e.g. the JSR303 constraint violation I referred to in the issue, because it prints all offending fields helping in debugging. So, alternatively we could go for `Cause#toString()`, which can produce very long outputs if the exception message is long, that's the downside. Your call.
https://github.com/AxonFramework/AxonFramework/blob/d7c6fcd7216558d9d90107e1ef77c0ae81530cb3/messaging/src/main/java/org/axonframework/messaging/deadletter/ThrowableCause.java#L139-L142
=> fix: log statement issue with logback classic

README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Axon Framework Guru](https://gurubase.io/g/axon-framework) to Gurubase. Axon Framework Guru uses the data from this repo and data from the [docs](https://docs.axoniq.io) to answer questions by leveraging the LLM.
In this PR, I showcased the "Axon Framework Guru", which highlights that Axon Framework now has an AI assistant available to help users with their questions. Please let me know your thoughts on this …
=> Introducing Axon Framework Guru on Gurubase.io

test/src/main/java/org/axonframework/test/saga/FixtureConfiguration.java, test/src/main/java/org/axonframework/test/saga/SagaTestFixture.java, test/src/test/java/org/axonframework/test/saga/AnnotatedSagaTest.java
This change allows the usage of metadata in the saga test fixture when using the givenAPublished GivenState. To do this currently, there is only the workaround to do sth. like:
```
fixture.givenAggregate("id")
.published()
.andThenAPublished(orderCreatedEvent, MetaData.emptyInstance())
```
fixes #3197
=> SagaTestFixture extend APIs for publishing historic events with metadata

docs/old-reference-guide/modules/ROOT/pages/known-issues-and-workarounds.adoc, docs/old-reference-guide/modules/tuning/pages/rdbms-tuning.adoc
This PR is an upgrade of #3193, specifically introducing a section called "PostgreSQL, `@LOB`-annotated columns, and default Hibernate mapping" to the RDBMS Tuning page.
Furthermore, I have adjusted the description of the TOAST/OID behavior to align better with this new section it links to.
=> PostgreSQL, `@LOB`-annotated columns, and default Hibernate mapping

.github/workflows/pullrequest.yml
The Pull Request GitHub Actions workflow takes about 15 minutes.
If you push another commit during an ongoing build, you end up with two builds running simultaneously, even though you only care about the latest result.
When you push another commit during a build, the ongoing build will be canceled, and only the latest commit will be processed.
- Saves time and resources.
- Reduces unnecessary builds, optimizing costs.
=> ci: GitHub Actions - one in-progress run per pull request

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/InfraConfiguration.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/InterceptorAutoConfiguration.java, spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories, spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/InterceptorConfigurationTest.java, spring/pom.xml
Solves #3202 
This PR discovers MessageHandlerInterceptors and registers them to the localSegment's queryBus and commandBus.
- introduced List of commandHandlerInterceptor to Configuration and Configurer
- introduced List of queryHandlerInterceptor to Configuration and Configurer
- added discovery of messageHandlerInterceptors to to InfraConfiguration
- register the discovered messageHandlerInterceptors to the created localSegment commandBus/queryBus and default commandBus/queryBus
=> [#3202] Auto-register `MessageHandlerInterceptors` with Spring Boot

config/src/main/java/org/axonframework/config/DefaultConfigurer.java, messaging/src/main/java/org/axonframework/commandhandling/annotation/AnnotationCommandHandlerAdapter.java, messaging/src/main/java/org/axonframework/commandhandling/gateway/DefaultCommandGateway.java, test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java
Continuation of changes from this PR:
https://github.com/AxonFramework/AxonFramework/pull/3214
=> [#3085] QualifiedName: use `MessageNameResolver` for `AnnotationCommandHandlerAdapter`

.github/workflows/main.yml, .github/workflows/pullrequest.yml
The Pull Request GitHub Actions workflow takes about 15 minutes.
- If you push another commit during an ongoing build, you end up with two builds running simultaneously, even though you only care about the latest result.
- Sometimes the tests can stuck and remain in progress till someone cancel them (a lot of lost resources and money for eg. more than hour)
- When you push another commit during a build, the ongoing build will be canceled, and only the latest commit will be processed.
- When the build takes more than 20 minutes, then will be cancelled.
- Saves time and resources.
- Reduces unnecessary and too long builds, optimizing costs.
=> ci: GitHub Actions (AF4) - timeout for builds and one in-progress run per pull request

.github/workflows/main.yml, .github/workflows/pullrequest.yml
The build contains some flaky tests:
- To ensure our changes work, we need to repeat the workflow multiple times. This wastes developers' time, as well as resources and money on GitHub Actions.
- We might encounter flaky test failures and assume "everything is OK," but some other tests may fail afterward. As a result, we may unknowingly merge something problematic.
- When a test fails, it will be retried up to 5 times.
Then this test will be counted as a flaky test. The build will be successful, but in the end of the summary of all tests run, the number of flaky tests will be output on the screen.
```
[INFO] Results:
[INFO] 
[WARNING] Flakes: 
[WARNING] org.axonframework.axonserver.connector.query.AxonServerQueryBusTest.queryReportsCorrectException
[ERROR]   Run 1: …
```
=> ci: GitHub Actions (AF5) - rerun flaky tests

messaging/src/main/java/org/axonframework/eventhandling/gateway/AbstractEventGateway.java, messaging/src/main/java/org/axonframework/eventhandling/gateway/DefaultEventGateway.java, messaging/src/test/java/org/axonframework/eventhandling/gateway/DefaultEventGatewayTest.java
This pull request makes a slight change in the `DefaultEventGateway`.
Before this PR, the `DefaultEventGateway` did a foreach over the given collection of `events`.
Hence, the `EventBus#publish` method was invoked multiple times. 
In doing so, the behavior of the `EventGateway` differs depending on whether a `UnitOfWork` is present or not.
With an active `UnitOfWork`, Axon Framework would batch the events in a single commit, as expected from the API.
But if there's no active `UnitOfWork`, each event would be published separately; regardless of whether the `EventGateway` was invoked with a single event or a set of events.
I think this behavior is off, hence this PR ensures the given collections is provided as a collection to the `EventBus`.
=> Have `DefaultEventGateway` provide a collection of events to the `EventBus` instead of looping over the events

docs/.asciidoctorconfig
Added an .asciidoctorconfig file which tells the IDE to render the preview of asciidoc using the stylesheets from the documentation platform.
This only works for adoc files that have an antora configuration file in one of the parent directories.
=> Added asciidoctor rendering configuration

messaging/src/main/java/org/axonframework/eventhandling/pooled/PooledStreamingEventProcessor.java
I've spotted the mistake in the documentation.
=> docs: fix PooledStreamingEventProcessor default initial tracking token

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/LegacyAxonServerEventStorageEngine.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/LegacyAxonServerEventStorageEngineTest.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AsyncEventStorageEngine.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EmptyAppendTransaction.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/LegacyAggregateBasedEventStorageEngineUtils.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/TooManyTagsOnEventMessageException.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/GapAwareTrackingTokenOperations.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/JpaEventStorageEngine.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/LegacyJpaEventStorageEngine.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/jpa/LegacyJpaEventStorageOperations.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/AggregateBasedStorageEngineTestSuite.java, integrationtests/pom.xml, integrationtests/src/test/java/org/axonframework/integrationtests/eventsourcing/eventstore/jpa/LegacyJpaEventStorageEngineTest.java
- Implemented JPA EventStore using the new API. 
- Adjusted test suite to work with different event sequencing and add more test cases.
- Extracted common parts (like LegacyJpaEventStorageOperations) from the old and new implementation of the Jpa Event Storage Engine in order to keep both implementations for now and better cohesion. 
- Fixed bug in LegacyAxonServerEventStorageEngine - handle Event metadata. 
Next PRs:
- I propose merging this PR in its current state, if it is good enough, and addressing the remaining work (e.g., changing the mechanism from serializer to converter, deciding how to handle metadata serialization, etc.) in subsequent PRs. This approach keeps the PR manageable in size and allows others to use the updated test suite and incorporate the bug fixes.
Note:
Do not …
=> [#3166] Add `LegacyJpaEventStorageEngine`

README.md
My eye just fell on the README.md, still containing start.axoniq.io as a link.  As we don't have that anymore, let's remove it.
=> Remove initializer from readme

integrationtests/src/test/java/org/axonframework/integrationtests/deadline/jobrunr/JobrunrDeadlineManagerTest.java, messaging/src/main/java/org/axonframework/deadline/jobrunr/JobRunrDeadlineManager.java
A user of ours had a scenario where a Saga's event handler invoked `JobRunrDeadlineManager#cancel`.
During that process, the connection to their Mongo store failed when updating the saga.
This predicament caused the JobRunr job to move to the `DELETED` state, while the saga would be retried by Axon Framework.
The retry caused the `JobRunrDeadlineManager#cancel` method to be invoked again for an already deleted JobRunr job.
JobRunr rightfully so throws a `IllegalJobStateChangeException` in such a scenario, as that's a faulty state change to make.
When JobRunr would participate in the Mongo transaction this could be resolved, of course.
However, since that's not the case at the moment, I have adjusted the `JobRunrDeadlineManager#cancel` to contain a try-catch when a …
=> Catch `IllegalJobStateChangeException` in `JobRunrDeadlineManager` when the failed change is from `DELETED` to `DELETED`

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/query/AxonServerQueryBus.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/ExecutorServiceBuilder.java, docs/old-reference-guide/modules/queries/pages/query-dispatchers.adoc, docs/old-reference-guide/modules/queries/pages/query-handlers.adoc, integrationtests/pom.xml, integrationtests/src/test/java/org/axonframework/integrationtests/queryhandling/QueryThreadingIntegrationTest.java
Splits the thead pool of the AxonServerQueryBus in two, one responsible for handling queries, and the other for handling incoming query responses. By having these two separate, the situation that the pool becomes full while waiting for query responses will no longer lead to a deadlock.
=> Fix for deadlock when many queries wait for responses

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConfiguration.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/AxonServerConnectionManager.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/GrpcMessageSizeExceededException.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/GrpcMessageSizeInterceptor.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/GrpcMessageSizeWarningThresholdReachedException.java
When Axon Server, or a client application, receives a message that is too large, its gRPC container (Netty) will automatically terminate the incoming connection without any clear error. This leads to confusion by the user, as it's often impossible to see the cause.
We can be clearer to the user in this regard. This change introduces the `GrpcMessageSizeInterceptor`, which rejects calls that are bigger than the configured max message size. This defaults to 4MiB, just like the inbound limit of Axon Server, but can be adjusted by the user. In addition, when 80% of the limit is reached, a warning with stack trace is logged to the user, so they can a) increase the limit on both sides or b) fix the problem in their application.
The latter warning also applies to inbound messages, to keep the …
=> Introduce gRPC message limit warning and prevention

eventsourcing/src/main/java/org/axonframework/eventsourcing/AsyncEventSourcingRepository.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/AnyEvent.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultAppendCondition.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransaction.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/EventStoreTransaction.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/GlobalIndexConsistencyMarker.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/AsyncEventSourcingRepositoryTest.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/AsyncEventStoreTest.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/DefaultEventStoreTransactionTest.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/SimpleEventStoreTest.java
This PR introduces the implementation and tests for the AsyncEventSourcingRepository to ensure that events are appended using a correct AppendCondition.
It's constructed using the `SourcingConditions` from each of the `source` calls on that repository in the same `ProcessingContext`, combined with the consistency marker resulting from the sourced stream.
The `ProcessingContext` parameter has been removed from the methods on an `EventStoreTransaction`, as the context is already provided on retrieval of that transaction. 
The transaction itself is already aware of the `ProcessingContext` it operates under.
=> Set Consistency Marker on `AppendCondition` from `EventStoreTransaction#source` calls

spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/InterceptorAutoConfiguration.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/InterceptorConfigurationTest.java
=> [#3283] fix: Auto-register `MessageHandlerInterceptors` with Spring Boot fails for interceptors which depends on Axon components

eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/ConsistencyMarker.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/inmemory/AsyncInMemoryEventStorageEngine.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/StorageEngineTestSuite.java
The AsyncInMemoryEventStorageEngine does not call the availability callback when starting a sourcing stream and the store is empty. This causes the stream to hang indefinitely when using normal `MessageStream` methods like `reduce` (which the `EventSourcingAsyncRepository` does).
To fix this, we now call the availability callback immediately when the store is empty. For flux this worked, because it called `hasNextAvailable`.
Additionally, the `Context` of the `EventMessage`s were missing the `ConsistencyMarker`, which caused always cause the marker to be origin, and any event to be appended a conflict when used in conjunction with the `EventSourcingAsyncRepository`.
=> Fix infinite event source call and missing ConsistencyMarker

messaging/src/test/java/org/axonframework/messaging/configuration/NewMessageHandlerRegistrationTest.java
Build was broken, because of not existing method.
=> fix: `NewMessageHandlerRegistrationTest` does not expect `GenericMessageHandlingComponent#supportedMessages` method

messaging/src/main/java/org/axonframework/eventhandling/pooled/Coordinator.java
The pooled event processor status is not reset to healthy when the connection to Axon Server was lost and recovered.
=> Reset the `Coordinator's` processing gate if the `Coordinator` was aborted and rescheduled

spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/AxonAutoConfigurationWithEventSerializerPropertiesTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/CBORMapperAutoConfigurationTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/ObjectMapperAutoConfigurationTest.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/integration/EventProcessingModuleConfigTest.java
First, the HttpMessageConvertersAutoConfiguration autoconfiguration class requires a singular ObjectMapper bean because it imports JacksonHttpMessageConvertersConfiguration. It breaks, as there *are* two ObjectMapper implementations in the bean registry. As such, I have excluded this for a few tests.
Second and last, the assertion for the number of interceptors in the EventProcessingModuleConfigTest was wrong, as there is an additional interceptor added by the AxonTimeoutConfigurerModule introduced in 4.11. I have disabled the module adding this interceptor through a property.
=> Fix failing Spring Boot tests due to 4.11.x merge.

modelling/src/main/java/org/axonframework/modelling/command/AggregateAnnotationCommandHandler.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AvroSerializerAutoConfiguration.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CreationPolicy.java
With the effort to support the `@CreationPolicy` for polymorphic aggregates as requested in #3171, we accidentally removed support for these methods on aggregate interfaces.
This pull request resolves that misser by falling back to the `AggregateModel#entityClass` whenever the `factoryPerType` collection does not have a concrete factory for the given type.
This concrete factory can only not be found in case of interfaces, so moving up the model chain is a worthwhile solution to this issue.
I've tested the fall back to work by adjusting the creation policy test to have an interface for some of the `@CreationPolicy` annotated methods.
And, by not having the `@CreationPolicy` annotations on the concrete implementation.
As this issue originated from fixing #3171, we can regard it as if it …
=> [#3171] Support `@CreationPolicy` annotated interface methods __again__

modelling/src/main/java/org/axonframework/modelling/command/LockingRepository.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CreationPolicy.java
This pull request adjusts the `LockingRepository#doLoadOrCreate` by checking if it is handling with an exact match of the `AggregateNotFoundException`.
If we are not dealing with an exact match of the `AggregateNotFoundException` class, a `AggregateDeletedException` is being caught.
The `AggregateDeletedException` occurs whenever a subsequent command comes in for an aggregate that's been marked as deleted by the `AggregateLifecycle#markDeleted` operation.
If we react on this exception as if the aggregate does not exist, a `CREATE_IF_MISSING` command handling policy would, that moves through the `LockingRepository#doLoadOrCreate`, results in a subsequent failure as it thinks it can recreate the aggregate.
The subsequent failure would be a failure on inserting the event, as the …
=> Ignore aggregates that have been `AggregateLifecycle#markDeleted` when using the Create-if-missing policy.

messaging/src/test/resources/META-INF/persistence.xml
The build of axon-messing hangs about 30-40% of the time on my local PC. There are also some Github builds that time out. After some investigation, I found a JVM-level deadlock in HSQLDB. I reported the deadlock here: https://sourceforge.net/p/hsqldb/bugs/1730/
As per the response, I have added the `hsqldb.log_size=0` to the test properties. This should have no other impact as far as I see (I have ran this build about 10 times now with success).
=> Fix thread deadlock for HSQLDB

eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/AnnotationBasedEventCriteriaResolver.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/annotation/AnnotationBasedEventCriteriaResolverTest.java
Allow non-public @EventCriteriaBuilder methods, so users can choose to encapsulate it.
=> Allow non-public @EventCriteriaBuilder methods

messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspector.java, messaging/src/main/java/org/axonframework/messaging/annotation/ChainedMessageHandlerInterceptorMember.java, modelling/src/main/java/org/axonframework/modelling/command/inspection/ChildForwardingCommandMessageHandlingMember.java, test/src/test/java/org/axonframework/test/aggregate/FixtureTest_CommandInterceptors.java
The `ChildForwardingCommandMessageHandlingMember` followed a different paradigm for deciding which Annotated Message Handler Interceptors to pick.
More specifically, it checked if the interceptors match with the message that's being handled.
Although not inherently wrong, if somebody used the `InterceptorChain` parameter, it would simply fail.
This failure stems from the way we set the `InterceptorChain` for parameter resolution. Namely, on a `ThreadLocal`.
For this process to succeed, we first want to invoke the chain before validating if the message can be handled.
The component that ensure that (1) the `InterceptorChain` is present on a `ThreadLocal` and (2) invokes all interceptors and the final handler, is the `ChainedMessageHandlerInterceptorMember`.
Hence, the old behavior made it …
=> [#3385] Align interceptor behavior for Aggregate Members

docs/old-reference-guide/modules/tuning/pages/rdbms-tuning.adoc
This pull request adds allocation size details to the warning and suggested `orm.xml`. 
If users set a [pooled optimizer](https://vladmihalcea.com/hibernate-hidden-gem-the-pooled-lo-optimizer/), they would prepare a (by default) set of 50 global indices shared over several instances. 
This will definitely incur a lot of gaps, causing performance degradation of Axon's JPA RDBMS solution. 
As a solution, users can adjust the allocation-size of the sequence generator to one. 
Although this does not entirely resolve the issue, it makes the window of opportunity a lot smaller.
It is very beneficial to not this predicament in the documentation. Henceforth, this pull request.
By doing the above, this pull request resolves issue #3374 to the best of it's abilities.
=> [#3374] Add allocation-size details to "Auto-increment and sequences" section

docs/old-reference-guide/modules/messaging-concepts/pages/message-intercepting.adoc
This pull request adds a note to describe the unintended behavior of invoking `@MessageHandlerInterceptor` for `@EventSourcingHandler` annotated methods.
Due to this unintended side effect, event sourcing handlers on aggregate members do not cause the invocation of message handler interceptors.
As such, the note suggests not to use this behavior, which in most cases should not be used any how.
By adding this note, this pull request resolves #3348
=> [#3348] Document `@MessageHandlerInterceptor` behavior for `@EventSourcingHandlers` on Aggregate Members

axon-5/api-changes.md, messaging/src/main/java/org/axonframework/messaging/StreamableMessageSource.java, modelling/src/main/java/org/axonframework/modelling/command/AggregateLifecycle.java, modelling/src/main/java/org/axonframework/modelling/configuration/ModellingConfigurer.java, modelling/src/main/java/org/axonframework/modelling/repository/ManagedEntity.java, modelling/src/main/java/org/axonframework/modelling/repository/Repository.java, test/src/main/java/org/axonframework/test/aggregate/AggregateTestFixture.java, test/src/main/java/org/axonframework/test/aggregate/FixtureConfiguration.java, test/src/main/java/org/axonframework/test/aggregate/ResultValidator.java, test/src/main/java/org/axonframework/test/aggregate/ResultValidatorImpl.java, test/src/main/java/org/axonframework/test/aggregate/TestExecutor.java
This pull request provides a lot of changes to the `api-changes.md` file.
Since this file forms the basis for our to-be-constructed migration guide and code, it is paramount we keep this file up to date.
Granted, we should perform this tasks for every pull request, instead of performing the write down after the fact.
Thus, to safe us some effort in the feature, let's try to adjust this file as we go along.
That said, this PR makes the following adjustments to the `api-changes.md`:
* Adds an introduction section
* Adds a `MessageStream` section to the Major API block
* Adds a Test Fixture section to the Major API block
* Adds an `EventStore` section to the Major API block
* Fine-tuned the `MessageType`/`QualifiedName` section
* Fine-tuned the `MessageStream` section
* Fine-tuned the …
=> [#3382] Add missing, and fine-tune existing, `api-changes` sections

messaging/src/main/java/org/axonframework/serialization/AbstractXStreamSerializer.java, messaging/src/main/java/org/axonframework/serialization/json/JacksonSerializer.java, messaging/src/main/java/org/axonframework/serialization/xml/XStreamSerializer.java, messaging/src/test/java/org/axonframework/serialization/json/JacksonSerializerTest.java, messaging/src/test/java/org/axonframework/serialization/xml/XStreamSerializerTest.java
Resolving classes based on a name that did not yield any results was very slow. This meant that processing a stream of event where the majority of events aren't represented as classes was slower than a case where the classes are available on the class path.
=> Added caching for unknown classes

messaging/src/main/java/org/axonframework/configuration/HierarchicalConfiguration.java, messaging/src/test/java/org/axonframework/configuration/HierarchicalConfigurationTest.java
The `HierarchicalConfiguration` did not return the `CompletableFuture` of its caller. 
So the exception on start was lost and thus not propagated. This PR resolves that issue.
=> Fix exceptions not being propagates from start handlers.

messaging/src/main/java/org/axonframework/configuration/Component.java, messaging/src/main/java/org/axonframework/configuration/ComponentDecorator.java, messaging/src/main/java/org/axonframework/configuration/ComponentDefinition.java, messaging/src/main/java/org/axonframework/configuration/ComponentNotFoundException.java, messaging/src/main/java/org/axonframework/configuration/ComponentOverrideException.java, messaging/src/main/java/org/axonframework/configuration/ComponentRegistry.java, messaging/src/main/java/org/axonframework/configuration/Components.java, messaging/src/main/java/org/axonframework/configuration/Configuration.java, messaging/src/main/java/org/axonframework/configuration/DecoratorDefinition.java, messaging/src/main/java/org/axonframework/configuration/DefaultAxonApplication.java, messaging/src/main/java/org/axonframework/configuration/DefaultComponentRegistry.java, messaging/src/test/java/org/axonframework/configuration/ApplicationConfigurerTestSuite.java, messaging/src/test/java/org/axonframework/configuration/ComponentTestSuite.java, messaging/src/test/java/org/axonframework/configuration/ComponentsTest.java, test/src/main/java/org/axonframework/test/fixture/MessagesRecordingConfigurationEnhancer.java, test/src/main/java/org/axonframework/test/fixture/RecordingEventSink.java, test/src/main/java/org/axonframework/test/fixture/RecordingEventStore.java
This pull request adjusts three spots in the configuration logic, being:
1. How we retrieve `Components` from the `Configuration`.
2. When we decide to decorate a `Component`
3. The name of a `Component` is now nullable.
Instead of a direct equals check on the given type and the stored type, this PR changes that behavior to an `Class#isAssignableFrom`.
In doing so, we and users can register decorators for (for example) all `CommandGateway` implementations present with a single `ComponentRegistry#registerDecorator` invocation.
Furthermore, retrieval of components is simplified where we or the users do not care about the concrete implementation, but simply desire the (for example) `EventStore` that's present in the configuration.
Lastly, by making the name of a `Component` nullable …
=> [#3434] Do `Class#isAssignableFrom` to retrieve components and match decorators in the `Configurer`

modelling/src/test/java/org/axonframework/modelling/AnnotationBasedEntityEvolvingComponentTest.java
I accidentally already built support for this in an earlier PR related to EntityModelling. As such, we can enable these already-working tests. This resolves #3313
=> [#3313] Enable tests for record support.

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/event/axon/GrpcMetaDataAwareSerializer.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/util/GrpcSerializedObject.java, messaging/src/main/java/org/axonframework/serialization/AbstractXStreamSerializer.java, messaging/src/main/java/org/axonframework/serialization/GapAwareTrackingTokenConverter.java, messaging/src/main/java/org/axonframework/serialization/SerializationException.java, messaging/src/main/java/org/axonframework/serialization/SerializedMetaData.java, messaging/src/main/java/org/axonframework/serialization/SerializedObject.java, messaging/src/main/java/org/axonframework/serialization/SerializedObjectHolder.java, messaging/src/main/java/org/axonframework/serialization/SerializedType.java, messaging/src/main/java/org/axonframework/serialization/Serializer.java, messaging/src/main/java/org/axonframework/serialization/SimpleSerializedObject.java, messaging/src/main/java/org/axonframework/serialization/SimpleSerializedType.java, messaging/src/main/java/org/axonframework/serialization/avro/AvroSerializer.java, messaging/src/main/java/org/axonframework/serialization/json/JacksonSerializer.java, messaging/src/main/java/org/axonframework/serialization/json/MetaDataDeserializer.java, messaging/src/main/java/org/axonframework/serialization/xml/CompactDriver.java, messaging/src/main/java/org/axonframework/serialization/xml/Dom4JToByteArrayConverter.java, messaging/src/main/java/org/axonframework/serialization/xml/InputStreamToDom4jConverter.java, messaging/src/main/java/org/axonframework/serialization/xml/InputStreamToXomConverter.java, messaging/src/main/java/org/axonframework/serialization/xml/XStreamSerializer.java, messaging/src/main/java/org/axonframework/serialization/xml/XomToStringConverter.java, modelling/src/main/java/org/axonframework/modelling/saga/repository/jpa/SerializedSaga.java
This pull request marks the `Serializer`, it's implementations, and other `Serializer`-specific interfaces and components as deprecated. 
This helps in the development of the `Converter` replacement, as it clarifies all the parts that should be adjusted.
In doing the above, this pull request is a part of issue #3102.
=> [#3102] Mark the `Serializer` flow as deprecated

eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/reflection/AnnotationBasedEventSourcedEntityFactory.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/annotation/reflection/AnnotationBasedEventSourcedEntityFactoryTest.java
=> [#3503] fix: Check for `@EntityCreator` method is not detecting return type correctly

messaging/src/main/java/org/axonframework/updates/UpdateChecker.java, messaging/src/main/java/org/axonframework/updates/UpdateCheckerConfigurationEnhancer.java, messaging/src/main/java/org/axonframework/updates/detection/TestEnvironmentDetector.java, messaging/src/test/java/org/axonframework/updates/UpdateCheckerConfigurationEnhancerTest.java, messaging/src/test/java/org/axonframework/updates/UpdateCheckerTest.java
The check for the `UpdateChecker` was part of the start lifecycle handler.
However, this is executed in a separate thread, and as such the testsuite detection did not work.
This PR moves the check to the ConfigurationEnhancer, which *is* called in the same thread. So the components are never registered, nor started.
=> Fix UpdateChecker test detection

spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/AxonAutoConfigurationTest.java, spring/src/main/java/org/axonframework/spring/config/SpringComponentRegistry.java, spring/src/main/java/org/axonframework/spring/config/SpringLifecycleRegistry.java
The new Spring integration has roughly two flows of components, being:
1. Components coming from Spring's Application Context.
2. Components coming through Axon Framework's configuration API.
The former are _public_ by nature, while the latter are initially **local** to the `SpringComponentRegistry`.
To make these available to Spring's Application Context, we register each `Component` separately.
It **that** bit of code that did not yet initialize the lifecycle of a `Component`.
Initializing the lifecycle of a component in Spring comes down to registering dedicated `SmartLifecycle` beans for every start- or shutdown-handler that's part of the `Component`.
This pull request resolves this bug by invoking `Component#initLifecycle(SpringConfiguration, SpringLifecycleRegistry)`.
By passing the …
=> Register start/shutdown handlers of "local" `Components` as `SmartLifecycle` beans 

messaging/src/main/java/org/axonframework/updates/api/Artifact.java, messaging/src/main/java/org/axonframework/updates/api/UpdateCheckRequest.java, messaging/src/test/java/org/axonframework/updates/api/UsageRequestTest.java
Repeating the `lib` GET parameter in the update checker was not a good idea, as the parsing does not happen correctly.
This PR introduces a different way, where each library gets their own GET parameter in the format: `lib-my.group.id.artifact-id=version`. To shorten the URL, some common prefixed have been replacd, like 'lib-fw.axon-messaging' for 'lib-org.axonframework.axon-messaging' and 'lib-iq.console-client' for 'lib-io.axonq.console-client'.
=> Change update checker request parameters

docs/old-reference-guide/modules/events/pages/event-versioning.adoc, docs/old-reference-guide/modules/tuning/pages/event-snapshots.adoc
This pull request adds a section to the "Event Upcasting" page, specifically about upcasting aggregate snapshots.
Added, warnings are put in place whenever a `SnapshotFilter` is used, since the `SnapshotFilter` will make it so that a snapshot event **never** reaches the snapshot upcaster.
Lastly, I've done some minor tweaks on the pages that I've touched to enhance readability.
In doing the above, this pull request resolves #3518.
=> [#3518] Add Snapshot Event Upcasting section and `SnapshotFilter` usage warning

axon-server-connector/src/main/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModule.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/TopologyChange.java, axon-server-connector/src/main/java/org/axonframework/axonserver/connector/TopologyChangeListener.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/ServerConnectorConfigurerModuleTest.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/TopologyChangeTest.java, spring-boot-autoconfigure/src/main/java/org/axonframework/springboot/autoconfig/AxonServerAutoConfiguration.java, spring-boot-autoconfigure/src/test/java/org/axonframework/springboot/autoconfig/TopologyChangeListenerAutoConfigurationTest.java
This pull request introduces the `TopologyChangeListener` functional interface.
This functional interface extends the `Consumer<TopologyChange>`.
As such, it perfectly fits the new `ControlChannel#registerTopologyChangeHandler(Consumer<TopologyChange>)` method that was introduced in [this](https://github.com/AxonIQ/axonserver-connector-java/pull/435) Axon Server Connector for Java PR (version 2024.1.4).
Although the `TopologyChangeListener` functional interface is strictly not necessary, it does provide clear hook into Axon Framework's `Configurer` API for the `ServerConnectorConfigurerModule`.
Furthermore, it serves as a spot to have a comprehensive bit of JavaDoc to explain what the topology change listener is for and how to use it.
Lastly, I have introduced a `ConfigurerModule` in the …
=> Introduce the `TopologyChangeListener`

modelling/src/test/java/org/axonframework/modelling/repository/AccessSerializingRepositoryTest.java
Changed timeout from 10ms to 5ms and poll delay from 10ms to 20ms to eliminate race condition between orTimeout() and Awaitility assertion check.
----
The race condition was caused by having the same 10ms timeout for both the orTimeout() and the pollDelay(). This created a race where sometimes the timeout would fire before the assertion check, and sometimes after.
=> fix(test): resolve non-deterministic race condition in AccessSerializingRepositoryTest

messaging/src/main/java/org/axonframework/eventhandling/AnnotationEventHandlerAdapter.java, messaging/src/main/java/org/axonframework/messaging/annotation/AnnotatedHandlerInspector.java, modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateMemberAnnotatedChildEntityCollectionDefinition.java, modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateMemberAnnotatedChildEntityDefinition.java, modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateMemberAnnotatedChildEntityMapDefinition.java, modelling/src/main/java/org/axonframework/modelling/command/inspection/AggregateMetaModelFactory.java, modelling/src/main/java/org/axonframework/modelling/command/inspection/AnnotatedAggregateMetaModelFactory.java, modelling/src/main/java/org/axonframework/modelling/command/inspection/EntityModel.java
This fixes generics in several places where something is being _consumed_ and subsequently _produced_ based on a type.  Using wildcards in those cases will lead to the wrong conclusions.  For example, calling `EntityModel#modelOf` in this way was allowed:
EntityModel<Parent> em1 =  modelOf(Parent.class);
EntityModel<Parent> em2 =  modelOf(Child.class);
Here it may seem that `em1` is the same as `em2` but it really isn't, as `em2` will also include fields/annotations/etc from the child class, while `em1` will not have those.  To avoid this, defining `modelOf` to only accept the exact type will make `em2` a compile error.
I discovered this because some of the code doesn't compile with `ecj` due to a generic mismatch (all the way down to `AnnotatedHandlerInspector`).
=> ECJ compiler fix in the `AnnotatedHandlerInspector`

messaging/src/main/java/org/axonframework/updates/UpdateCheckerHttpClient.java, messaging/src/main/java/org/axonframework/updates/api/UpdateCheckRequest.java
This pull request performs several fixes for the [Axon Framework Update Checker](https://docs.axoniq.io/axon-framework-update-checker/) flow. 
Firstly, we have adjusts the `UpdateCheckerHttpClient` to manually handle redirects.
The use of the `HttpURLConnection` makes it so that on a redirect all headers are lost.
Although an intended security measure, we should still consciously set the update-checker-specific headers, as otherwise the intended task of this component cannot be fulfilled.
As such, the `UpdateCheckerHttpClient` is adjusted to handle a maximum of 5 redirects (AFAIK the max amount used by Google), and upon a redirect.
Furthermore, it ensure the query parameters set by the `UpdateCheckRequest` are maintained, for the similar reason that without, Axon Framework's Update …
=> [#3565] Several Axon Framework Update Checker fixes

messaging/pom.xml
This avoids a module conflict with several classes being present in the unnamed module and in the xml module.
=> Exclude xml-apis dependency as these are part of JDK 1.6+

messaging/src/main/java/org/axonframework/eventhandling/FirstTrackingToken.java, messaging/src/main/java/org/axonframework/eventhandling/LatestTrackingToken.java, messaging/src/main/java/org/axonframework/eventhandling/TrackingToken.java
- Introduced FirstTrackingToken to explicitly represent the start of a stream, replacing the use of null.
- Introduced LatestTrackingToken to represent the tail position of a stream.
- Both tokens implement TrackingToken and are exposed as static constants.
- Added static methods `TrackingToken.firstToken()` and `TrackingToken.latestToken()` for convenient access.
=> Introduce FirstTrackingToken and LatestTrackingToken (#3552)

messaging/src/main/java/org/axonframework/configuration/DefaultComponentRegistry.java, messaging/src/test/java/org/axonframework/configuration/ApplicationConfigurerTestSuite.java, messaging/src/test/java/org/axonframework/configuration/DefaultComponentRegistryTest.java, spring/src/main/java/org/axonframework/spring/config/SpringComponentRegistry.java
This pull request ensures that `ConfigurationEnhancers` are not accidentally registered twice.
I encountered that the `MessagingConfigurationDefaults`  `ConfigurationEnhancer` was registered twice; once through the `MessagingConfigurer` and once through the integrated Service Loader mechanism to discover `MessagingConfigurer`. 
A down-stream branch I was working on through this received duplicate `MessageHandlerInterceptors`, which may very definitely lead to unwanted side effects.
To resolve this, I have adjusted the `List` of  `ConfigurationEnhancers` to a `Map`, having a `String` key based on the `Class#getName` of the given `ConfigurationEnhancer`.
I have deliberately chosen `String` as the key, as that better aligns with our `SpringComponentRegistry`, which will search for …
=> Ensure `ConfigurationEnhancers` are not registered twice

eventsourcing/src/main/java/org/axonframework/eventsourcing/configuration/EventSourcingConfigurationDefaults.java, eventsourcing/src/main/java/org/axonframework/eventsourcing/eventstore/InterceptingEventStore.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/configuration/EventSourcingConfigurationDefaultsTest.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/InterceptingEventStoreTest.java, messaging/src/main/java/org/axonframework/commandhandling/InterceptingCommandBus.java, messaging/src/main/java/org/axonframework/configuration/MessagingConfigurationDefaults.java, messaging/src/main/java/org/axonframework/eventhandling/InterceptingEventSink.java, messaging/src/test/java/org/axonframework/commandhandling/InterceptingCommandBusTest.java, messaging/src/test/java/org/axonframework/configuration/MessagingConfigurationDefaultsTest.java, messaging/src/test/java/org/axonframework/eventhandling/InterceptingEventSinkTest.java
This pull request introduces two new components dedicated to intercepting `EventMessages` during publication.
These components are:
1. The `InterceptingEventSink` - a decorator around the `EventSink`.
2. The `InterceptingEventStore` - a decorator around the `EventStore`.
Both implementation create the `MessageDispatchInterceptorChain` once, to safe on chain-calculation costs.
In that regard they are styled equal to the `InterceptingCommandBus` (and in doing so providing a common grounds on how we construct our intercepting infrastructure).
As such, the `InterceptingEventSink` has an internal `static class` (the `InterceptingPublisher`) to ensure the chain of interceptor is only constructed once.
The `InterceptingEventStore` has a similar construct to ensure appending events by the …
=> [#3103] Event `MessageDispatchInterceptor` support for publishing and appending events

axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/AggregateBasedAxonServerEventStorageEngineTest.java, axon-server-connector/src/test/java/org/axonframework/axonserver/connector/event/AxonServerEventStorageEngineTest.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/JdbcEventStorageEngineTest.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/eventstore/jdbc/MysqlJdbcEventStorageEngineTest.java, integrationtests/src/test/java/org/axonframework/integrationtests/eventhandling/MultiStreamableMessageSourceTest.java, integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/EventProcessingAnnotatedEventSourcedPooledStreamingTest.java, integrationtests/src/test/java/org/axonframework/integrationtests/testsuite/student/EventProcessingDeclarativeEventSourcedPooledStreamingTest.java, messaging/src/test/java/org/axonframework/eventhandling/processors/streaming/pooled/PooledStreamingEventProcessorTest.java, test/src/test/java/org/axonframework/test/server/AxonServerContainerTest.java
This PR adds JUnit5 Tags `slow` and `flaky` to some tests. Those tags are not changing any default behaviour.
By doing so, you can address the tags via CLI of your Maven run.
`mvn clean install -DexcludedGroups=slow,flaky` would exclude marked tests...
`mvn clean install -Dgroups=slow,flaky` would run only marked tests...
=> Add slow and flaky tags to some tests

eventsourcing/src/main/java/org/axonframework/eventsourcing/annotation/AnnotationBasedEventCriteriaResolver.java, eventsourcing/src/test/java/org/axonframework/eventsourcing/annotation/AnnotationBasedEventCriteriaResolverTest.java
Reverting because of the bug:
https://github.com/AxonFramework/AxonFramework/issues/3680
=> Revert "feat(event-sourcing): support `@EventCriteriaBuilder` detection in nested classes (#3538)

messaging/src/main/java/org/axonframework/common/property/Property.java
Property declares only one method and making it a functionl interface helps to implement a custom Property (for example when creating a custom PropertyAccessStrategy).
=> chore: make functional interface

pom.xml
Adapts the documented config for mockito and JDK 21+ as described here: https://javadoc.io/doc/org.mockito/mockito-core/latest/org.mockito/org/mockito/Mockito.html#0.3
Without, running a mockito test can lead to console output like:
```
Mockito is currently self-attaching to enable the inline-mock-maker. This will no longer work in future releases of the JDK. Please add Mockito as an agent to your build as described in Mockito's documentation: https://javadoc.io/doc/org.mockito/mockito-core/latest/org.mockito/org/mockito/Mockito.html#0.3
WARNING: A Java agent has been loaded dynamically (.../.m2/repository/net/bytebuddy/byte-buddy-agent/1.17.7/byte-buddy-agent-1.17.7.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning …
```
=> chore: configure javaagent for mockito
